### ISSUE TITLE
Twitter: blocks php artisan from running

### ISSUE THREAD

**Issue by mblarsen** [SocialiteProviders/Providers#10]
The twitter provider blocks artisan from running If you do not specify a value for `client_id` and `client_secret` in `config/services.php`. The setup could be like this where you defer the values to the `.env` file:

```
    'twitter' => [
        'client_id' => env('TWITTER_KEY'),
        'client_secret' => env('TWITTER_SECRET'),
        'redirect' => env('TWITTER_REDIRECT_URI')
    ],
```

Typically when you deploy your app through some CI you might not have the `.env` file when running `composer install` and thus `php artisan optimize`.

Other providers like Facebook and Instagram has no issues with this.

Sample error:

```
$ php artisan --help

  [InvalidArgumentException]
  Missing client credentials key [secret] from options.

```

ps: A temporary solution, if you have this problem, is to just provide a dummy default value until an `.env` can be placed.

**Comment by faustbrian** [comment]
Just pushed a fix for that https://github.com/SocialiteProviders/Manager/commit/6b047ae3775a4e4905837137aafd4cc85878082e and tagged `v2.2.0`.

Whenever providers are registered but the application now runs in the terminal it should spoof config values now.
