### ISSUE TITLE
StreamElements - 400 Bad Request on asking for Token

### ISSUE THREAD

**Issue by bilbodog** [SocialiteProviders/Providers#1003]
Hi there,
When Socialite - StreamElements requests for the token, it gets the response of '400 Bad Request'.
You're not able to access the data it should've collected from the authorization.

Following error code is what happens:
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/16679010/230633940-2b73ae77-a111-444c-a222-7cb22e9d9fa6.png">

It might be that the token request is malformed? But I am just curious why it says: "The client is not authorized to request a token using this method." This might be an error from StreamElements? (I have sent an email to StreamElements asking about this issue as well)

In the documentation it states that the POST to https://api.streamelements.com/oauth2/token needs to be of the Content-Type: "application/x-www-form-urlencoded", is this fulfilled?

Documentation link: https://dev.streamelements.com/docs/api-docs/cd02cda5171ea-o-auth2

**Comment by atymic** [comment]
Yep, it's urlencoded (guzzle form params). Issue is somewhere else.

![Screen Shot 2023-04-10 at 15 53 35](https://user-images.githubusercontent.com/50683531/230835941-c0a696d8-ed07-4f87-98fc-4b59e88b67fc.png)

**Comment by bilbodog** [comment]
Thank you very much, I have forwarded this issue to the StreamElements team. Then I will return with an update on this.

**Comment by sandeepthakkar23** [comment]
Hi Guys,

I am getting below issues when I am calling $socialUser = Socialite::driver($provider)->userFromToken($token);

<!--
TypeError: SocialiteProviders\Apple\Provider::getUserRequest(): Return value must be of type array, null returned in file D:\xampp\htdocs\maisuma-backend\vendor\socialiteproviders\apple\Provider.php on line 256

I have set all the required setting as per this tutorial's: https://devpeel.com/implement-apple-sign-in-with-laravel/


Can anybody help me for this.


Thank You!1

**Comment by bilbodog** [comment]
> Hi Guys,
> 
> I am getting below issues when I am calling $socialUser = Socialite::driver($provider)->userFromToken($token);

Is this specifically for the "streamelements" provider, or in general?
What provider (media) are you trying to use?

**Comment by bilbodog** [comment]
Am I doing anything wrong here, @atymic ? Media is "streamelements".
$media = "streamelements";
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/16679010/230940968-bb9b3b85-8a6d-4f91-a029-1ef219c30420.png">
In this example it fails at line 50. (Normally: $data = Socialite::driver($media)->user(); but json_encode used for debugging)

I have also tried with my own PHP, without luck, here is the example where I have just taken the code from Socialite authorization, trying to get the code:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/16679010/230943815-395213fc-8577-44e6-b85e-7c2e9bd7717f.png">
In this example it fails at line 55. Since it cannot read the response.
I get the same error with my example as when I use Socialite.

Thanks in advance.

**Comment by sandeepthakkar23** [comment]
> to

I am implementing for apple login using apple socialite provider. In that getting issue when calling userFromToken() method.

**Comment by bilbodog** [comment]
> > > > to
> > > 
> > > 
> > > I am implementing for apple login using apple socialite provider. In that getting issue when calling userFromToken() method.
> > 
> > 
> > Ohh, okay. This issue is only about StreamElements, sorry.
> 
> So any solution for apple integration for shared issues?

I am not the one in charge of the GitHub, but usually they prefer to keep things separated, since it's very hard isolating issue as it is, so maybe create a new issue and describe your issue and what you've done for debugging and see what they can help you with. :)

**Comment by c4ldas** [comment]
Hi @bilbodog, I worked with you on a similar issue on SE Discord and was informed this issue was opened so I came here to check that together with you.

Unfortunately, I am not skilled in PHP, so won't be able to help you with the code, but hope more people working together we can get somewhere :)

I was in touch with the SE team and I tested the requests using CURL and JavaScript and both worked with no issues. They were request successfully a token request using your Client ID and Secret.

I see the error mentioned is `"unauthorized_client":"the client is not authorized to request a token using this method"`.
This error is usually related to invalid data being sent on the request. Are you using the correct `Client ID` and `Client Secret` (in case you have more than one)? I've heard some companies which mixed their Client IDs and Secrets, so it would never work. 
Have you tried to use Insomnia or Postman for that request to confirm they are working fine? 

Using curl as an example: 
```text
curl -X POST "https://api.streamelements.com/oauth2/token" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code" -d "client_id=********" -d "client_secret=********" -d "code=********" -d "redirect_uri=https://example.com/callback"
```

Response would be: 
```json
{ 
 "access_token":"t7BK6bFM5shQSTi9HoT1P3",
  "expires_in":2592000,
  "refresh_token":"GT6iZQ24buWGq4Z2v51pY2",
  "scope":"channel:read activities:read activities:write overlays:read overlays:write tips:read tips:write loyalty:read loyalty:write bot:read bot:write",
  "token_type":"Bearer"
}
```

**Comment by bilbodog** [comment]
> > Hi @bilbodog, I worked with you on a similar issue on SE Discord and was informed this issue was opened so I came here to check that together with you.
> > Unfortunately, I am not skilled in PHP, so won't be able to help you with the code, but hope more people working together we can get somewhere :)
> > I was in touch with the SE team and I tested the requests using CURL and JavaScript and both worked with no issues. They were request successfully a token request using your Client ID and Secret.
> > I see the error mentioned is `"unauthorized_client":"the client is not authorized to request a token using this method"`. This error is usually related to invalid data being sent on the request. Are you using the correct `Client ID` and `Client Secret` (in case you have more than one)? I've heard some companies which mixed their Client IDs and Secrets, so it would never work. Have you tried to use Insomnia or Postman for that request to confirm they are working fine?
> > Using curl as an example:
> > ```
> > curl -X POST "https://api.streamelements.com/oauth2/token" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code" -d "client_id=********" -d "client_secret=********" -d "code=********" -d "redirect_uri=https://example.com/callback"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Response would be:
> > ```json
> > { 
> >  "access_token":"t7BK6bFM5shQSTi9HoT1P3",
> >   "expires_in":2592000,
> >   "refresh_token":"GT6iZQ24buWGq4Z2v51pY2",
> >   "scope":"channel:read activities:read activities:write overlays:read overlays:write tips:read tips:write loyalty:read loyalty:write bot:read bot:write",
> >   "token_type":"Bearer"
> > }
> > ```
> 
> Thanks for reply. I have checked, it's working fine with CURL request. But not the socialized package of Laravel that particular method.

Hi @sandeepthakkar23,
I have already tried with Postman but I have just tried with exactly what you've sent, doesn't work either.

<img width="2549" alt="image" src="https://user-images.githubusercontent.com/16679010/235292337-ebb7b031-0662-4443-b499-bf5bc3ef63e5.png">

**Comment by bilbodog** [comment]
I have been in contact with StreamElements and they confirmed that I had a typo in the secret key, so now it works, but it still doesn't work with Socialite, so now the problem is clear, that there must have been some change or a bug, that results in Socialite not working with StreamElements.

Is this something you are already aware of @atymic ?

**Comment by atymic** [comment]
Can you confirm that the actual oauth flow works by adding a `dd($token)` here? Try that manually on the API and see what happens
https://github.com/SocialiteProviders/Providers/blob/master/src/StreamElements/Provider.php#L39

**Comment by bilbodog** [comment]
> https://github.com/SocialiteProviders/Providers/blob/master/src/StreamElements/Provider.php#L39

It seems to work, here is a screenshot with some obscuring:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/16679010/235848328-0bd260d9-82d8-4413-a9d6-50823134138b.png">

I can also head into Postman and revoke the token, so I can confirm it gets the token and I can rekove it through Postman and their endpoint:
https://api.streamelements.com/oauth2/revoke?client_id=<ClientId>&token=-jih89bHQmKvlKj3HNJPgg

**Comment by atymic** [comment]
@bilbodog feel free to PR a fix if you can debug the issue

**Comment by HashGateApp** [comment]
@atymic 

I've identified the issue and implemented the patch in the PR above. If PR is approved, this can be closed
