### ISSUE TITLE
Apple - Broken since 5.5.0

### ISSUE THREAD

**Issue by golsson** [SocialiteProviders/Providers#1015]
lcobucci/jwt has removed a number of functions:

- Lcobucci\JWT\Configuration::forUnsecuredSigner()
- Lcobucci\JWT\Signer\Key\InMemory::empty()
- Lcobucci\JWT\Signer\None
- Lcobucci\JWT\Token\Signature::fromEmptyData()

See https://lcobucci-jwt.readthedocs.io/en/stable/upgrading/#removal-of-none-algorithm - however 5.5.0 still makes use of `Lcobucci\JWT\Configuration::forUnsecuredSigner()` here https://github.com/SocialiteProviders/Providers/blob/e5cbb4b0c4dd2e20488915a585eda4cac5e25533/src/Apple/Provider.php#L148 which breaks the functionality of this package after upgrade to lcobucci/jwt 5.0

@hamrak @atymic

**Comment by atymic** [comment]
Can you PR a fix? Otherwise I will revert the previous PR

**Comment by hamrak** [comment]
Please check my pull request with bugfix, for me it works.
And bonus, I added the option to enter a certificate instead of a secret key.

**Comment by atymic** [comment]
@hamrak can you please split this into two PRs? Bugfix for issue first please and then you can do the other changes. In the meantime i have reverted.

**Comment by hamrak** [comment]
Done. Can someone check #1018 and #1019 if it works for you too? It works for me, I tested it, but sometimes ... Thank you.
