### ISSUE TITLE
Changes reverted/ not included for SuperOffice provider update

### ISSUE THREAD

**Issue by SuperDJ** [SocialiteProviders/Providers#1023]
@atymic some changes on master of https://github.com/SocialiteProviders/SuperOffice/compare/4.1.0...master have some how not been released with [4.2](https://github.com/SocialiteProviders/SuperOffice/compare/4.1.0...4.2.0).

**Comment by atymic** [comment]
Sorry which changes are the issue?

**Comment by SuperDJ** [comment]
It's about these changes https://github.com/SocialiteProviders/SuperOffice/compare/4.2.0...master.

**Comment by SuperDJ** [comment]
@atymic ping

**Comment by atymic** [comment]
Sorry, what's the issue/fix? You want a new version tagged?

**Comment by SuperDJ** [comment]
@atymic  the changes/ differences that are shown here https://github.com/SocialiteProviders/SuperOffice/compare/4.2.0...master are not released. Those changes should have been merged with https://github.com/SocialiteProviders/Providers/pull/1007, but appear to be removed/ reverted with https://github.com/SocialiteProviders/Providers/pull/1008.

**Comment by atymic** [comment]
Tagged 4.2.0 which seems to have fixed the issue.
