### ISSUE TITLE
Composer package out of date for Adobe provder

### ISSUE THREAD

**Issue by jxxe** [SocialiteProviders/Providers#1034]
The Adobe provider (`socialiteproviders/adobe`) has this error:

```
Type of SocialiteProviders\Adobe\Provider::$scopes must not be defined (as in class Laravel\Socialite\Two\AbstractProvider)
```

It's caused by this type declaration, since the `$scopes` property isn't typed in Laravel's codebase:

![](https://github.com/SocialiteProviders/Providers/assets/64276359/dded2ac3-28aa-4132-9c87-7fe9d188b6bd)

The repo has [the correct code](https://github.com/SocialiteProviders/Adobe/blob/master/Provider.php#L17), but the Composer package hasn't been updated yet.

**Comment by jxxe** [comment]
Additionally, the scopes appear to be incorrect. They should be `AdobeID` and `openid`.  The `email` and `profile` scopes are invalid.

**Comment by jxxe** [comment]
The `$code` parameter in `getTokenFields()` is also missing, in both the repo and published package.

https://github.com/SocialiteProviders/Adobe/blob/master/Provider.php#L33

**Comment by atymic** [comment]
Feel free to PR :)

**Comment by atymic** [comment]
Will release a fix with both issues

**Comment by atymic** [comment]
Released
