### ISSUE TITLE
Saml2: Collisions in metadata caching

### ISSUE THREAD

**Issue by marcovo-peercode** [SocialiteProviders/Providers#1037]
https://github.com/SocialiteProviders/Providers/blob/6d291f4e33dd04632d92d43e4428e352dd7a721f/src/Saml2/Provider.php#LL303C53-L303C53

This method caches values using a hardcoded key irrespective of the URL being fetched. When the URL changes, or one e.g. uses multiple SAML2 configurations, this can cause collisions.

Could it be possible to make these cache keys scoped to the URL? Or otherwise, make it so that the key can be overridden in a child Provider class?

**Comment by atymic** [comment]
@27pchrisl

**Comment by 27pchrisl** [comment]
Thanks @marcovo-peercode, I have created a PR to resolve this (@atymic).
