### ISSUE TITLE
Getting additional claims in azureadb2c provider

### ISSUE THREAD

**Issue by cwp-michaell** [SocialiteProviders/Providers#1040]
I'm trying to configure the azureadb2c provider to claim additional fields from azureb2c tenant. These aren't custom fields they are standard fields like city/email.
Currently all I get back are these values
![image](https://github.com/SocialiteProviders/Providers/assets/47455948/2482be09-23ae-40e1-af7f-38e26592992b)
I've added these fields under the accepted claims of the user flow
![image](https://github.com/SocialiteProviders/Providers/assets/47455948/77a4923d-4bd8-41e6-80fd-bda737b2400b)

Any help would be appreciated

**Comment by atymic** [comment]
@fujie @lsmith77 @kurucu any ideas?

**Comment by kurucu** [comment]
Hey guys, you need to add them to the add them to the user attributes, assign them to a claim ([see here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes?pivots=b2c-user-flow#use-a-custom-attribute-in-your-user-flow)) and then send the claim as part of your ouath flow [scope](https://laravel.com/docs/10.x/socialite#access-scopes).

I haven't double checked this, just going from memory. Let me know how you go.

**Comment by fujie** [comment]
Let me clarify that all of attributes you intend to send from Azure AD B2C are included in id_token? To receive claims from Azure AD B2C, it is required to include these claims in id_token.

**Comment by cwp-michaell** [comment]
Thank you for coming back to me.
It turns out Azure won't return the email value unless sign-up with email is configured, even if you populate the email field. I was then unable to retrieve the rest of the values.
