### ISSUE TITLE
SocialiteProviders/Okta needs new release

### ISSUE THREAD

**Issue by dennis-koster** [SocialiteProviders/Providers#1043]
Hi,

I was following the [documentation](https://github.com/SocialiteProviders/Okta#refresh-token) of the SocialiteProviders/Okta package to obtain a new access token, providing a refresh token.

It appears this functionality has been added to the master branch, but it has never been tagged.

We are using the latest version (4.2.1) and that version does not contain the `getRefreshTokenResponse()` method as documented.

**Comment by atymic** [comment]
Tagged sorry :)
