### ISSUE TITLE
Archive Slack Provider

### ISSUE THREAD

**Issue by jbrooksuk** [SocialiteProviders/Providers#1045]
Firstly, thank you for maintaining a Slack Socialite provider.

At Laravel, we've now shipped a Slack provider with Socialite itself. The provider also has support for Slack's [Bot tokens](https://laravel.com/docs/10.x/socialite#slack-bot-scopes), which are the preferred way for most integrations.

With that, the `SocialiteProviders/Slack` provider may be archived 😃 

Thank you again!

**Comment by atymic** [comment]
Updated docs and deprecated on packagist :)

**Comment by atymic** [comment]
Actually turns out I don't have perms to abandon, will ask @m1guelpf to do.

**Comment by m1guelpf** [comment]
Done!

**Comment by atymic** [comment]
Thanks :D

**Comment by maartenpaauw** [comment]
First of all, I want to express gratitude to the Laravel team for maintaining an official Slack socialite provider. However, I have a couple of questions regarding the decision to mark this package as deprecated:

To what extent is the Slack socialite provider considered deprecated? Following its deprecation, numerous changes have been implemented, including the ability to request both a bot token and a user token in a single request. Furthermore, the replacement official Laravel socialite Slack provider does not support requesting both a user token and a bot token in a single request.

**Comment by atymic** [comment]
@maartenpaauw we should un-archive it as you mentioned. I will PR to update the docs, and @m1guelpf will need to do the actual un-abandon on packagist

**Comment by maartenpaauw** [comment]
Thank you! 🙏
