### ISSUE TITLE
Driver [tiktok] not supported.

### ISSUE THREAD

**Issue by gilbert-weboptimizers** [SocialiteProviders/Providers#1051]
Hello,

I implemented the tiktok socialite driver as per the documentation in laravel 10 but i'm encountering the following issue: 
Driver [tiktok] not supported.

web.php

```
Route::get('/tiktok/auth/redirect/', function () {     
    return Socialite::driver('tiktok')->redirect();
});
```

Event Service Provider:
```

protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
            
        ],
        [
            \SocialiteProviders\Manager\SocialiteWasCalled::class => [
                // ... other providers
                \SocialiteProviders\Google\GoogleExtendSocialite::class.'@handle',
                \SocialiteProviders\TikTok\TikTokExtendSocialite::class.'@handle',
            ],
        ],
    ];
```

The implementation for the Google driver works fine as intended

**Comment by parelio** [comment]
Same problem here. Any 'official' driver works. Any SocialiteProviders provider doesn't work.

**Comment by atymic** [comment]
I've tested in a fresh install and it's working correctly. 
What laravel version and package versions are you running?

**Comment by gilbert-weboptimizers** [comment]
The following are the versions in composer.json

"laravel/framework": "^10.10"
"laravel/socialite": "^5.8"
"socialiteproviders/tiktok": "^5.0"

**Comment by atymic** [comment]
Could you please upload a reproduction repo?
Thanks

**Comment by atymic** [comment]
If you upload a repro repo please comment. Closing in the meantime.

**Comment by gilbert-weboptimizers** [comment]
Tried it on a fresh install and still encountering the same problem.

Uploaded the files for this fresh install to https://github.com/gilbert-weboptimizers/laravel-tiktok/tree/main/tiktok-app

**Comment by incognitozen** [comment]
Has this been patched ? @atymic
