### ISSUE TITLE
[FusionAuth] ErrorException: Undefined array key "family_name"

### ISSUE THREAD

**Issue by timyourivh** [SocialiteProviders/Providers#1070]
Not all of our users have a known "name", "given_name" or "family_name" available in the response returned by FusionAuth. If no name was given, the driver throws an exception (*ErrorException: Undefined array key "family_name"*) at this line:

https://github.com/SocialiteProviders/Providers/blob/34e53fcda539176fcf69ee6c112d5fd0cf39cbeb/src/FusionAuth/Provider.php#L95
 
These name fields are all optional in FusionAuth and will be undefined when not filled.

To fix this, I suggest these changes:

```diff
-'name' => $user['name'] ?? trim($user['given_name'] ?? ''.' '.$user['family_name'] ?? ''), 
+'name' => $user['name'] ?? trim(($user['given_name'] ?? '').' '.($user['family_name'] ?? '')),
```

This results in an empty string if all "name", "given_name" and "family_name" are missing.

**Comment by atymic** [comment]
Feel free to PR :)
