### ISSUE TITLE
Spotify: Email not returned

### ISSUE THREAD

**Issue by Mirko-Tebaldi** [SocialiteProviders/Providers#1087]
In my callback, I dod

    $spotify_user = Socialite::driver('spotify')->user();

Then, dumpinh the user, I can see

![image](https://github.com/SocialiteProviders/Providers/assets/114985433/57273d13-5362-492d-969e-4c41e4a38669)

as you can see, email field is empty.

I cannot find doc about optional scopes to activate on spotify developer dashboard, or other things to do with the package

**Comment by realtebo** [comment]
Found ! 

    ->scopes(['user-read-email'])

List of scopes into the official doc (I suggest kindly to add this link to the official doc)

https://developer.spotify.com/documentation/web-api/concepts/scopes

**Comment by atymic** [comment]
Added in https://github.com/SocialiteProviders/Providers/commit/da904b57acadf9303e2747f725662cfb61db1636
