### ISSUE TITLE
Driver [discord] not supported.

### ISSUE THREAD

**Issue by leodlplq** [SocialiteProviders/Providers#1089]
Hi, I'm having trouble using the discord provider. I did all the installation as the documentation tell us to do. Here is a quick recap : 

### Step 1

In `app.php`, I added : `\SocialiteProviders\Manager\ServiceProvider::class`

### Step 2

Added the config to `config/services.php`

```
'discord' => [    
  'client_id' => env('DISCORD_CLIENT_ID'),  
  'client_secret' => env('DISCORD_CLIENT_SECRET'),  
  'redirect' => env('DISCORD_REDIRECT_URI'),
  
  // optional
  'allow_gif_avatars' => (bool)env('DISCORD_AVATAR_GIF', true),
  'avatar_default_extension' => env('DISCORD_EXTENSION_DEFAULT', 'jpg'), // only pick from jpg, png, webp
],
```
added the data to the .env file and even restarted my containers. 

### Step 3

Added Discord in $listen variables in `EventServiceProvider.php`

```
...
protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
            \SocialiteProviders\Manager\SocialiteWasCalled::class => [
                // add your listeners (aka providers) here
                \SocialiteProviders\GitHub\GitHubExtendSocialite::class.'@handle',
                \SocialiteProviders\Discord\DiscordExtendSocialite::class.'@handle',
            ],
        ],
    ];
...
```

### Step 4

Create function that uses `discord` driver

```
class DiscordController extends Controller
{
    public function redirect()
    {
        return Socialite::driver('discord')->redirect();
    }

    public function callback()
    {
        try {
            $user = Socialite::driver('discord')->user();
            dd($user);

        } catch (\Exception $e) {
            dd($e);
        }
    }
}
```

and call them in `web.php`

### Final step

When I try to log with discord, I got a error screen that tells me that : Driver [discord] not supported.

<img width="1508" alt="image" src="https://github.com/SocialiteProviders/Providers/assets/45670576/e985899a-6fe1-43d1-8fe4-646742c7084a">

___________

Did I missed something ? I followed the all documentation but didn't manage to make it work :/ 

Here is the repo if anyone would like to try on their side : https://github.com/leodlplq/laravel-test-oauth

Thank you in advance.

**Comment by mattiasghodsian** [comment]
I had the same issue, i added  the `web` middleware to the route group
```php
Route::prefix('/auth')->middleware(['web'])->group(function () {
    Route::get('/redirect', function () {
        return Socialite::driver('discord')->redirect();
    });
});
```

**Comment by leodlplq** [comment]
> I had the same issue, i added the `web` middleware to the route group

I wrapped both routes with the `web`middleware but I still get the same error :/

**Comment by mattiasghodsian** [comment]
Also move ` \SocialiteProviders\Manager\SocialiteWasCalled` array out of Registered
```php
protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            \SocialiteProviders\GitHub\GitHubExtendSocialite::class.'@handle',
            \SocialiteProviders\Discord\DiscordExtendSocialite::class.'@handle',
        ],
    ];
...

**Comment by leodlplq** [comment]
Thank you, that was the problem !

**Comment by mattiasghodsian** [comment]
@leodlplq I'm glad to hear👍
