### ISSUE TITLE
userFromToken undefined method

### ISSUE THREAD

**Issue by josemoreno-juicestudio** [SocialiteProviders/Providers#1096]
Hello!

I'm trying to use Apple to login to my mobile app but I'm getting an error because it says the method is not defined.

![photo_2023-10-13 14 31 10](https://github.com/SocialiteProviders/Providers/assets/144258831/d5f6b0c2-c20c-4ef7-a9b9-a080434a31af)

**Comment by leonardocaitano** [comment]
use Laravel\Socialite\Facades\Socialite;

**Comment by josemoreno-juicestudio** [comment]
I am using it, but it still gives an error.
![photo_2023-10-13 20 21 00](https://github.com/SocialiteProviders/Providers/assets/144258831/b9bebe2c-0189-4daf-b023-17e05b4d9f85)

**Comment by josemoreno-juicestudio** [comment]
Any help?

**Comment by moha-ep** [comment]
> Any help?

Use with instead of driver:

`Socialiete::driver('x')->user()` ❌

`Socialiete::with('x')->user()` ✔️
