### ISSUE TITLE
A new release is needed 

### ISSUE THREAD

**Issue by moha-ep** [SocialiteProviders/Providers#1101]
There are many providers that have changes in git and their last release is years old and when they are installed by composer it installs a version with bugs...

Example:
Pinterest latest version 4.2 v (with bugs) release date14 oct 2021.
Latest fixes in git: 31 Aug 2023 (currently no bugs)

I would like to request a new release with the fixes done.  

Thnx

**Comment by atymic** [comment]
Tagged, any other ones let me know
