### ISSUE TITLE
Driver [figma] not supported

### ISSUE THREAD

**Issue by eta-orionis** [SocialiteProviders/Providers#1103]
Line 16 of FigmaExtendSocialite.php in the Figma driver extends Socialite under the name `Figma` (notice capital F), but the documentation refers to `figma` in lowercase. Following the documentation leads to the aforementioned error.

`        $socialiteWasCalled->extendSocialite('Figma', Provider::class);`

I'm not providing a pull request here because I frankly do not know what's best: fix the documentation (which makes the package different from other packages, leading to head scratches) or fix the extension, therefore breaking existing installs and leading to other head scratches.

**Comment by atymic** [comment]
I will PR fix to name and release new major version.
