### ISSUE TITLE
Figma's Authorization Header is wrong

### ISSUE THREAD

**Issue by eta-orionis** [SocialiteProviders/Providers#1104]
https://github.com/SocialiteProviders/Providers/blob/f6e4b21d66db2b0eaf2672d61f5d891c43da53cc/src/Figma/Provider.php#L41

When using OAuth, Figma expects `Authorization: Bearer <token>`, not `X-FIGMA-TOKEN`

(See [Figma Docs](https://www.figma.com/developers/api#oauth2), section "Using the Oauth2 Token".)

Using the package as it is right now will result in a 403 error.

**Comment by lucasmichot** [comment]
Can you make a PR @eta-orionis ?
