### ISSUE TITLE
StreamElementsProvider needs a new version release on composer

### ISSUE THREAD

**Issue by HashGateApp** [SocialiteProviders/Providers#1113]
The last release of StreamElements provider on [composer](https://packagist.org/packages/socialiteproviders/streamelements) was in Dec 2020 and is no longer compatible. Would it be possible to get a new release to on composer to reflect the latest changes?

**Comment by atymic** [comment]
Tagged 5.0.0 :)

**Comment by HashGateApp** [comment]
Thank you @atymic, one more time please 🥇

**Comment by atymic** [comment]
Done :)

**Comment by HashGateApp** [comment]
Thank you friend!
