### ISSUE TITLE
Microsoft provider does not return refresh_token

### ISSUE THREAD

**Issue by SuperDJ** [SocialiteProviders/Providers#1123]
Maybe I'm missing something but on login with the Microsoft provider there is no refresh_token returned.

I have the following redirect:
```php
$config = new Config(
            config( 'services.microsoft.client_id' ),
            config( 'services.microsoft.client_secret' ),
            config( 'services.microsoft.redirect' ),
            [ 'tenant' => config( 'services.microsoft.tenant' ) ]
        );

        return Socialite::driver( 'microsoft' )
            ->scopes( [ 'Calendars.Read' ] )
            ->setConfig( $config )
            ->stateless()
            ->redirect();
```

On  callback
```php
$microsoftUser = Socialite::driver( 'microsoft' )
            ->stateless()
            ->user();
dd($micrososftUser);
```

I get the following response:

![image](https://github.com/SocialiteProviders/Providers/assets/6484766/62f54454-a1fd-4ca4-9a07-c54c72533ab3)

**Comment by SuperDJ** [comment]
Sorry, found https://github.com/SocialiteProviders/Providers/issues/624 and adding the `offline_access` scope fixed it. Perhaps this is something to add to the docs.

**Comment by atymic** [comment]
Feel free to PR to the docs :)

**Comment by SuperDJ** [comment]
Added https://github.com/SocialiteProviders/Providers/pull/1124
