### ISSUE TITLE
Discord - Additional scope support natively

### ISSUE THREAD

**Issue by keesh7663** [SocialiteProviders/Providers#115]
Hi, do you have plans to natively implement adding the other available scopes in gateway v6 (guild list, connections specifically)?  These are extremely helpful tidbits to have when creating a web UI for a bot.

**Comment by faustbrian** [comment]
https://laravel.com/docs/5.5/socialite#access-scopes

**Comment by keesh7663** [comment]
durp, not sure how I missed that...  thanks for the quick reply!
