### ISSUE TITLE
OIDC token request results in failure multiple_client_credentials

### ISSUE THREAD

**Issue by krodox** [SocialiteProviders/Providers#1151]
```php
 $user = Socialite::driver('okta')->user();
```

"Cannot supply multiple client credentials"

The client library is likely passing client credentials in both the headers and post body of the API call. Okta does not allow this, while other providers may be more lax in this requirement. You can only pass the credentials in one of these but not both.

**Comment by atymic** [comment]
Fixed by upstream revert, update our socialite package version
https://github.com/SocialiteProviders/Providers/pull/1150
