### ISSUE TITLE
Azure: Add support for optional post_logout_redirect_uri

### ISSUE THREAD

**Issue by Tamas-hi** [SocialiteProviders/Providers#1173]
# Support for optional post logout redirect uri

## Issue
Right now, the library doesn't support the case when you don't want to redirect the user after a succesful logout. I needed this case, and I think it makes sense to make it available through this provider.

## Solution
Set the $redirectUri as an optional parameter to keep it backward compatible. Post_logout_redirect_uri is meant to be optional also according to the OpenID (https://openid.net/specs/openid-connect-rpinitiated-1_0.html)

**Comment by Tamas-hi** [comment]
Thanks for merging my contribution. Can we expect a release in the near future so that we can use this functionality? Thanks!

**Comment by atymic** [comment]
Tagged sorry :)
