### ISSUE TITLE
Microsoft-azure laravel 11 support

### ISSUE THREAD

**Issue by fabiendeloye** [SocialiteProviders/Providers#1182]
I try to add Microsoft Azure to my fresh Laravel 11 installation, 
but It's not working...
It's compatible with laravel 11 ?

I have this error : 
SocialiteProviders\Azure\AzureExtendSocialite does not extend Laravel\Socialite\Two\AbstractProvider

Thanks

**Comment by KenGuggelmeyer** [comment]
Same problem here but with the Microsoft provider. 

I modified the AppServiceProvider with the following:

Event::listen(function (\SocialiteProviders\Manager\SocialiteWasCalled $event) {
    $event->extendSocialite('microsoft',  \SocialiteProviders\Microsoft\MicrosoftExtendSocialite::class,);
});

and I'm receiving the following:

SocialiteProviders\Microsoft\MicrosoftExtendSocialite does not extend Laravel\Socialite\Two\AbstractProvider

**Comment by NickArcher** [comment]
> I try to add Microsoft Azure to my fresh Laravel 11 installation, but It's not working... It's compatible with laravel 11 ?
> 
> I have this error : SocialiteProviders\Azure\AzureExtendSocialite does not extend Laravel\Socialite\Two\AbstractProvider
> 
> Thanks

Try this:

In **AppServiceProvider.php**

```php
Event::listen(function (\SocialiteProviders\Manager\SocialiteWasCalled $event) {
$event->extendSocialite('microsoft', \SocialiteProviders\Microsoft\Provider::class,);
});
``` 

and then 

```php
php artisan cache:clear
```

**Comment by KenGuggelmeyer** [comment]
That fixed it for me!

**Comment by atymic** [comment]
Docs added for all providers :)

**Comment by fabiendeloye** [comment]
Thanks it's fixed for me too :)
