### ISSUE TITLE
Can we add the "department" attribute to the azure provider's mapped fields?

### ISSUE THREAD

**Issue by PaddingtonBrown** [SocialiteProviders/Providers#1223]
Relates to https://github.com/SocialiteProviders/Providers/issues/745

**Comment by PaddingtonBrown** [comment]
In azure provider https://github.com/SocialiteProviders/Providers/blob/1cf2b81f84a85e89f8c96ed1ad7344d1fd3ae3f4/src/Azure/Provider.php#L4

**Comment by PaddingtonBrown** [comment]
https://github.com/SocialiteProviders/Providers/pull/1224

**Comment by atymic** [comment]
@PaddingtonBrown is there a reason why you can't use the microsoft provider? We are aiming to merge them soon.

**Comment by PaddingtonBrown** [comment]
@atymic the microsoft provider doesn't have the department field too. I would/could add it to that provider too.

**Comment by atymic** [comment]
Please PR it there :)

**Comment by PaddingtonBrown** [comment]
@atymic here is a new pull request for the change https://github.com/SocialiteProviders/Providers/pull/1228

**Comment by PaddingtonBrown** [comment]
Hi @atymic at what point will this get released as a new package version on packagist? Cheers

**Comment by atymic** [comment]
Tagged sorry!
