### ISSUE TITLE
Laravel Passport fails to return approved scopes

### ISSUE THREAD

**Issue by zorenkonte** [SocialiteProviders/Providers#1229]
Laravel Passport is not returning approved scopes, unlike other providers such as GitHub and Google.

When logging the [response](https://github.com/SocialiteProviders/Manager/blob/dea5190981c31b89e52259da9ab1ca4e2b258b21/src/OAuth2/AbstractProvider.php#L53) in the  [user method](https://github.com/SocialiteProviders/Manager/blob/dea5190981c31b89e52259da9ab1ca4e2b258b21/src/OAuth2/AbstractProvider.php#L43), the response is:

```
array (
  'token_type' => 'Bearer',
  'expires_in' => 31536000,
  'access_token' => 'access_token',
  'refresh_token' => 'refresh_token',
) 
```
As a result, [`setApprovedScopes($this->parseApprovedScopes($response))`](https://github.com/SocialiteProviders/Manager/blob/dea5190981c31b89e52259da9ab1ca4e2b258b21/src/OAuth2/AbstractProvider.php#L67) consistently returns null.

### Steps to Reproduce:

1. Redirect call
```
Socialite::driver('laravelpassport')
                ->scopes(['user:email'])
                ->stateless()
                ->redirect()->getTargetUrl()
```

2.  Callback call
``` 
Socialite::driver('laravelpassport')->stateless()->user()
```

The expected behavior is for the approved scopes to match those requested during authorization, as observed with other providers.

<img width="910" alt="image" src="https://github.com/SocialiteProviders/Providers/assets/29701857/b8e484ad-b34e-460e-b1d0-91c2817139c2">

### Screenshots

1. Laravel Passport Response (Scopes are Empty)
<img width="830" alt="image" src="https://github.com/SocialiteProviders/Providers/assets/29701857/430e6fa8-ab63-424a-a60a-ed755247b3ac">

2. GitHub Response (Scopes are Returned).
```
// Result if you log the response of GitHub in the user() method. It returns 'scope' property.
array (
    'access_token' => 'token',
    'token_type' => 'bearer',
    'scope' => 'user:email',
)  
```

<img width="681" alt="image" src="https://github.com/SocialiteProviders/Providers/assets/29701857/f808a0c0-bf78-4236-9162-aecfd52e2e29">

**Comment by atymic** [comment]
Is this not an issue with socialite not sending the approved scopes back, not with the socialite provider.
Maybe PR to socialite to include scopes in reply?
