### ISSUE TITLE
Can we add Employee ID to the Microsoft Provider's attribtues?

### ISSUE THREAD

**Issue by PaddingtonBrown** [SocialiteProviders/Providers#1233]
Can we add Employee ID to the Microsoft Provider's attribtues?

**Comment by PaddingtonBrown** [comment]
https://github.com/SocialiteProviders/Providers/pull/1234

**Comment by PaddingtonBrown** [comment]
@atymic

**Comment by PaddingtonBrown** [comment]
Hi @atymic can we get a package version bump for this change too. Cheers.

**Comment by atymic** [comment]
Done
