### ISSUE TITLE
"Access denied for user 'root'@'localhost" when attempting to auth with Microsoft 

### ISSUE THREAD

**Issue by amy1hwang** [SocialiteProviders/Providers#1244]
The handleProviderCallback() function looks like this:
```
 public function handleProviderCallback()
    {
        try {
            $socialiteUser = Socialite::driver('microsoft')
                ->scopes(['openid', 'profile', 'email'])
                ->stateless()
                ->user();

            // Debugging: Log the retrieved user data
            Log::info('Microsoft User: ' . json_encode($socialiteUser));

            // Find or create the user in your database
            $authUser = $this->findOrCreateUser($socialiteUser);

            // Log in the user
            Auth::login($authUser, true);

            return redirect()->intended('/');
        } catch (Exception $e) {
            Log::error('Microsoft login failed: ' . $e->getMessage());
            return redirect('/')->withErrors(['login' => 'Failed to authenticate with Microsoft.']);
        }
    }
```

After going through authentication in the frontend, I am redirected to the login page and am still not logged in. The log says:
`local.ERROR: Microsoft login failed: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from `users` where (`email` = [email address]) limit 1)  `

Am I missing something in a configuration or should I be reaching out to the site hosting service?

**Comment by atymic** [comment]
That's a mysql database connection error, unrelated to socialite.

**Comment by amy1hwang** [comment]
Is the database connection even something that I need or am I going down a wrong path?
