### ISSUE TITLE
Could not find a version of package socialiteproviders/atlassian

### ISSUE THREAD

**Issue by Jelcoo** [SocialiteProviders/Providers#1249]
The [Atlassian](https://github.com/SocialiteProviders/Atlassian) package does not have a release.
<img width="851" alt="Code_z8iiYFmqaA" src="https://github.com/user-attachments/assets/d82c0d43-74e1-4069-b65a-3a8cd2667d27">
Please create a proper release so the composer command in the documentation actually works.

**Comment by atymic** [comment]
Done!
