### ISSUE TITLE
Merge of Microsoft-Graph and Microsoft-Live into new Microsoft provider

### ISSUE THREAD

**Issue by Jimbolino** [SocialiteProviders/Providers#128]
Both providers use the same urls for requesting tokens and api calls:

https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft-Graph/Provider.php#L33
https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft-Live/Provider.php#L32

The Microsoft-Azure provider uses the deprecated V1.0 api, but i do like the configurable "tenant"
https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft-Azure/Provider.php#L36

Would it be ok if I:
- Create a new provider "microsoft"
- Mark these 3 as deprecated

**Comment by faustbrian** [comment]
If Microsoft now uses one API for all those services than you can make a new provider.
