### ISSUE TITLE
How can i Avoid Laravel Socialite to Authenticate a User if i just wanna return the user details and process it ?

### ISSUE THREAD

**Issue by codeitlikemiley** [SocialiteProviders/Providers#129]
I know this is kind weid but i have an application that utilized laravel sociate and extenstion...
i never used the built in twitter and facebook, so i can change config based on user...

but the normal behaviour would be, is if im already authenticated by laravel passport...
then i tried to authenticated via facebook or twitter,
my old token is being invalidated, 

i wanna know what method that really makes this happens,
my hunch is mapUserToObject but i belive this is just mapping the credentials fetched from any service provider...

maybe the setToken ,method in Class
vendor\laravel\socialite\src\Two\User.php
vendor\laravel\socialite\src\One\User.php

I wouldnt like to messed up built in functionality 
But i would like to remove or avoid calling setToken

Can someone help me with this?
I just wanna return the userdetails and tokens after they authenticated in facebook or twitter...
but i dont want to authenticate them anymore in my app since they are authenticated already

hope someone can drop a good pointers for this thanks

**Comment by pierrocknroll** [comment]
If you closed it can you provide your solution please ?

**Comment by codeitlikemiley** [comment]
the solution is simple avoid returning a json that has a key of access_token or token....
so in my user model i added access_token as hidden field

**Comment by codeitlikemiley** [comment]
this happens when you have a statemanagement on your app or a global variable for example Laravel
that has the access_token or token , what happen is that when return directly you return the access token of Twitter for example thus, when you make subsequent api calls , you are not using anymore the access token provided by laravel passport but by Twitter for example...
