### ISSUE TITLE
Telegram Login Widget

### ISSUE THREAD

**Issue by okaufmann** [SocialiteProviders/Providers#142]
Hi,

Telegram just released a way to login via your Telegram account. https://core.telegram.org/widgets/login.

Is there anyway to at least handle the callback by a socialite provider?

I refactored the original example into an Controller with comments for better understanding whats going on: https://gist.github.com/okaufmann/28fd45d6c91107380953123c2e1e4e03

I think its neither a OAuth1 nor OAuth2 way? 

Thanks for every tip

**Comment by faustbrian** [comment]
If it's not a standardized OAuth1 or OAuth1 flow we won't support it.
