### ISSUE TITLE
Microsoft Azure doesn't allow to set the prompt option

### ISSUE THREAD

**Issue by Milad** [SocialiteProviders/Providers#148]
Hello

I'd like to ask the user to give consent every time they login. But the current [Microsoft Azure Provider](https://github.com/SocialiteProviders/Microsoft-Azure) doesn't allow the `prompt` [setting](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code).

Could you please add it? Or is it OK if I submit a pull request?

Regards

**Comment by faustbrian** [comment]
Feel free to submit a PR.

**Comment by m1guelpf** [comment]
Closing due to of lack of activity.
