### ISSUE TITLE
PHP requirement

### ISSUE THREAD

**Issue by bytestream** [SocialiteProviders/Providers#151]
All of the providers seem to have a PHP requirement of `5.6 || 7.0` registered in `composer.json`. This [commit](https://github.com/SocialiteProviders/Providers/commit/dcd7440aeecc42d0c40eef5a5a954ee84ed0a47a#diff-67cb83b11c284295c590ffaf2270858a) allowed use of the `2.0` `socialiteproviders/manager` branch which has PHP requirement of `>=5.4.0`.

Any reason for this? Happy to submit a PR that either removes the PHP requirement from each provider or change it to `>=5.4.0`

**Comment by faustbrian** [comment]
Won't support anything below PHP 5.6 because of the EOL. If you are still on 5.4 you should update asap.
