### ISSUE TITLE
Vk provider doesn't return email

### ISSUE THREAD

**Issue by pavelpage** [SocialiteProviders/Providers#154]
https://api.vk.com/method/users.get?access_token={token}&fields=uid,email,first_name,last_name,screen_name,photo&v=3.0 Such kind of request doesn't return a email value. In verison 3.0.1 everything was working except of using version as required get param.

**Comment by frutality** [comment]
I found email here: `$socialiteUser->accessTokenResponseBody['email']`. I was confused too when did not found email at `$socialiteUser>getEmail()` or `$socialiteUser->user['email']`.

**Comment by pavelpage** [comment]
@frutality And How do you use this method? Because, if I try to do it I see the error: `Call to undefined method SocialiteProviders\Manager\OAuth2\User::accessTokenResponseBody()`.  `$user = Socialite::driver($provider)->user();

        dd($user->accessTokenResponseBody('email'));`

**Comment by frutality** [comment]
It's not a method.
```
if ($socialiteUser->accessTokenResponseBody) {
  $email = $socialiteUser->accessTokenResponseBody['email'];
}
```

**Comment by aleksandrguru** [comment]
Here works catch


namespace SocialiteProviders\VKontakte;
use Illuminate\Support\Arr;
use Laravel\Socialite\Two\ProviderInterface;
use SocialiteProviders\Manager\OAuth2\AbstractProvider;
use SocialiteProviders\Manager\OAuth2\User;
class Provider extends AbstractProvider implements ProviderInterface
{
    protected $fields = ['uid', 'email', 'first_name', 'last_name', 'screen_name', 'photo'];
    /**
     * Unique Provider Identifier.
     */
    const IDENTIFIER = 'VKONTAKTE';


    /**
     * {@inheritdoc}
     */
    protected $scopes = ['email'];
    /**
     * {@inheritdoc}
     */
    const API_VERSION = '5.74';

    protected $parameters = [
         'v' => self::API_VERSION,
    ];
    /**
     * {@inheritdoc}
     */
    protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase(
            'https://oauth.vk.com/authorize', $state
        );
    }
    /**
     * {@inheritdoc}
     */
    protected function getTokenUrl()
    {
        return 'https://oauth.vk.com/access_token';
    }
    /**
     * {@inheritdoc}
     */
    protected function getUserByToken($token)
    {
        $from_token = [];

        if(is_array($token)) {
            $from_token["email"] = $token["email"];
            $token = $token["access_token"];
        }

        $lang = $this->getConfig('lang');

        $response = $this->getHttpClient()->get(
            'https://api.vk.com/method/users.get?' . http_build_query([
                "access_token" => $token,
                "fields" => implode(",", $this->fields),
                "lang" => $lang ?: "ru",
                'v' => self::API_VERSION,
            ])
        );

        $response = json_decode($response->getBody()->getContents(), true);

        if(!isset($response["response"][0])) {
            throw new \RuntimeException("Result of VK response is bad: " . sprintf($response, true));
        }

        $result = $response["response"][0];

        return array_merge($result, $from_token);

    }
    /**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user)->map([
            'id'       => Arr::get($user, 'id'),
            'nickname' => Arr::get($user, 'screen_name'),
            'name'     => trim(Arr::get($user, 'first_name').' '.Arr::get($user, 'last_name')),
            'email'    => Arr::get($user, 'email'),
            'avatar'   => Arr::get($user, 'photo'),
        ]);
    }

    protected function parseAccessToken($body) {
        return json_decode($body, true);
    }


    public function user() {
        if ($this->hasInvalidState()) {
            throw new \RuntimeException();
        }

        $user = $this->mapUserToObject($this->getUserByToken(
            $token = $this->getAccessTokenResponse($this->getCode())
        ));

        return $user->setToken(array_get($token, 'access_token'));
    }


    /**
     * {@inheritdoc}
     */
    protected function getTokenFields($code)
    {
        return array_merge(parent::getTokenFields($code), [
            'grant_type' => 'authorization_code',
        ]);
    }
    /**
     * Set the user fields to request from Vkontakte.
     *
     * @param array $fields
     *
     * @return $this
     */
    public function fields(array $fields)
    {
        $this->fields = $fields;
        return $this;
    }
    /**
     * {@inheritdoc}
     */
    public static function additionalConfigKeys()
    {
        return ['lang'];
    }
}

**Comment by AlexanderWM** [comment]
@aleksandrguru Could you make a pull request?

**Comment by m1guelpf** [comment]
Can anyone PR this?
