### ISSUE TITLE
Instagram's new Graph API

### ISSUE THREAD

**Issue by degustadev** [SocialiteProviders/Providers#170]
Is the current Instagram provider ([https://github.com/SocialiteProviders/Instagram](https://github.com/SocialiteProviders/Instagram)) compatible with new Instagram's Graph API integration?

If not, I will add a pull request for this.

Thanks

**Comment by m1guelpf** [comment]
@degustadev Feel free to PR it!

**Comment by atymic** [comment]
Released in Instagram Basic provider now :)
