### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by faustbrian** [SocialiteProviders/Providers#192]
This package is not maintained anymore due to not having the time.

We are looking for a new maintainer that wants to maintain the project and ideally it's someone who already is using the providers.

**Comment by davodsaraei** [comment]
@faustbrian 
I want to maintain this package

**Comment by nickurt** [comment]
Some update on this?

**Comment by GinoPane** [comment]
@nickurt probably they are not actively looking 😄

**Comment by claudsonm** [comment]
So, any updates here?
There are lots of volunteers here and as well on Issue #204 

PR's are waiting in line way too long. Someone needs to take better care of this amazing project.

**Comment by nickurt** [comment]
Indeed, still waiting ... ;/

**Comment by m1guelpf** [comment]
If you are still searching for people, I'm in

**Comment by faustbrian** [comment]
@m1guelpf Thanks for offering your help, glad to accept it with your contribution history to various OSS projects.
