### ISSUE TITLE
Issue with Goodreads provider

### ISSUE THREAD

**Issue by dwightwatson** [SocialiteProviders/Providers#196]
I'm running into an `InvalidArgumentException` on the callback after authenticating with the Goodreads provider - `Invalid request. Missing OAuth verifier.`. Taking a look at the code that triggers this in `SocialiteProviders\Manager\OAuth1\AbstractProvider` it looks like `hasNecessaryVerifier()` is failing.

```php
if (! $this->hasNecessaryVerifier()) {
    throw new \InvalidArgumentException('Invalid request. Missing OAuth verifier.');
}
 ```

The method it calls checks for the existence of two query string parameters in the request.

```php
protected function hasNecessaryVerifier()
{
    return $this->request->has('oauth_token') && $this->request->has('oauth_verifier');
}
```

Taking a look at [the Goodreads API documentation](https://www.goodreads.com/api/documentation) under "callbacks" it indicates that the request will be given two query string parameters - `oauth_token` and `authorize`.

I'm wondering if this is a change in Goodread's API that has broken this, or does this library not work for their flow. Not sure if their implementation fully follows the OAuth spec or not. It looks as though the Goodreads provider was added to this repo in October 2016 and you'd assume it worked then.

Is there something that I'm doing wrong?

**Comment by dwightwatson** [comment]
No - I wasn't sure if I was alone in experiencing this issue or not, but ended up removing Goodreads from our feature list.

**Comment by kajack** [comment]
I just had this issue. I guess no solution?

**Comment by dwightwatson** [comment]
Rather than close the issue I'd probably argue that the Goodreads provider be removed if it isn't working.

**Comment by atymic** [comment]
I think we should fix it, will look into this soon. PRs welcome :)

**Comment by dwightwatson** [comment]
Granted I looked into this over two years ago - but I got absolutely nowhere. The Goodreads documentation was poor, and I found other people seemed to having the same issue with their API  generally (not just with the Socialite provider) so I'm inclined to believe it's more of an issue on their end that they're not interested in resolving.

**Comment by atymic** [comment]
I'll see if we can hack around it, seems like a useful provider to have :)

**Comment by atymic** [comment]
Otherwise, I agree, we should deprecate the provider.

**Comment by dwightwatson** [comment]
Wow, good stuff! 🔥
