### ISSUE TITLE
Driver [vkontakte] not supported.

### ISSUE THREAD

**Issue by KuNman** [SocialiteProviders/Providers#197]
Hello.
I am using yours vk provider some time with Laravel 5.6. It was working. But I checked today and I get this error

> Driver [vkontakte] not supported.

 I tried 

- change socialiteproviders/vkontakte version to dev-master and 4.0

- composer dumpautoload

- php artisan config:clear

- changed \ to  \ \ in EventServiceProvider.php

> EventServiceProvider.php

```
 protected $listen = [

        "App\Events\RegisterWorker" => [

            "App\Listeners\RegisterWorkerWasFired",

        ],

	\SocialiteProviders\Manager\SocialiteWasCalled::class => [

        // add your listeners (aka providers) here

	      "SocialiteProviders\VKontakte\VKontakteExtendSocialite@handle",

	    ],

    "];

```
Any help?

**Comment by BillRiess** [comment]
I'm getting the same error with the battle.net provider. I've tried everything as well... Seeing how they are looking for a new maintainer I assume there is an issue with the package as a whole. Hopefully, someone will take over and fix it or a new package will popup.

**Comment by ngyikp** [comment]
Try https://github.com/SocialiteProviders/Manager/issues/125 ?

**Comment by m1guelpf** [comment]
@KuNman Did you manage to get this working?

**Comment by girmate** [comment]
Install provider:
