### ISSUE TITLE
Questions about contributing workflow

### ISSUE THREAD

**Issue by claudsonm** [SocialiteProviders/Providers#207]
Hi there,

I've got a PR merged, added the docs and everything, but things were not that intuitive to figure out. Maybe we need to describe things better on a CONTRIBUTING.md file?

~~Actually, my provider is not available on Packagist yet. If it is something automated, I think it should be done by now, because the [generated GitHub repo](https://github.com/SocialiteProviders/UFS) is already up and running.~~

Also, about the docs, they are not available on the interface. Maybe it will only appear after change the [SocialiteProviders/Documentation/docs/.vuepress/providers.js](https://github.com/SocialiteProviders/Documentation/blob/master/docs/.vuepress/providers.js) as well?

The PR's mentioned are #206 and [this one](https://github.com/SocialiteProviders/Documentation/pull/6).

@Edit
After a few hours the package can be found on Packagist.

**Comment by claudsonm** [comment]
Also, I noticed that the [generated repository](https://github.com/SocialiteProviders/UFS) doesn't have any versioning or releases. This is a bad thing for composer, because the package version becomes "dev-master", throwing the [message about the use of unbound versions](https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md).

I saw that the former maintainer of this package used to make some releases (manually?), but he doesn't have time anymore. How we should accomplish this?

**Comment by m1guelpf** [comment]
@claudsonm I joined as a mantainer yesterday, and I'm still getting around everything. The Packagist issue (I didn't have publish access) should be solved by now, and I'll also ask the old mantainer about the release process. Will keep this issue updated!

**Comment by m1guelpf** [comment]
I've manually tagged releases for all the providers that needed it, and also added missing providers to the website's navigation.

**Comment by bytestream** [comment]
@m1guelpf please can you tag Steam

**Comment by claudsonm** [comment]
> I've manually tagged releases for all the providers that needed it, and also added missing providers to the website's navigation.

Nice @m1guelpf .

And what about some packages not being displayed on the website (https://socialiteproviders.github.io/about.html)
There's anything missing to make it available?

Some examples are UFS and IFSP packages.

**Comment by atymic** [comment]
@claudsonm feel free to PR missing docs :)
