### ISSUE TITLE
Azure Conditional Access policy 2FA returns 'interaction_required' 400 response

### ISSUE THREAD

**Issue by PrinsFrank** [SocialiteProviders/Providers#208]
We are using the Azure driver to authenticate users. We have a conditional access policy set for users when they are not authenticating from a certain ip to require 2FA. We ran into issues when users tried to authenticate from a different ip and got an 'interaction_required' 400 response because a user was not asked for 2FA.

The problem seems to be that the 'resource'-value is not set when the initial auth-call is triggered, but is set when the access response token is requested.

Multiple fixes can be applied for this to work:
- Removing the 'resource' field from the getTokenFields and moving it to the getCodeFields. This requires the function to be overwritten in the azure Provider.
- Removing the 'resource' field from the getTokenFields and moving it to the parameters. This causes the value to be overwritten when the 'with' function is used.
- Calling the socialite driver with the resource:
`Socialite::driver($oAuthProvider)->with(['resource' => 'https://graph.windows.net'])->redirect()`. This is our current fix because it doesn't require anything to be changed in the source. I can add this to the documentation. 

Because i don't know all the ins and outs i don't know what would be the best option. What do you think about this? I can create a pull request with your preferred option.

**Comment by m1guelpf** [comment]
@PrinsFrank Would love if you could PR the third option to the documentation, as it seems something caused by explicit configuration.

**Comment by PrinsFrank** [comment]
@m1guelpf Thanks, done!
