### ISSUE TITLE
Driver [Instagram] not supported.

### ISSUE THREAD

**Issue by sajjad-talebi** [SocialiteProviders/Providers#220]
problem to laravel 5.6 and 5.7

**Comment by m1guelpf** [comment]
please provide more info

**Comment by sajjad-talebi** [comment]
i am set google plus and ok 
but instagram like google plus show message Driver [Instagram] not supported. 

Is there a perfect sample for Instagram?

**Comment by m1guelpf** [comment]
I mean, can you provide Laravel version, PHP version, example code to reproduce...?

**Comment by sajjad-talebi** [comment]
php 7.2 and laravel 5.7


config/servise.php
'github' => [
    'client_id' => env('GITHUB_CLIENT_ID'),         // Your GitHub Client ID
    'client_secret' => env('GITHUB_CLIENT_SECRET'), // Your GitHub Client Secret
    'redirect' => 'http://your-callback-url',
],


logincontroller:

 public function redirectToProvider()
    {
        return Socialite::driver('github')->redirect();
    }

    /**
     * Obtain the user information from GitHub.
     *
     * @return \Illuminate\Http\Response
     */
    public function handleProviderCallback()
    {
        $user = Socialite::driver('github')->user();

        // $user->token;
    }




route:

Route::get('login/instagram', 'Auth\LoginController@redirectToProvider');
Route::get('login/instagram/callback', 'Auth\LoginController@handleProviderCallback');



provider add:


    \SocialiteProviders\Manager\ServiceProvider::class, // add



and listen:
protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // add your listeners (aka providers) here
        'SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle',
    ],
];

**Comment by yocmen** [comment]
Any update on this? i have the same problem too on Laravel 5.8, php 7.1

**Comment by Ivcho-Varna** [comment]
> 
> 
> Any update on this? i have the same problem too on Laravel 5.8, php 7.1

I've been struggling with the same problem for the last few hours. Hope this helps you:

WORKING:

`<?php

namespace App\Providers;

use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
	        'SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle',
        ]
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }
}
`

NOT WORKING:
`<?php

namespace App\Providers;

use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;
use SocialiteProviders\Manager\SocialiteWasCalled; --> THIS IS CAUSING THE PROBLEM

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        SocialiteProviders\Manager\SocialiteWasCalled::class => [ -> YOU SHOULD USE THE FULLY CLALIFIED CLASS NAME HERE
	        'SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle',
        ]
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }
}
`

**Comment by mrstu84** [comment]
A combination of @sajjad-talebi  and @Ivcho-Varna solutions worked for me with Laravel 6.

Any call to the driver should reference "instagram" - note the lowercase "i".

`Socialite::driver('instagram')->redirect();`

And within the EventServiceProvider make sure to use the fully classified class name in the listener declaration.

`\SocialiteProviders\Manager\SocialiteWasCalled::class => [
    'SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle',
]`

**Comment by atymic** [comment]
Sounds like this is solved. If anyone is still having issues, feel free to comment and I can reopen.

**Comment by SaburovBabur** [comment]
Driver [instagram]not found issue (laravel 8)
`<?php

namespace App\Providers;

use Illuminate\Auth\Events\Registered;
use SocialiteProviders\Manager\SocialiteWasCalled;

use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;


class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        SocialiteWasCalled::class => [  ------------ // Will work if i give it via "use", but if i give fully qualified name it throws an exception
            'SocialiteProviders\\Google\\GoogleExtendSocialite@handle',
            'SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle',
            'SocialiteProviders\\Facebook\\FacebookExtendSocialite@handle',
        ],
    ];
`
