### ISSUE TITLE
Driver [Vkontakte] is outdated

### ISSUE THREAD

**Issue by si-dge** [SocialiteProviders/Providers#228]
I found two repositories of VK Driver: 
1. https://github.com/SocialiteProviders/VKontakte (updated 5 month ago).
2. https://github.com/SocialiteProviders/Providers/tree/master/src/VKontakte (updated 22 sep).

But on https://packagist.org/packages/socialiteproviders/vkontakte last version is 4.0.0 from first repository.
Merge this two versions, please. Without changes in newer rep this driver is not working.

**Comment by MKiselev** [comment]
+1

**Comment by evgeniakuzina** [comment]
I have the same problem.

**Comment by atymic** [comment]
New version was tagged with the lastest changes.
