### ISSUE TITLE
socialiteproviders/facebook can't install by composer

### ISSUE THREAD

**Issue by haruo69** [SocialiteProviders/Providers#232]
how do i install socialiteproviders/facebook by composer?

**Comment by haruo69** [comment]
I gave up using socialiteproviders/facebook. Instead, I use facebook provider of socialite and it worked fine.

**Comment by autaut03** [comment]
Could you please reopen the issue? It's still a bug, because socialiteproviders/facebook is not identical to the one that comes with socialite.

**Comment by haruo69** [comment]
I reopen this issue.

**Comment by Ramir1** [comment]
If you get messages
`[InvalidArgumentException]                                                                                                                    
  Could not find a version of package socialiteproviders/facebook matching your minimum-stability (stable). Require it with an explicit versio  
  n constraint allowing its desired stability.      `

Use 
`composer require socialiteproviders/facebook dev-master`

**Comment by tolawho** [comment]
Same. Can't install it.

**Comment by m1guelpf** [comment]
Should be fixed now
