### ISSUE TITLE
Laravel 5.7 Paypal Driver [PayPal] not supported

### ISSUE THREAD

**Issue by abkrim** [SocialiteProviders/Providers#237]
Laravel 5.7
Socialiteproviders/paypal: 3.0
SocialiteProviders/Manager 3.3
PHP 7.2.11

- Install with [manual](http://socialiteproviders.github.io/providers/pay-pal.html#_1-installation)

```
composer require socialiteproviders/paypal
```
- Not remove `Laravel\Socialite\SocialiteServiceProvider` because is Laravel 5.7. Also I need support for access with Faceboo and this work fine)
- Not add `\SocialiteProviders\Manager\ServiceProvider::class`, beacuse Laravel 5.7 autodiscover. Also try with add class.
- Add `app/Providers/EventServiceProvider` Event Listener
```php
protected $listen = [
    Registered::class => [
        SendEmailVerificationNotification::class,
    ],
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // add your listeners (aka providers) here
        'SocialiteProviders\\PayPal\\PayPalExtendSocialite@handle',
        'SocialiteProviders\\Sage\\SageExtendSocialite@handle'
    ],
];
```
- `config/services.php`
```php
'paypal' => [
        'client_id' => env('PAYPAL_KEY'),
        'client_secret' => env('PAYPAL_SECRET'),
        'redirect' => env('PAYPAL_REDIRECT_URI')
    ],
```
- Put values on my own `.env` for paypal 
- Create method `redirecToPaypalProvider` on `app/Httpd/Controllers/Auth/LoginController`
```php
public function redirectToPayPalProvider()
{
    return Socialite::with('PayPal')->redirect();
}
```
- web.php
```php
Route::get('/login/paypal', 'Auth\LoginController@redirectToPaypalProvider');
```
- login.blade.php
```
<a class="btn btn-primary" href="/login/facebook">
    Facebook Login
</a>
<a class="btn btn-primary" href="/login/paypal">
    Paypal Login
</a>
```

When try login with PayPal get error

```
InvalidArgumentException
Driver [PayPal] not supported.
```

**Comment by chancebrilz** [comment]
Have you figured out a solution to this? I am running into the same issue with another driver (Azure).

**Comment by atymic** [comment]
Are you still having issues?

**Comment by DSpeichert** [comment]
Apparently the correct driver name is `paypal` (lowercase), not `PayPal` as documentation claims.

**Comment by atymic** [comment]
Docs are fixed now 👍
