### ISSUE TITLE
Driver [Flickr] not worked correctly, service require additional query parameter

### ISSUE THREAD

**Issue by ko5ch** [SocialiteProviders/Providers#239]
> Additionally, you can pass the optional perms= parameter, asking for read, write, or delete privileges. This parameter will override the setting defined in your application's authentication flow.

It is from flickr api documentation. 

But without this parameters, flickr can't accept my auth. So i need to manually append "&perms=read" to the authorization URL for it to work. 
[screen_one](https://camo.githubusercontent.com/fb2088d15235697386278ada9c11eb95f4777936/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343330353134362f3936333430302f33623761333235652d303530322d313165332d386465382d6161616537633737323037332e706e67)
[screen_two](https://camo.githubusercontent.com/3c5f5f8c1c6705ee90958f6fe578b2fe80ecc884/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343330353134362f3936333431312f37363730666464342d303530322d313165332d393961372d3133306232373532663364372e706e67)

With the perms parameter appended to the URL:
[screen_three](https://camo.githubusercontent.com/0330b158696c4e3e90e8a022945648f17dc7f4a7/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343330353134362f3936333432312f62613130333339382d303530322d313165332d386632372d6230613131326565323162392e706e67)

Any idea how to avoid this? or can I add aditional set method for query parameters?

**Comment by m1guelpf** [comment]
@koshalex69 Maybe you could PR this to the documentation :)

**Comment by koshalex69** [comment]
> Maybe you could PR this to the documentation :)

sorry. i can't understand. problem, that without this change(in flickr/Server.php) it doesn't work, 
![image](https://user-images.githubusercontent.com/16420776/48660165-e5a21000-ea65-11e8-9e1f-9977a15f7c3e.png).

**Comment by m1guelpf** [comment]
oh right, I thought it was a configuration issue. I'm fine with updating that, but my concern is that that may block users who are currently using write actions

**Comment by koshalex69** [comment]
user can see the difference. if you talking about that :) 
![image](https://user-images.githubusercontent.com/16420776/48663863-eefb9e80-ea9e-11e8-89d7-ce3b7c635b71.png)
 
![image](https://user-images.githubusercontent.com/16420776/48663876-1eaaa680-ea9f-11e8-8c33-b32922e5aabb.png)

**Comment by m1guelpf** [comment]
@koshalex69 Could you maybe PR a way to switch perms on the URL? 😄

**Comment by ajw4sk** [comment]
@m1guelpf  I'm getting this same error - can you set scopes with this like:
return Socialite::with('flickr')->scopes($scopes)->redirect();

**Comment by philmarc** [comment]
Any update on that issue? 
I'd need the same for Etsy provider.

**Comment by atymic** [comment]
Sorry for the delay, a PR would be welcome to correct this issue :)
