### ISSUE TITLE
Steam provider needs a release

### ISSUE THREAD

**Issue by ahjorth** [SocialiteProviders/Providers#24]
It's been months and I've been using it on my old project. But now for 5.4 it's in dire need of an update and a proper release so we don't have to change `minimum-stability`

**Comment by faustbrian** [comment]
This should work for now and won't change anything since stable releases will be pulled in for all other packages.

```
"minimum-stability": "dev",
"prefer-stable": true
```

I have to take care of my job and all SocialiteProvider repositories alone so things might take time.

**Comment by ahjorth** [comment]
SocialiteProviders/Steam requires `SocialiteProviders/Manager@2.0` which requires `Laravel/Socialite@2.0`

5.4 requires `Laravel Socialite@3.0`. So currently it will work for 5.3 but not for 5.4 using the method above.
