### ISSUE TITLE
Google+ (including Sign-in) shutting down 

### ISSUE THREAD

**Issue by CSNWEB** [SocialiteProviders/Providers#246]
Sign ins with google will slowly start failing beginning with the 28th of January. Google published a migration guide to the Google Login here: https://developers.google.com/identity/sign-in/web/quick-migration-guide. Are there any plans to integrate this soon?

**Comment by m1guelpf** [comment]
PRs welcome

**Comment by CSNWEB** [comment]
#266

**Comment by atymic** [comment]
Closed in #266
