### ISSUE TITLE
[Orcid] driver seems to be broken

### ISSUE THREAD

**Issue by antonkomarev** [SocialiteProviders/Providers#257]
I found `dd($data);` in it's code. Need to assure.

**Comment by m1guelpf** [comment]
Can you PR this?

**Comment by antonkomarev** [comment]
Sorry, I don't have enough time to test it. I don't know if it's working. We need somebody to create Orcid application and try to integrate with it, to proof that's all is OK.

**Comment by asntech** [comment]
I need Orcid for an academic App I'm developing. @m1guelpf I'll look into this and do a PR.

**Comment by pxgamer** [comment]
Looks like this can be closed by #263 if it's been tested?

**Comment by m1guelpf** [comment]
Closing this, let me know if this is still an issue
