### ISSUE TITLE
LinkedIn API v1 deprecation March 1st

### ISSUE THREAD

**Issue by dextermb** [SocialiteProviders/Providers#272]
LinkedIn are going to [drop support](https://engineering.linkedin.com/blog/2018/12/developer-program-updates) for `v1` of their API come March 1st 2019 (next month). Currently the LinkedIn provider uses `v1`.

Are there plans to update to [`v2`](https://docs.microsoft.com/en-us/linkedin/) before this happens?

**Comment by m1guelpf** [comment]
Would love to get a PR for this :)

**Comment by throttlehead** [comment]
Hey guys, I've got a fix mostly done for this. Should I fork this repo or the readonly one specific for the provider?

**Comment by m1guelpf** [comment]
Please PR to this repo.

**Comment by pxgamer** [comment]
It looks like this can be closed since #283 was merged. 👍
