### ISSUE TITLE
Discord Intergration 401 when using ENV values

### ISSUE THREAD

**Issue by JTD420** [SocialiteProviders/Providers#275]
I am trying to add discord integration to my site however unless I manually set the config options I get a 401 unauthorised error!

(More Info)
`  $config = new \SocialiteProviders\Manager\Config($clientId, $clientSecret, $redirectUrl, $additionalProviderConfig);`
If I do the above and then use the `->setConfig($config)` before redirect my code works and it returns the users info, token etc.

However trying it normally and expecting it to go through the environment set variables doesn't seem to work at-all.

The ENV file is clearly readable because if I change other variables like app name etc it updates on the website.

I've tried uppercase, lowercase and more with ENV but here is a copy of the current config I had in there I was trying (sensitive info redacted)

```
CLIENT_ID = "###"    
CLIENT_SECRET = "###"   
REDIRECT_URI = "http://###.co/dev/public/provider/discord/callback"
```

**Comment by sofwar** [comment]
Hi, did you enter data into the config/services.php file?

`
 'discord' => [
        'client_id' => env('DISCORD_KEY'),
        'client_secret' => env('DISCORD_SECRET'),
        'redirect' => env('DISCORD_REDIRECT_URI')
 ],
`

**Comment by JTD420** [comment]
> Hi, did you enter data into the config/services.php file?
> 
> ` 'discord' => [`
> ` 'client_id' => env('DISCORD_KEY'),`
> `'client_secret' => env('DISCORD_SECRET'),`
> ` 'redirect' => env('DISCORD_REDIRECT_URI')`
> ` ]`

Hi, yes I have them entered in the config/services.php file also

```
'discord' => [
    'client_id' => env('###'),
    'client_secret' => env('###'),
    'redirect' => env('http://###.co/dev/public/provider/discord/callback'),
],
```

**Comment by sofwar** [comment]
Looks like you're not using env correctly. Try entering data directly without it.

` 'discord' => [`
       ` 'client_id' => '539403797894*****',
        `'client_secret' => '*****-AxZVENQRSRM5MMYdCPfb****',
       ` 'redirect' => 'http://###.co/dev/public/provider/discord/callback'
` ]`

**Comment by JTD420** [comment]
> Looks like you're not using env correctly. Try entering data directly without it.
> 
> ` 'discord' => [`
> ` 'client_id' => '539403797894*****',`
> `'client_secret' => '*****-AxZVENQRSRM5MMYdCPfb****',`
> ` 'redirect' => 'http://###.co/dev/public/provider/discord/callback'`
> ` ]`
> 
> https://laravel.com/docs/5.7/configuration#retrieving-environment-configuration

This fixed my problem, thank you!


Would this constitute a bug/mistake on the documentation then?

Straight from the official sites documentation : 

> Add to config/services.php. 
```
'discord' => [
    'client_id' => env('DISCORD_KEY'),
    'client_secret' => env('DISCORD_SECRET'),
    'redirect' => env('DISCORD_REDIRECT_URI')
],

```
Link: https://socialiteproviders.netlify.com/providers/discord.html#_4-configuration-setup

**Comment by sofwar** [comment]
This is not an error in env spelled constant from an .env file. Read the documentation.

https://laravel.com/docs/5.7/configuration#retrieving-environment-configuration

**Comment by JTD420** [comment]
> This is not an error in env spelled constant from an .env file. Read the documentation.
> 
> https://laravel.com/docs/5.7/configuration#retrieving-environment-configuration

But I had it in my .env file aswell and it wasn't working?
