### ISSUE TITLE
Discord "invalid state exception"

### ISSUE THREAD

**Issue by JTD420** [SocialiteProviders/Providers#276]
So I'm getting 

> "Laravel \ Socialite \ Two \ InvalidStateException
> No message"
error whenever I try and authenticate with discord... It can redirect to provider fine but its when it gets to the callback that I get the errors...

The command
    `$getInfo = Socialite::driver('discord')->user();`
is what is throwing the error I believe but I'm not exactly sure why or what I'm doing wrong....

I am able to get the users info by doing `$discord_model_id = $user->getId();` as an example but this is not what the documentation suggests for routing/authenticating.

In fact, in the documentation it includes `//$user->token;` but it's commented out so I am not sure if its supposed to be used in that way or not.

Why is `$getInfo` not working and how am I supposed to use the command if not in that way?

What is the correct way to handle things from the callback?

**Comment by JTD420** [comment]
I have got the following DB schema 
`        Schema::create('social_accounts', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
      	    $table->string('provider_user_id');        //Store the provider's user id.
      	    $table->enum('provider', ['discord', 'facebook', 'twitter', 'linkedin', 'github']); //Store the provider.
      	    $table->timestamps();
      	    $table->foreign('user_id')->references('id')->on('users');`

From the callback I just need to check if the user already exists by seeing if their discord id is in the DB and if so logging in the user it matches up with (user_id) otherwise it should register the user or allow for the user to register....

Do I skip the driver('discord')->user(); part and just go straight to using $user->getID and put the value of that into provider_user_id etc etc?

**Comment by sofwar** [comment]
try using **stateless**

`$getInfo = Socialite::driver('discord')->stateless()->user()`

**Comment by JTD420** [comment]
> try using **stateless**
> 
> `$getInfo = Socialite::driver('discord')->stateless()->user()`

Thanks, I managed to get it to work afaict with this instead:

 ```
    $user = Socialite::driver('discord')
     ->with(['Content-Type' => 'application/x-www-form-urlencoded'])
     ->user();
```

**Comment by JTD420** [comment]
I believe discord requires you to include a header which wasn't being included... That seemed to fix it

**Comment by JTD420** [comment]
I've got a new problem of having moved my project to a new webserver and now whenever I try logging in I get 419 Session Expired / Page Expired...

Is there a specific way you're supposed to move servers?
