### ISSUE TITLE
Driver['Discord'] not supported

### ISSUE THREAD

**Issue by peter-ec** [SocialiteProviders/Providers#280]
### Having problem implementing discord as a provider. 
I keep getting this issue of:

Driver['Discord'] not supported, and 
Driver['discord'] not supported, when I try calling it using 'discord' in my controller that handles the routes.

### **Composer.json**

```
   "require": { 
       "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "google/apiclient": "~2.0",
        "laravel/framework": "5.6.*",
        "laravel/socialite": "^3.2.0",
        "laravel/tinker": "^1.0",
        "socialiteproviders/battlenet": "^2.0",
        "socialiteproviders/discord": "^2.0.2",
        "socialiteproviders/twitch": "^5.0",
        "socialiteproviders/youtube": "^3.0"
    },
```

### **config/services.php**
In discords redirect uri I have this down as my redirect uri. (I have tried having the uri be .../oauth/discord/callback and that didn't work either)

```
    'discord' => [
        'client_id' => env('DISCORD_KEY'),
        'client_secret' => env('DISCORD_SECRET'),
        'redirect' => env('DISCORD_REDIRECT_URI', 'https://xxxxxx.com/oauth/Discord/callback')
    ],
```
### **config/app.php**

```
    'providers' => [
    //other providers 
    \SocialiteProviders\Manager\ServiceProvider::class,

   ],
```
###  **App/Providers/EventServiceProvider.php** 
```
    protected $listen = [
       // other events to listen to  

        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            // add your listeners (aka providers) here
            'SocialiteProviders\\YouTube\\YouTubeExtendSocialite@handle',
            'SocialiteProviders\\Battlenet\\BattlenetExtendSocialite@handle',
            'SocialiteProviders\\Discord\\DiscordExtendSocialite@handle',
            'SocialiteProviders\\Twitch\\TwitchExtendSocialite@handle',
        ],
    ];
```
### **App/Http/Controllers/OAuth/OAuthController.php** 

```
namespace App\Http\Controllers\OAuth;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Support\Facades\Auth;

use Socialite;

class OAuthController extends Controller 
{
    use AuthenticatesUsers;
    /**
     * Redirect the user to the providers authentication page.
     *
     * @return \Illuminate\Http\Response
     *  
     * Socialite::driver($social)->scopes(['parm1', 'parm2'])->redirect();
     *  If scopes need to be added make sure to add logic for each provider so that 
     *  the scopes match the respective provider 
     *  
     */
    public function redirectToProvider($social)
    {
        if($social == 'battlenet'){
          return Socialite::driver($social)->scopes(['wow.profile','sc2.profile'])->redirect();
        }else if($social == 'discord'){
          return Socialite::with('Discord')->redirect();
        }else{
          return Socialite::driver($social)->redirect();
        }
    }
```

### **Routes.php**
```
Route::get('/oauth/{social}', array(
    'as'   => 'oauth.social',
    'uses' => 'OAuth\OAuthController@redirectToProvider'
));

Route::get('oauth/{social}/callback', array(
    'uses' => 'OAuth\OAuthController@handleProviderCallback'
));

```

### **connections.blade.php** 
Passes discord from view to route.

`        <a href="{{URL::route('oauth.social', 'discord')}}" class='oauth-button'>Discord</a> `

**Comment by peter-ec** [comment]
I have tried passing through 'Discord' and 'discord'. When passing in these different values I make sure to change anything that may be affected by it such as the redirect URI of the provider, and the redirectToProvider to handle in the different passed in result.

**Comment by StephanWithPH** [comment]
I have this same problem too,

My social login file:
`class SocialLogin extends Controller
{

    public function redirect($service)
    {
        return Socialite::driver($service)->redirect();
    }

    public function callback($service)
    {
        if ($service === "discord"){
            dd(Socialite::driver('discord')->user());
        }
        else {
            $user = Socialite::driver($service)->user();
            $existingUser = User::whereEmail($user->getEmail())->first();
            if ($existingUser){
                Auth::login($existingUser);
                return redirect()->action('HomeController@loadHomePage');
            }
            User::create([
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'password' => bcrypt('jkdsfj$kf%ds!334kfjds'),
            ]);
            $existingUser = User::whereEmail($user->getEmail())->first();
            Auth::login($existingUser);

            return redirect()->action('HomeController@loadHomePage');
        }

    }
}`

My services.php
`    'discord' => [
        'client_id' => env('DISCORD_KEY'),
        'client_secret' => env('DISCORD_SECRET'),
        'redirect' => env('DISCORD_REDIRECT_URI'),
    ],`

My app.php providers array
`'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,


        /*
         * Added for Discord authentication
         */
        \SocialiteProviders\Manager\ServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

    ],`

My EventServiceProvider
` /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            \SocialiteProviders\Manager\SocialiteWasCalled::class => [
                // add your listeners (aka providers) here
                'SocialiteProviders\\Discord\\DiscordExtendSocialite@handle',
            ],
        ],
    ];`

**Comment by atymic** [comment]
It's definitely lower case `discord`.

I'm going to close this now. If you're still having issues please ping me :)
