### ISSUE TITLE
Google provider conflict

### ISSUE THREAD

**Issue by jshayes** [SocialiteProviders/Providers#281]
It seems like there is a package naming conflict between the two Google providers.
There is the [Google-Plus provider](https://github.com/SocialiteProviders/Providers/blob/master/src/Google-Plus) that has existed for a while. In the `composer.json` file the name is set to `socialiteproviders/google`.

There is also a new [Google provider](https://github.com/SocialiteProviders/Providers/tree/master/src/Google) that was introduced in #266. The name in the `composer.json` file for this provider is also `socialiteproviders/google`.

Additionally, on the `socialiteproviders/google` [package on packagist](https://packagist.org/packages/socialiteproviders/google) is for the Google-Plus provider. So it doesn't seem like there is a way to install the new provider at this point.

**Comment by sofwar** [comment]
> Google+ APIs will be shut down on March 7, 2019. This includes Google+ Sign-in and OAuth token requests with Google+ scopes. Learn more.
Google+ integrations for web and mobile apps will also cease to function March 7, 2019. Learn more.
This will be a progressive shutdown, with intermittent failures starting as early as January 28, 2019.

Maybe you should just delete Google-Plus, given that Google completely copies its properties and should replace it.

**Comment by sinkcup** [comment]
yes, it's a bug.

https://packagist.org/packages/socialiteproviders/google

is linked to

https://github.com/SocialiteProviders/Google-Plus

it should be

https://github.com/SocialiteProviders/Google

**Comment by sinkcup** [comment]
@m1guelpf need run `build/split.sh`, then check https://packagist.org/packages/socialiteproviders/google

**Comment by sinkcup** [comment]
@m1guelpf maybe should delete the package:

https://packagist.org/packages/socialiteproviders/google

then create it using:

https://github.com/SocialiteProviders/Google

**Comment by jshayes** [comment]
Or maybe just create a new version, there are still people using this package. It's had over 11, 000 installs over the last 30 days. So, this should probably be done in a way that doesn't cause any issues for them.

**Comment by m1guelpf** [comment]
Yeah, is there a way to do this without breaking BC for the people still running the older version?

**Comment by Paulsky** [comment]
How to find and use the correct (new) one? The old one is not working anymore (error on the endpoint). This project is really a maze. A lot of providers in the documentation are removed/not working/deprecated and working providers are not documented and hidden. Is this the correct one: https://github.com/jihwan-baek/Google-Plus/(socialiteproviders-comento/google)? Why is it called Google PLUS while it's really not PLUS?
