### ISSUE TITLE
[Steam] Driver stops working in SocialiteProviders/Manager 3.3.5

### ISSUE THREAD

**Issue by andy3471** [SocialiteProviders/Providers#299]
## PHP 7.3

My steam integration has been working for my site. I have no run composer update, which has update my socialiteproviders/manager package to 3.3.5, which now throws an error (screenshot attached).

Restoring to the previous version, deleting the vendor folder, and running composer install again has fixed the issue for me.

## Controller Redirect  
`
    public function steamRedirect()
    {
        return Socialite::driver('steam')->redirect();
    }
`

## Controller Callback  

`
    public function steamCallback()
    {
        $steamuser = Socialite::driver('steam')->user();

        $KeyshareUser = LinkedAccount::where('account_id', '=', $steamuser->id)->get();

        if (count($KeyshareUser) == 0) {
            //If Doesn't Exist, Create User
            $KeyshareUser = new User;
            $KeyshareUser->name = $steamuser->nickname;
            $KeyshareUser->image = $steamuser->avatar;
            $KeyshareUser->email = uniqid();
            $KeyshareUser->password = uniqid();
            $KeyshareUser->save();

            $LinkedAccount = new LinkedAccount;
            $LinkedAccount->user_id = $KeyshareUser->id;
            $LinkedAccount->linked_account_provider_id = '1';
            $LinkedAccount->account_id = $steamuser->id;
            $LinkedAccount->save();

        } elseif (count($KeyshareUser) == 1) {

            //If Exists, Find and Update User
            $KeyshareUser = User::find($KeyshareUser[0]->user_id);
            $KeyshareUser->name = $steamuser->nickname;
            $KeyshareUser->image = $steamuser->avatar;
            $KeyshareUser->save();

        } else {
            return 'Error';
        }

        Auth::login($KeyshareUser);
        return redirect('/games');
    }
`  

## Steps to Replicate:
Press steam sign in button -> redirected to steam website -> on redirect to site, attached error appears

**Comment by sinkcup** [comment]
try 3.3.6.
maybe same as https://github.com/SocialiteProviders/Manager/issues/143

**Comment by andy3471** [comment]
@sinkcup That's done it - all fixed. Thank you very much!
