### ISSUE TITLE
split.sh seems not run

### ISSUE THREAD

**Issue by sinkcup** [SocialiteProviders/Providers#304]
new provider had been added to `build/split.sh` by PR https://github.com/SocialiteProviders/Providers/pull/302

but new repo have not been auto created. 404: https://github.com/SocialiteProviders/WeChatServiceAccount

**Comment by sinkcup** [comment]
need your help. @m1guelpf

**Comment by sinkcup** [comment]
the repo is ok, then need to "submit repo as a package" on packagist.org @m1guelpf
now packages 404:
https://packagist.org/packages/socialiteproviders/wechat-web
https://packagist.org/packages/socialiteproviders/wechat-service-account

**Comment by sinkcup** [comment]
Do you have time? Help tag and submit new repo to https://packagist.org/
submit
https://github.com/SocialiteProviders/WeChatServiceAccount
to
https://packagist.org/packages/socialiteproviders/wechat-service-account

and submit
https://github.com/SocialiteProviders/WeChatWeb
to
https://packagist.org/packages/socialiteproviders/wechat-web

@m1guelpf @LasseRafn

**Comment by LasseRafn** [comment]
Hi, I don't seem to have access to these

**Comment by sinkcup** [comment]
we need you. @m1guelpf

**Comment by sinkcup** [comment]
how are you? @m1guelpf

**Comment by sinkcup** [comment]
happy weekend, waiting your submit. @m1guelpf

**Comment by sinkcup** [comment]
maybe it's a good idea to set me as a owner of these tow repos:
https://github.com/SocialiteProviders/WeChatServiceAccount
https://github.com/SocialiteProviders/WeChatWeb

so I can create tag and submit packagist. @m1guelpf

**Comment by sinkcup** [comment]
Hello, is there someone? @m1guelpf

**Comment by sinkcup** [comment]
hello? @m1guelpf

**Comment by sinkcup** [comment]
are you there? @m1guelpf

**Comment by m1guelpf** [comment]
Hey! I'm really sorry about this. I've tagged and added the two repos to packagist.

**Comment by sinkcup** [comment]
@m1guelpf, I had wait one month, it's too late, so I create a new org and repo: [socialite providers](https://github.com/laravel-socialite-providers), it can split and release tag automatically by CI.

https://github.com/laravel-socialite-providers/socialite-providers/blob/master/.circleci/config.yml

**Comment by m1guelpf** [comment]
@sinkcup I'd love it if you could PR a version of that script to this org to keep everything updated ❤️

**Comment by sinkcup** [comment]
at first, I want to make a PR, but then I found this org and repo having some problem and some can not be fixed:

1. github org URI and composer org URI don't follow slug style standard, it's difficult to read, you can see warnings in IDE or Chrome input box. the better URI is "github.com/socialite-providers" or https://github.com/laravel-socialite-providers

![image](https://user-images.githubusercontent.com/4971414/61518645-a97fde80-aa3c-11e9-8f45-b95848fe19b3.png)

2. repo and composer names are not semantic, it's unfriendly to fork. "socialite-providers/providers" is a bad name, the better one is "socialite-providers/socialite-providers"; "socialite-providers/stripe" is a bad name, the better one is "socialite-providers/socialite-stripe". see https://github.com/laravel-socialite-providers/socialite-providers/issues/9

3. [Documents](https://github.com/SocialiteProviders/Documentation) are not in code, it's difficult to make PR. If I want to add one provider, but I need to fork two repo... so I use `readme.md` in codes as docs. see https://github.com/laravel-socialite-providers/socialite-providers/tree/master/WeChatWeb

@LasseRafn Do you have any advice?

**Comment by m1guelpf** [comment]
@sinkcup I see how other names would be better but I'm afraid this organization has been around for too long to just change this. Also, renaming packages would be a breaking change. I'm fine with managing the docs myself (as that's done by Netlify) and maintaining a reference that joins paths and repos (maybe a JSON version of the split.sh file? My issue is with having to re-run manually the split script in my computer every time a new commit is merged, as it can take me quite some time.

**Comment by sinkcup** [comment]
@m1guelpf, you are right, we can't change a wildly used package's name.

I have a suggestion: keep this org and repo only for reading, we use "github.com/socialite-providers" or https://github.com/laravel-socialite-providers as a new begin, and format providers and docs to the new repo.

split and tag can be automatical, but packagist.org doesn't support submit a package by API, so we need to submit when each new package merged, it will take a little time. we can all be admin, It's really difficult for a person to handle it in time.

**Comment by m1guelpf** [comment]
Hmmm, I'd like to preserve stats if possible. Let me contact packagiat support to ask if there's a better way of managing this.
