### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by edbizarro** [SocialiteProviders/Providers#307]
https://socialiteproviders.netlify.com is down

![Page Not Found](https://user-images.githubusercontent.com/84926/56975051-65b8bf80-6b46-11e9-92f2-24d0e6ef67c4.png)

**Comment by m1guelpf** [comment]
Would appreciate a PR to the documentation site

**Comment by sinkcup** [comment]
PR https://github.com/SocialiteProviders/Documentation/pull/48

duplicate of https://github.com/SocialiteProviders/Documentation/issues/47

**Comment by m1guelpf** [comment]
Fixed
