### ISSUE TITLE
SocialiteProviders for MercadoLibre (Latinamerica Ebay) display error.

### ISSUE THREAD

**Issue by price2b** [SocialiteProviders/Providers#308]
Dear all,

I took Dropbox socialiteprovider and tried to copy/customize in order to create a provider for MercadoLibre (Latinamerica Ebay) - https://developers.mercadolibre.com.ar -. For some reason is not working, my current error msg is  **"throw new InvalidStateException();"** in OAuth2/AbstractProvider.php.

This is the code I created:
composer.json:

```
{
    "name": "price2b/mercadolibre",
    "description": "Mercadolibre Laravel Socialite Integration",
    "keywords": ["Laravel","Socialite","Mercadolibre"],
    "license": "MIT",
    "authors": [
        {
            "name": "Sebastian Herrera",
            "email": "....@....com"
        }
    ],
    "minimum-stability": "stable",
    "require": {      
        "laravel/socialite": "3.*",
        "illuminate/support": "5.*"
    },
    "autoload" : {
        "psr-4": {
            "Price2b\\Mercadolibre\\": "src/"
        }
    }
}

```
then I created a folder with name  src (in src folder) and place the following code:

MercadolibreExtendSocialite.php  (in src folder):

```
<?php
namespace Price2b\Mercadolibre;
use SocialiteProviders\Manager\SocialiteWasCalled;
class MercadolibreExtendSocialite
{
    /**
     * Register the provider.
     *
     * @param \SocialiteProviders\Manager\SocialiteWasCalled $socialiteWasCalled
     */
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        $socialiteWasCalled->extendSocialite(
            'mercadolibre', __NAMESPACE__.'\Provider'
        );
    }
}
```

Provider.php  (in src folder):

```
<?php
namespace Price2b\Mercadolibre;
use Illuminate\Support\Arr;
use SocialiteProviders\Manager\OAuth2\AbstractProvider;
use SocialiteProviders\Manager\OAuth2\User;
class Provider extends AbstractProvider
{
    /**
     * Unique Provider Identifier.
     */
    const IDENTIFIER = 'MERCADOLIBRE';
    /**
     * {@inheritdoc}
     */
    protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase(
            'http://auth.mercadolibre.com/authorization', $state
        );
    }
    /**
     * {@inheritdoc}
     */
    protected function getTokenUrl()
    {
        return 'https://api.mercadolibre.com/oauth/token';
    }
    /**
     * {@inheritdoc}
     */
    protected function getUserByToken($token)
    {
        $response = $this->getHttpClient()->get('https://api.mercadolibre.com/users/me?'.http_build_query(['access_token'=>$token]));
        return json_decode($response->getBody()->getContents(), true);
    }
    /**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user)->map([
            'id'                => $user['id'],
            'nickname'          => $user['nickname'],
            'name'              => trim($user['first_name'].' '.$user['last_name']),
            'email'             => (isset($user['email']))? $user['email'] : \Auth::user()->email,
        ]);
    }
    /**
     * {@inheritdoc}
     */
    protected function getTokenFields($code)
    {
        return array_merge(parent::getTokenFields($code), [
            'grant_type' => 'authorization_code',
        ]);
    }
}

```
composer.json (in src folder)

```
{
    "name": "price2b/mercadolibre",
    "description": "Mercadolibre OAuth2 Provider for Laravel Socialite",
    "license": "MIT",
    "authors": [{
        "name": "Sebastian Herrera",
        "email": "...@...com"
    }],
    "require": {
        "php": "^5.6 || ^7.0",
        "socialiteproviders/manager": "~2.0 || ~3.0"
    },
    "autoload": {
        "psr-4": {
            "Price2b\\Mercadolibre\\": ""
        }
    }
}
```
I took some parameters information from another implementation from the following repository: https://github.com/Kolovious/MeliSocialite/blob/master/src/MeliSocialite.php 
any help appreciated!.

**Comment by m1guelpf** [comment]
@price2b Why did you close this issue? Did you find a solution to your problem?

**Comment by price2b** [comment]
Hi @m1guelpf , I didnt find a solution.. usually when I find a solution I share it (the solution or the package). Honestly I was in doubt if it was off topic consequently I choose to close it. I will reopen it.

**Comment by sofwar** [comment]
Did you try to put another namespace?

```namespace Price2b\Mercadolibre;```
on
```namespace SocialiteProviders\Mercadolibre;```

**Comment by price2b** [comment]
hi @sofwar , I will try that change and let you know..

**Comment by price2b** [comment]
Hi @sofwar @m1guelpf , I created a new package https://github.com/price2b/melisocialite and published at packagist so it can be installed using composer. the current error I received is

> Driver [MeliSocialite] not supported.
![Captura de pantalla 2019-06-01 a las 2 33 15 p m](https://user-images.githubusercontent.com/396666/58751814-4fba5980-847a-11e9-84ca-06946062abf4.png)

@sofwar regarding the namespace: SocialiteProviders\ is an already registered namespace at packagist, consequently it cannot be used unless you receive approval. Thats the reason why I need to use another namespace.

Additional info, I tried to declare eventservice provider with doble \\ and single \.

protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // add your listeners (aka providers) here
        'Price2b\\MeliSocialite\\MeliExtendSocialite@handle',
    ],
];

Im stuck on this area because Im new (trying) developing for socialiteproviders. If you can check the code will be appreciated.
github: https://github.com/price2b/melisocialite
packagist: https://packagist.org/packages/price2b/melisocialite

**Comment by m1guelpf** [comment]
Hey @price2b!

Sorry for the late response, I've been really busy with school and haven't had time to run the split script.

Will try to get this done today and push to packagist, sorry for the inconveniences!

**Comment by price2b** [comment]
> Hey @price2b!
> 
> Sorry for the late response, I've been really busy with school and haven't had time to run the split script.
> 
> Will try to get this done today and push to packagist, sorry for the inconveniences!

Im facing problems with InvalidStateException when I try to invoke:

$user = Socialite::driver('melisocialite')->user();
$accessTokenResponseBody = $user>accessTokenResponse

the error comes from: price2b/melisocialite/Provider.php InvalidStateException.. in function

```
public function user()
{
if ($this->hasInvalidState()) {
throw new InvalidStateException;
}
```

Im trying to see why Im receiving the error

**Comment by price2b** [comment]
"Will try to get this done today and push to packagist, sorry for the inconveniences!"

thank you!
