### ISSUE TITLE
Call to undefined method setTenantId() in Microsoft-Graph Provider

### ISSUE THREAD

**Issue by apmyp1990** [SocialiteProviders/Providers#314]
Hi guys,
I have installed the SocialiteProviders/Microsoft-Graph provider and the laravel/socialite package in my laravel project via composer. As provided in the documentation of socialiteproviders (https://socialiteproviders.netlify.com/providers/microsoft-graph.html) I want to set an explicit tenant id by using `setTenantId('my-secret-tenant-id')` because I do not want to implement a multi-tenant application. When running my app I get following error: 

    Call to undefined method SocialiteProviders\Graph\Provider::setTenantId()

I searched for this method in the vendor package and did not find it - but it is in the Provider class which you can find here on github.

Am I doing something wrong? How can I solve this error?

Thanks in advance!

**Comment by Jimbolino** [comment]
I think you have to use the dev-master in your composer.json,
because the latest "stable" is from 2017, and doesnt have the function.
 
https://github.com/SocialiteProviders/Microsoft-Graph/releases

**Comment by wells** [comment]
Somebody needs to tag that release... dev-master for now...

**Comment by apmyp1990** [comment]
> I think you have to use the dev-master in your composer.json,
> because the latest "stable" is from 2017, and doesnt have the function.
> 
> https://github.com/SocialiteProviders/Microsoft-Graph/releases

That solved my issue, thanks!
