### ISSUE TITLE
Add provider for "Sign In with Apple"

### ISSUE THREAD

**Issue by LukeStanbery89** [SocialiteProviders/Providers#316]
Please create a Socialite provider for [Sign In with Apple](https://developer.apple.com/sign-in-with-apple/).

Sorry if this is not the right place to submit this request. Please let me know if there is a better place.

**Comment by LukeStanbery89** [comment]
I see that there is already a [pull request](https://github.com/SocialiteProviders/Providers/pull/315) for this, so I am closing this issue.

**Comment by Ahilmurugesan** [comment]
Hi,
We added a new pull request, awaiting approval. The previous pull request did not get approved. Hopefully, this one gets approved.

https://github.com/SocialiteProviders/Providers/pull/405
