### ISSUE TITLE
Zendesk is Missing Subdomain

### ISSUE THREAD

**Issue by MCKLtech** [SocialiteProviders/Providers#320]
In the docs for Zendesk:

https://socialiteproviders.netlify.com/providers/zendesk.html

The config should include the subdomain:

```
'zendesk' => [
    'client_id' => env('ZENDESK_KEY'),
    'client_secret' => env('ZENDESK_SECRET'),
    'redirect' => env('ZENDESK_REDIRECT_URI'),
    'subdomain' => env('ZENDESK_SUBDOMAIN')
],
```
Failure to include the subdomain will result in OAuth failure as getSubdomain() in the Provider.php will return an empty string.

**Comment by m1guelpf** [comment]
Feel free to open a PR on the docs repo or in here for added validation

**Comment by sathishkannangit4** [comment]
\||

**Comment by sathishkannangit4** [comment]
i dont know bro
