### ISSUE TITLE
composer requires old version of linkedin provider

### ISSUE THREAD

**Issue by samarqhand** [SocialiteProviders/Providers#324]
I'm running php 7.3.x on windows with composer 1.8.6. 

doing `composer require socialiteproviders/linkedin` seems to work just fine, and so does the login on linkedin.com but I get the error

`Client error: `GET https://api.linkedin.com/v1/people/~:(id,formatted-name,picture-url,email-address,public-profile-url)`resulted in a `410 Gone` This resource is no longer available under v1

When the login redirects me to my server. 

comparing the code in my vendor folder with that on https://github.com/SocialiteProviders/LinkedIn I can see I have got an old version that does indeed reference v1, in vendor/socialiteproviders/linkedin/Provider.php line 97

    /**
     * {@inheritdoc}
     */
    protected function getUserByToken($token)
    {
        $response = $this->getHttpClient()->get(
            'https://api.linkedin.com/v1/people/~:(id,formatted-name,picture-url,email-address,public-profile-url)', [
            'headers' => [
                'Accept-Language' => 'en-US',
                'x-li-format' => 'json',
                'Authorization' => 'Bearer '.$token,
            ],
        ]);

        return json_decode($response->getBody()->getContents(), true);
    }

What is going wrong for me to get the older version? I have tried removing the package `composer self-update` and `composer clear-cache` and requiring again. adding a repositories element doesn't seem to help either.

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/SocialiteProviders/LinkedIn"
        }
    ],

Looks like the https://packagist.org/packages/socialiteproviders/linkedin hasn't been updated since 2017, is that the issue?

Any ideas? Thanks :)

**Comment by emotality** [comment]
Yes, this provider is outdated and still calling v1 endpoint.

More about the new endpoint: 
https://docs.microsoft.com/en-gb/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin

Might consider doing a PR but this place seems dead. So rather fork and fix?

**Comment by m1guelpf** [comment]
Tagged a new release that includes the commits that were already in the repo. Feel free to PR the new endpoint

**Comment by m1guelpf** [comment]
Actually I'll leave this open to track the new endpoint change 😄
