### ISSUE TITLE
Is there a reason you're not releasing a new tag of Naver?

### ISSUE THREAD

**Issue by cherryred5959** [SocialiteProviders/Providers#334]
https://github.com/SocialiteProviders/Naver/tree/v3.1.0
Is there a reason why you haven't released a new tag since that 3.1?

https://github.com/SocialiteProviders/Naver/commit/58e298d9ca9f728866ecf25e9e39d7386bcb3002#diff-b5c55cdefc46e252adb39d5bbf0aceb8
I need the contents of that commit.

The commit was merged as many as eight months ago, And yet why?

**Comment by m1guelpf** [comment]
Just tagged

**Comment by cherryred5959** [comment]
Right, I just checked the new tag, thank you!!
