### ISSUE TITLE
WeChat Driver is a stripped down version of the weixin Driver

### ISSUE THREAD

**Issue by apollopy** [SocialiteProviders/Providers#338]
Weixin is WeChat, just in a different language. The Weixin driver is much more complete. In order to avoid confusion, I suggest deleting the WeChat driver.

The same
```
https://github.com/SocialiteProviders/Providers/tree/master/src/Weixin
https://github.com/SocialiteProviders/Providers/tree/master/src/WeChatServiceAccount
```

and The same
```
https://github.com/SocialiteProviders/Providers/tree/master/src/Weixin-Web
https://github.com/SocialiteProviders/Providers/tree/master/src/WeChatWeb
```

**Comment by m1guelpf** [comment]
Is there a way to do this without breaking the apps of people who already rely on the WeChatWeb driver?

**Comment by sinkcup** [comment]
@apollopy WeChatServiceAccount is more semantic than weixin, and no warning in IDE.

I suggest: copy features which you need to WeChatServiceAccount and WeChatWeb.

**Comment by larvacent** [comment]
WeChatServiceAccount and WeChatWeb Written parameters, can not be customized, I will not use.
