### ISSUE TITLE
Composer Doesn't Find Shopify Provider

### ISSUE THREAD

**Issue by ShaunaGordon** [SocialiteProviders/Providers#34]
The Shopify provider doesn't seem to be completely installed/released.

I had to go all the way to adding the Shopify provider's git url to the `repositories` array, because without it, Composer kept throwing "The requested package socialiteproviders/shopify could not be found in any version," errors.

In the process of troubleshooting, I also found that the Shopify provider only registers versions 1.0 and dev-master. There is no 2.0 version, like there is with the other providers.

(To compare, I did test installs of the Discord provider, which worked as expected by installing version 2.0 with the `composer require` command, meaning it's an issue with the Shopify provider and not my access to SocialiteProviders as a whole.)

**Comment by faustbrian** [comment]
I will add the provider to packagist when I am back at my mac.

**Comment by faustbrian** [comment]
There is no version 2.0 because the current state of the provider is the first iteration so there is no need for a version 2 since there haven't been any major changes.

**Comment by faustbrian** [comment]
@ShaunaGordon Should be available on packagist now.
