### ISSUE TITLE
Discord scopes are explicitly defined in the provider

### ISSUE THREAD

**Issue by jimsug** [SocialiteProviders/Providers#344]
The Discord Provider overrides the default (empty) array of scopes. Because of the way that `scopes()` is implemented on `BaseProvider`, this means that if developers don't want to request email information, passing `->scopes(['identify'])` (i.e. explicitly _not_ requesting email) doesn't function as expected.

https://github.com/SocialiteProviders/Providers/blob/master/src/Discord/Provider.php#L18

It is unclear from the contribution guidelines whether you're accepting such changes, happy to fix it if you are.

**Comment by m1guelpf** [comment]
Feel free to PR this :D

**Comment by SeoFood** [comment]
Workaround:

```php
Socialite::with('discord')
  ->setScopes([])
  ->redirect();
```

**Comment by jimsug** [comment]
> 
> 
> Workaround:
> 
> ```
> Socialite::with('discord')
>   ->setScopes([])
>   ->redirect();
> ```

Is this tested and works, though? I would expect that you must pass at least one valid scope to a provider.

The `setScopes()` methods does an `array_merge()`, and this means that that hardcoded and explicitly defined scopes will be merged with the empty array: https://github.com/laravel/socialite/blob/4.0/src/Two/AbstractProvider.php#L305

Even if it works, though it's probably the wrong behaviour to require.

**Comment by jimsug** [comment]
Hrm. Having looked at the other providers, there seem to be default scopes set, so changing this would break the pattern. I don't think the PR is required.

**Comment by mackhankins** [comment]
I don't want email forced.  Ugh.
