### ISSUE TITLE
Update Slack Provider on Packagist

### ISSUE THREAD

**Issue by Micky5991** [SocialiteProviders/Providers#349]
The latest version of `socialiteproviders/slack` is over 2 years and does not contain fixes for breaking changes for Laravel 6.0.

In the latest released version of it on packagist contains the removed `array_get` helper, but the current version on `master` contains the new `Arr::get` helper.

Please update the version on packagist, so it is compatible with Laravel 6.0.

`master`: https://github.com/SocialiteProviders/Slack/blob/master/Provider.php#L137
`v3.0.3`: https://github.com/SocialiteProviders/Slack/blob/v3.0.3/Provider.php#L137

**Comment by m1guelpf** [comment]
Done
