### ISSUE TITLE
Google Plus Auth for a single tld

### ISSUE THREAD

**Issue by abishekrsrikaanth** [SocialiteProviders/Providers#35]
Am not sure if I am creating the issue at the right place. I started implement Google Authentication using the `Google-Plus` provider. Is there a way to allow only a single tld? For example if my Google Auth is being built on `foo.com`, I only want the auth to work with `@foo.com` and not any other email. Is there a config to do this or is there another way to implement this.

**Comment by ShaunaGordon** [comment]
Google's API kind of allows for this, and I know the default Socialite Google driver allows for the mechanism involved. As a result, the Google+ one _should_ also support it, though I haven't personally tried it with the G+ one (alternatively, you might be able to use the built in Google one for your purposes).

In the code that goes out to the provider, you pass the `hd` (hosted domain) field:

`return Socialite::driver('google')->with(['hd' => 'foo.com'])->redirect();`

This changes the OAuth screen to reflect the hosted domain. ([This is one of those things that isn't really documented by Google.](https://groups.google.com/forum/#!topic/oauth2-dev/SRStIuewiws))

Then, in the callback code, you check the email domain against your allowed domain(s) with something like:

```
$user = Socialite::driver('google')->user();
if($user && $user->user['domain'] == 'foo.com') {
    // Log user in
}
```
