### ISSUE TITLE
Update Twitch Provider on Packagist

### ISSUE THREAD

**Issue by kalizi** [SocialiteProviders/Providers#350]
The latest version of `socialiteproviders/twitch` is 5.0 and does not contain fixes for breaking changes for Laravel 6.0.

In the latest released version of it on packagist contains the removed `array_get `helper, but the current version on master contains the new `Arr::get` helper, I had to update composer.json in order to get `dev-master` version in order to make it work.

Please update the version on packagist, so it is compatible with Laravel 6.0.

**Comment by m1guelpf** [comment]
DOne
