### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by RobertBoes** [SocialiteProviders/Providers#355]
There hasn't been an update to `socialiteproviders/vimeo` since Jan 26, 2017 while a PR (#298) has been merged with useful changes. I don't know for other libraries, but wouldn't it be better to use a release method that Illuminate is using? They basically have some sort of composer sub-modules. Each release is then automatically done for each sub-module.

**Comment by m1guelpf** [comment]
We're working on this (see #363), would love your help :D

**Comment by m1guelpf** [comment]
Hey @atymic we're having some issues with the script erroring on the Google repo, could you take a look?

**Comment by atymic** [comment]
👀

**Comment by atymic** [comment]
PR created in #376 just a typo in the URL :)
