### ISSUE TITLE
CoinBase: 404 Not found

### ISSUE THREAD

**Issue by Paulsky** [SocialiteProviders/Providers#356]
Hello,

The `getUserByToken()` results in a 404 (https://api.coinbase.com/v1/users/self). I think this has to be updated to `https://api.coinbase.com/v2/user`.

But when I do that, I receive an error 'Undefined index: user', probably from the 'mapUserToObject' function.

**Comment by faustbrian** [comment]
https://github.com/SocialiteProviders/Providers/pull/357 should resolve this

ping @m1guelpf

**Comment by Paulsky** [comment]
Thank you @faustbrian !
