### ISSUE TITLE
Call to undefined method Illuminate\Session\Store::set() with Linkedin login

### ISSUE THREAD

**Issue by hengsoheak** [SocialiteProviders/Providers#36]
I have used Laravel Socialite with default configuration another social like google,Facebook,Twitter is work fine but when I create Linkedin it respond as below errors

"require": {
        "php": ">=5.6.4",
        "laracasts/flash": "^2.0",
        "laravel/framework": "5.4.*",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "nesbot/carbon": "^1.22",
        "socialiteproviders/google": "^3.0",
        "socialiteproviders/linkedin": "^3.0",
        "socialiteproviders/twitter": "^3.0",
        "twbs/bootstrap": "4.0.0-alpha.6"
    },

vendor/socialiteproviders/linkedin/Provider.php line 76:
Call to undefined method Illuminate\Session\Store::set()

Thank for help

**Comment by faustbrian** [comment]
https://github.com/SocialiteProviders/Providers/commit/1d1c1cfff35ea8d954d5c80b18ef613dd6fa6a3d
