### ISSUE TITLE
Battle.net Provider

### ISSUE THREAD

**Issue by Zemill** [SocialiteProviders/Providers#362]
I was having issues getting the battle.net provider to work and looked into the code and believe I found an issue.

The code is calling the following endpoint in the Providers.php class file, in protected function getUserByToken($token) method

`.api.battle.net/account/user`  I believe it should be  `.battle.net/oauth/userinfo`

**Comment by Zemill** [comment]
The issue appears to be that composer is using the latest package, which is not the correct commit.  Switching the version to dev-master in the composer.json file resolves the issue.

**Comment by m1guelpf** [comment]
Should be fixed now
