### ISSUE TITLE
Update Okta provider on Packagist

### ISSUE THREAD

**Issue by Zakini** [SocialiteProviders/Providers#368]
Just to echo an issue raised on the Okta subtree (https://github.com/SocialiteProviders/Okta/issues/3) and similar issues in other providers, the Okta provider is incompatible with Laravel 6 due to the breaking changes to array helpers.

This is issue is already fixed in master, so could this version please be released and pushed to Packagist?

**Comment by timothyrowan** [comment]
Anything?

**Comment by pacoorozco** [comment]
Please, can you update Packagist version? If you need help I can do it for you xD

**Comment by atymic** [comment]
It's tagged now as `1.1.0`
Apologies for the massive delay, I've joined the team and will be responsive in the future so feel free to reach out :).
