### ISSUE TITLE
Shopify Provider: Call to Undefined Method Provider::config()

### ISSUE THREAD

**Issue by ShaunaGordon** [SocialiteProviders/Providers#37]
It looks like `$this->config`, is used, but never defined.

**Comment by faustbrian** [comment]
Fixed https://github.com/SocialiteProviders/Providers/commit/5070fa23867fd6ea71b66c9024dc01838577c4f6

**Comment by faustbrian** [comment]
Also please consider to send PRs instead of just opening issues without much info or help.

**Comment by ShaunaGordon** [comment]
Normally, I would, but this one did not give me any more information (undefined errors are the extent of the information I have) and I don't know enough about the package to offer a PR.
