### ISSUE TITLE
SocialiteProviders/Steam, Laravel5.3 and Sociallite2

### ISSUE THREAD

**Issue by Arekusei** [SocialiteProviders/Providers#38]
It's possible?

**Comment by faustbrian** [comment]
No, only Laravel 5.4+.

**Comment by Arekusei** [comment]
But the differences between commits insignificant.
https://github.com/SocialiteProviders/Steam/commit/95cf6291b3d002523e7e0b0ea53a62331a766ff9
This commit compatible with 2.0 manager.
New commits contain no significant changes except change itself composer.json.
It's like something out illogical.

**Comment by faustbrian** [comment]
The version requirement is not about one single commit being compatible or not, there are differences between Socialite 2.0 and 3.0 which require different Manager releases.

All new providers will require Socialite 3.0 and Laravel 5.4 or higher to make sure the latest releases are supported. If you don't like to use the newest releases of Laravel and Co. that's fine but please don't just dismiss it as illogical.

**Comment by Arekusei** [comment]
I mean that the incompatibility within the provider for Steam (as it should be, and many others) is not available, but it is encapsulated in the manager. Accordingly illogical formally compliant package/provider to do incompatible.

**Comment by Arekusei** [comment]
Why not mark the package as is compatible with the two versions of the manager.
```
"socialiteproviders/manager": "~2.0 || ~3.0",
```

**Comment by faustbrian** [comment]
Laravel 5.3 and 5.4 have different method names and I am not going to plunge a bunch of checks in some providers to check if the `put` or `set` method has to be called.

Everything onwards will require Laravel 5.4 and Socialite 3.0 or newer, that's the current state and will stay like this for now.
