### ISSUE TITLE
Replace LightOpenID for Steam provider

### ISSUE THREAD

**Issue by benjivm** [SocialiteProviders/Providers#383]
The [Steam provider](https://github.com/SocialiteProviders/Steam) depends on [LightOpenID](https://github.com/iignatov/lightopenid), which is [abandoned](https://github.com/iignatov/LightOpenID/issues/9#issuecomment-186659836). It is currently incompatible with PHP 7.4 and has pull requests open since 2016.

Error Exception on callback:
```
Function get_magic_quotes_gpc() is deprecated
```

From `iignatov\lightopenid\openid.php:891`:
```
$params['openid.' . $item] = function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() ? stripslashes($value) : $value;
```

**Comment by m1guelpf** [comment]
PRs welcome!

**Comment by ToeiRei** [comment]
as get_magic_quotes_gpc does not exist in php anymore, returning false since 5.4(?) it shouldn't be a big deal patching that up, I'd say until we get things back on track

**Comment by ToeiRei** [comment]
@benjivm a quick fix I'd suppose is swapping out that line with
`$params['openid.' . $item] = $this->data['openid_' . str_replace('.','_',$item)];`

**Comment by chescos** [comment]
Would we need to fork `iignatov/lightopenid` in order to replace that line or is there a better way to accomplish this?

**Comment by ToeiRei** [comment]
@chescos either that or get another implementation running.

**Comment by NurdTurd** [comment]
Please someone get on this!

**Comment by atymic** [comment]
I'm not sure why we even need that library. I will have a look and figure out if we can drop it.

**Comment by atymic** [comment]
Oh, it seems the docs I was reading for oauth 2 are only for game devs. Looks like we do need to use openid 🤔

**Comment by atymic** [comment]
Draft PR open here:
https://github.com/SocialiteProviders/Providers/pull/415

Would love it if people could test. Otherwise I'll test when I have time :)

**Comment by atymic** [comment]
Tagged as 3.0 :)
https://github.com/SocialiteProviders/Steam/releases/tag/v3.0.0
