### ISSUE TITLE
Create new release for Okta

### ISSUE THREAD

**Issue by jameshulse** [SocialiteProviders/Providers#384]
Hi, as the other issues mention, I've run into Laravel 6 support issues with the Okta provider. Fix exists in master, but not released yet. Can we please get a new release tag.

`Call to undefined function SocialiteProviders\Okta\array_get()`

**Comment by hugeps** [comment]
Copy that! Same problem here

**Comment by jameshulse** [comment]
@hugeps, if you haven't already done so, until they do the release you can work-around the issue by setting your composer.json as follows:
```
"require": {
    ...
    "socialiteproviders/okta": "dev-master"
},
```

**Comment by gofish543** [comment]
Can we get that release?

**Comment by atymic** [comment]
Tagged, see #368 sorry!
