### ISSUE TITLE
microsoft-graph: mail field is always null

### ISSUE THREAD

**Issue by koshian** [SocialiteProviders/Providers#390]
Hi.
getEmail() method return null with microsoft-graph.

> The mail property is read-only. It is automatically populated by Exchange Online. Without Exchange Online (or syncing with an on-prem AD instance), this field will always be null.
> 
> https://stackoverflow.com/questions/51026440/https-graph-microsoft-com-v1-0-users-endpoint-returning-users-with-mail-fiel

format of userPrincipalName is RFC822 mail address.  It seems correctly email address on Microsoft Graph API.

https://docs.microsoft.com/en-us/graph/api/resources/office365activeuserdetail?view=graph-rest-beta&viewFallbackFrom=graph-rest-beta

Could you use userPrincipalName as email address instead of mail field?

```
diff --git a/src/Microsoft-Graph/Provider.php b/src/Microsoft-Graph/Provider.php
index 64690a0..e49dcca 100755
--- a/src/Microsoft-Graph/Provider.php
+++ b/src/Microsoft-Graph/Provider.php
@@ -97,12 +97,17 @@ class Provider extends AbstractProvider
      */
     protected function mapUserToObject(array $user)
     {
+        // mail field is always null without Exchange online.
+        // Use userPrincipalName(UPN) instead of mail.
+        $mail = isset($user['mail']) ? $user['mail']
+                                     : Arr::get($user, 'userPrincipalName');
+
         // Mapping default Laravel user keys to the keys that are nested in the
         // response from the provider.
         return (new User())->setRaw($user)->map([
             'id' => $user['id'],
             'name' => $user['displayName'],
-            'email' => $user['mail'],
+            'email' => $mail,
 
             // The following values are not always required by the provider. We
             // cannot guarantee they will exist in the $user array.
```

**Comment by Jimbolino** [comment]
Microsoft-Graph should be deprecated.
Use "Microsoft" instead
https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft/Provider.php#L68

**Comment by atymic** [comment]
@Jimbolino if this is correct, we should PR a deperecation and remove form the docs.
