### ISSUE TITLE
Salesforce provider should be tagged

### ISSUE THREAD

**Issue by iansltx** [SocialiteProviders/Providers#396]
Right now the currently tagged version of the Salesforce provider (3.0) uses array_get, which doesn't work for Laravel 6+. The fix is on master but there's no tag for it. Not sure whether there are BC breaks (I'm guessing not) but we either need 3.1 or 4.0 here so you don't have to grab dev-master.

**Comment by atymic** [comment]
Sorry about this, we'll get it tagged ASAP!

**Comment by atymic** [comment]
Sorry for the delay, it's been tagged as `3.1`
https://packagist.org/packages/socialiteproviders/salesforce#v3.1.0

Thanks for your patience!
