### ISSUE TITLE
Provider Request » WHMCS

### ISSUE THREAD

**Issue by ZeProf2Code** [SocialiteProviders/Providers#397]
Hello! I'm requesting a provider for WHMCS because I don't really know how that OpenID is working.
Here is the WHMCS OpenID documentation : https://docs.whmcs.com/OpenID_Connect_Developer_Guide
Thank you.

**Comment by atymic** [comment]
Hey!

Thanks for the suggestion :)
I anyone wants to take a crack, feel free to PR.

**Comment by Max13** [comment]
@ZeProf2Code I would love to have your feedback on this please
