### ISSUE TITLE
Call to undefined function SocialiteProviders\Twitch\array_get()

### ISSUE THREAD

**Issue by DubStepMad** [SocialiteProviders/Providers#399]
Laravel: 6.18.7
PHP: 7.4.4
OS: ‪Ubuntu 18.04.4

`Call to undefined function SocialiteProviders\Twitch\array_get() {"userId":2,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function SocialiteProviders\\Twitch\\array_get() at /var/www/vhosts/*****.com/httpdocs/vendor/socialiteproviders/twitch/Provider.php:71)`

**Comment by codegeek1001** [comment]
The library is not compatible with Laravel 6 or higher. I also found this out recently. Right now, you will have to downgrade to Laravel  5.x if you want to use the released version of this library.
