### ISSUE TITLE
Is there a package for Zoho?

### ISSUE THREAD

**Issue by github-grabaz** [SocialiteProviders/Providers#400]
Following the documentation to install the provider for zoho by running:

`composer require socialiteproviders/zoho`

Leads to the error: 

> [InvalidArgumentException]                    
> Could not find a matching version of package socialiteproviders/zoho. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

Will there be a package available soon?
Is there documentation to use the code without a package?

**Comment by atymic** [comment]
I've tagged version `1.0.0`, but i'm waiting on access to packagist to add it. In the meantime, you can load it directly by adding the repo to your composer.json:
https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by atymic** [comment]
See #409

**Comment by atymic** [comment]
Tagged
https://github.com/SocialiteProviders/Zoho
