### ISSUE TITLE
HubSpot Scopes - Wrong URL Encoding

### ISSUE THREAD

**Issue by MCKLtech** [SocialiteProviders/Providers#408]
For example, when called like this:

`return Socialite::with('hubspot')->scopes(array('contacts', 'oauth'))->redirect();`

The URL is:

`&scope=contacts%2Coauth&response_type=code&state`

However, as per HubSpot's docs, it should be:

`contacts%20oauth`

In URL decoded terms, there should be a space (%20) between the scopes, not a comma (%2C)

**Comment by atymic** [comment]
@MCKLtech are you still having this issue?

**Comment by atymic** [comment]
Tagged in https://github.com/SocialiteProviders/HubSpot/releases/tag/v3.0.0
