### ISSUE TITLE
Providers missing from packagist 

### ISSUE THREAD

**Issue by atymic** [SocialiteProviders/Providers#409]
Some providers need to be added to packagist, but I don't yet have access. This issue is to keep track of the ones that need to be added still.

- [x] https://github.com/SocialiteProviders/Keycloak
- [x] https://github.com/SocialiteProviders/Zoho

cc @m1guelpf

**Comment by Jimbolino** [comment]
https://github.com/SocialiteProviders/SURFconext
is also missing

**Comment by atymic** [comment]
Submitted 👍 
https://packagist.org/packages/socialiteproviders/surfconext
