### ISSUE TITLE
Twitch provider change rules

### ISSUE THREAD

**Issue by IvanovPavel** [SocialiteProviders/Providers#411]
Since 1 May 2020 Twitch.tv changed a rule to request to API endpoints `https://api.twitch.tv/helix/users`. 
It need to send both: **Client ID and OAuth token.**

So now, this provider _does not work_!
Fix it please.

**Comment by atymic** [comment]
Please make a PR :)

**Comment by atymic** [comment]
Tagged :)
https://github.com/SocialiteProviders/Twitch/tree/v5.2.0
