### ISSUE TITLE
Microsoft provider avatar

### ISSUE THREAD

**Issue by danswiser** [SocialiteProviders/Providers#425]
Is it possible to retrieve the user avatar from the `microsoft` provider?

**Comment by atymic** [comment]
Can you clarify which microsoft provider this is for (we have a few)?
PRs welcome :)

**Comment by danswiser** [comment]
Just the regular `microsoft` provider. It looks like that one replaces `graph`, `live` and `azure` correct?

**Comment by danswiser** [comment]
@atymic based on the help wanted label I assume this isn't currently possible. I started looking at making a PR to get the avatar URL but it looks like the microsoft api returns the binary data of the image. Do any other providers return the binary data? The only ones I found just returned the avatar URL.

https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0#using-the-binary-data-of-the-requested-photo

**Comment by danswiser** [comment]
PR #429
