### ISSUE TITLE
Error using Apple Sign In userFromToken

### ISSUE THREAD

**Issue by dangerdan** [SocialiteProviders/Providers#441]
https://github.com/SocialiteProviders/Providers/blob/8f0711e3ff301f3b2ee0867317d00de7e3d5e1a6/src/Apple/Provider.php#L200

This implementation seems incorrect. The code suggests that a token is passed to this method, but the token is transformed into a user in the user() method:

```
        $apple_user_token = $this->getUserByToken(
            $token = Arr::get($response, 'id_token')
        );
```

Shouldn't this method simply read from the array? mapUserToObject(array $user). When I attempt to use it I get an error:

  #message: "array_key_exists() expects parameter 2 to be array, null given"
  #code: 0
  #file: "/Users/dan/sbg-web/vendor/socialiteproviders/apple/Provider.php"
  #line: 197
  #severity: E_WARNING

**Comment by atymic** [comment]
@dangerdan are you still having an issue?
