### ISSUE TITLE
Failed to validate OpenID login: unknown error

### ISSUE THREAD

**Issue by CockersGaming** [SocialiteProviders/Providers#443]
Hello.  I am trying to add socialite steam to be able to login to my dashboard with.

I get this error: 

> Failed to validate OpenID login: unknown error

Here is my steam controller:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Auth;
use Laravel\Socialite\Facades\Socialite;

class SteamController extends Controller
{
    public function redirect()
    {
        return Socialite::with('steam')->redirect();
    }

    public function handle()
    {
        // Collect response from callback
        $response = Socialite::driver('steam')->user();

        dd($response);



        // Look for existing user with steam ID
        $user = User::where('steamID', $response->getId())->first();

        // Check if steam ID is linked to account
        if ($user) {
            if($user->steamID != $response->getId()){
                $user->update([
                    'steamID' => $response->getId()
                ]);
            }
            Auth::login($user);
            //Log::l('LOGGED_IN', "Via steam Login");

            return redirect()->route('dashboard')->with('status', 'You have been logged in via Steam.');
        } else {
            $newUser = factory(\App\User::class)->create([
                'name' => $response->getName(),
                'email' => $response->getEmail(),
                'avatar' => $response->getAvatar(),
                'steamID' => $response->getId()
            ]);
            //$newUser->assignRole('Public');
            Auth::login($newUser);
            //Log::l('USER_CREATED', "via steam Login");

            return redirect()->route('dashboard')->with('status', 'User Created with Steam.');
        }
    }
}
```

My Event Listener Provider:

```
protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        SocialiteWasCalled::class => [
            // add your listeners (aka providers) here
            \SocialiteProviders\Discord\DiscordExtendSocialite::class,
            \SocialiteProviders\Steam\SteamExtendSocialite::class
        ],
    ];
```

My app.php:

```
Laravel\Socialite\SocialiteServiceProvider::class,
\SocialiteProviders\Manager\ServiceProvider::class,
```

The button to login with steam:

```
<div class="mt-4 text-center">
          <a href="{{route('login.steam')}}" class="btn btn-success btn-block waves-effect waves-light"><i class="fab fa-steam"></i> Login With Steam</a>
</div>
```

web.php:

```
// Steam Start
Route::get('/login/steam', 'Auth\SteamController@redirect')->name('login.steam');
Route::get('/login/steam/callback', 'Auth\SteamController@handle');
// Steam End
```

Help Much Appreciated,

Regards,
James

**Comment by atymic** [comment]
cc @ilumos @Metrakit who are using the library.

Any ideas?

**Comment by ilumos** [comment]
Can you paste the steam URL that you are redirected to?

Also the URL that Steam redirects you to after login?

**Comment by CockersGaming** [comment]
> 
> 
> Can you paste the steam URL that you are redirected to?
> 
> Also the URL that Steam redirects you to after login?

The redirect link is https://127.0.0.1:8000/login/steam/callback

When I press the login with steam button it takes me to here: https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2F127.0.0.1%3A8000%2Flogin%2Fsteam%2Fcallback&openid.realm=http%3A%2F%2F127.0.0.1%3A8000&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select

That link is the login form for steam.

When I login I go to this link:
http://127.0.0.1:8000/login/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198071889507&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198071889507&openid.return_to=http%3A%2F%2F127.0.0.1%3A8000%2Flogin%2Fsteam%2Fcallback&openid.response_nonce=2020-06-30T11%3A54%3A16ZgFseoHwe1r9YkNplAmAVIOJmXJo%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=VUqcQ%2Bekhg362QkKjVtgovJm1xU%3D

I have done a data dump of the responce and it returns the correct data.

**Comment by CockersGaming** [comment]
according to https://socialiteproviders.netlify.app/providers/steam.html u have to use a cappital (Steam) however i then get this `Driver [Steam] not supported. `

but when I change it to a lowercase (steam) it will go to

**Comment by CockersGaming** [comment]
wron button xD.

It is now working.
