### ISSUE TITLE
Passport Provider

### ISSUE THREAD

**Issue by homeoftheunits** [SocialiteProviders/Providers#466]
Hi there,

i use the Passport Provider in my Application. So, i have my own oauth2 Service. In this oauth2 Service are the User Informations collected. Login works fine, and everything do what it should. But i have two Problems.

1. Where should i collect the User Informations from the OAuth Service
`$user = Socialite::driver('laravelpassport')->user();`

This works only in the Controller method, wich is called by the Callback. In another Controller (when i need the user informations) this throws an error. Do i something wrong, or ist this correct? What is the best practice to store the user informations temporary? 

2. I call the API from the Auth Service and get no informations
In the first step i store the token in the session. Now when i call the Passport API in another Controller, like that:

```
$response = Http::get(env('LARAVELPASSPORT_AUTHORIZE_URI').'/oauth/tokens', [
    'headers' => [
        'Accept' => 'application/json',
        'Authorization' => 'Bearer '.Session::get('user')->token,
    ],
]);
```
or
```
$response = Http::get(env('LARAVELPASSPORT_AUTHORIZE_URI').'/api/logout', [
    'headers' => [
        'Accept' => 'application/json',
        'Authorization' => 'Bearer '.Session::get('user')->token,
    ],
]);
```
the response body is always the HTML Code from the Login Page.

What do i wrong? Thanks for your help

Cheers 
Ralf

**Comment by shehi** [comment]
When you do `$user = Socialite::driver('laravelpassport')->user();` in your Login/Oauth2 controller whatever, you should be persisting token, refresh_token and their respective TTL info in your User storage. And later, in some other controller, using those tokens, you can query the target API on behalf of these token-owners. I have never used Passport's `/tokens` endpoint, but something tells me you can't query that endpoint with scoped JWT tokens like these OAuth2 ones. You can query general Laravel app's API tho. The same kinda goes for `/logout` endpoint as well: the goal of logout action is to delete browser cookies and related session data - how are you achieving these with a server side call like that?!

And do not store PII (personally identifiable information) in Session. Session isn't safe space for such personal data. These OAuth2 tokens are PII (equal to a user password) and very sensitive info.

**Comment by atymic** [comment]
> What is the best practice to store the user informations temporary?

You should create a local user in your system, and save the passport access token with that user. Then, you can grab that token and use it in requests.
