### ISSUE TITLE
Steam provider doesn't play nicely behind a reverse proxy

### ISSUE THREAD

**Issue by andy3471** [SocialiteProviders/Providers#467]
I tried updating my laravel socialite steam provider to 3.0, it worked with HTTPS, but when using a reverse proxy (reverse proxy is listening on HTTPS and directing to the site on HTTP), I was getting an error that the realm does not match the return to.

On looking at the URL, that it's directing to on steam:
https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=https%3A%2F%2F360nohope.co.uk%2Flogin%2Fsteam%2Fcallback&openid.realm=http%3A%2F%2F360nohope.co.uk&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select

 You can see that the return to is generating with HTTPS, but the Realm is HTTP. 

I can change the callback URL by changing the Redirect setting in config/services, I'm not sure if there is a way of overwriting the 'realm' it's using.

**Comment by bytestream** [comment]
You can overwrite the realm in the config as well

**Comment by atymic** [comment]
As @bytestream said, you can overwrite the realm config :)
