### ISSUE TITLE
Attemping to create new Provider, Target Class does not exist error

### ISSUE THREAD

**Issue by svpernova09** [SocialiteProviders/Providers#478]
I'm trying to follow along w/ https://socialiteproviders.netlify.app/providers/zendesk.html, but instead of using ZenDesk, I've created my own provider "Lavishsoft" and modeled it exactly like the Zendesk provider. I've setup a private repo for the provider, added the repo to `composer.json` as:
 ```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/svpernova09/LavishsoftProvider"
        }
    ],`
```
and  
```
"svpernova09/lavishsoftprovider": "dev-master"
```

I have my  event service provider `listen` property set up as: 
```    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            // add your listeners (aka providers) here
            'SocialiteProviders\Lavishsoft\LavishsoftExtendSocialite',
        ],
    ];
```

My `LavishsoftExtendSocialite.php` looks like 
```<?php

namespace SocialiteProviders\Lavishsoft;

use SocialiteProviders\Manager\SocialiteWasCalled;

class LavishsoftExtendSocialite
{
    /**
     * Register the provider.
     *
     * @param \SocialiteProviders\Manager\SocialiteWasCalled $socialiteWasCalled
     */
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        $socialiteWasCalled->extendSocialite('lavishsoft', Provider::class);
    }
}
```

I can't figure out what I'm doing wrong that composer can't find my class

The socialite provider docs say to use
 ```    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // add your listeners (aka providers) here
        'SocialiteProviders\\Zendesk\\ZendeskExtendSocialite@handle',
    ],
```
but I get the same error there, which the laravel 7.x docs show single slashes and no method name.

Here's the output of `composer dump-auto`:

![image](https://user-images.githubusercontent.com/967362/88462463-08a6d900-ce71-11ea-8657-77bff432a7e1.png)

And the same 

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [SocialiteProviders\Lavishsoft\LavishsoftExtendSocialite] does not exist.
```

in the browser when viewing `/login` route

You can find my provider repo here: https://github.com/svpernova09/LavishsoftProvider

Thanks for any suggestions.

**Comment by svpernova09** [comment]
I'm bad at typing. The issue was in my provider, I had "SocialiteProviders\\LavishSoft\\": "src/" instead of "SocialiteProviders\\Lavishsoft\\": "src/" That capital S >.<

**Comment by atymic** [comment]
No worries :)
