### ISSUE TITLE
Release new version of all providers

### ISSUE THREAD

**Issue by atymic** [SocialiteProviders/Providers#480]
Release new major version dropping support for < `7.2`

- [x] Release Provider [23andme](https://github.com/SocialiteProviders/23andme/releases)
- [x] Release Provider [37Signals](https://github.com/SocialiteProviders/37Signals/releases)
- [x] Release Provider [500px](https://github.com/SocialiteProviders/500px/releases)
- [ ] Release Provider [Acclaim](https://github.com/SocialiteProviders/Acclaim/releases)
- [ ] Release Provider [Admitad](https://github.com/SocialiteProviders/Admitad/releases)
- [ ] Release Provider [Amazon](https://github.com/SocialiteProviders/Amazon/releases)
- [ ] Release Provider [AngelList](https://github.com/SocialiteProviders/AngelList/releases)
- [ ] Release Provider [App.net](https://github.com/SocialiteProviders/App.net/releases)
- [ ] Release Provider [Apple](https://github.com/SocialiteProviders/Apple/releases)
- [ ] Release Provider [ArcGIS](https://github.com/SocialiteProviders/ArcGIS/releases)
- [ ] Release Provider [Asana](https://github.com/SocialiteProviders/Asana/releases)
- [ ] Release Provider [Auth0](https://github.com/SocialiteProviders/Auth0/releases)
- [ ] Release Provider [Aweber](https://github.com/SocialiteProviders/Aweber/releases)
- [ ] Release Provider [Battle.net](https://github.com/SocialiteProviders/Battle.net/releases)
- [ ] Release Provider [Binance](https://github.com/SocialiteProviders/Binance/releases)
- [ ] Release Provider [Bit.ly](https://github.com/SocialiteProviders/Bit.ly/releases)
- [ ] Release Provider [Bitbucket](https://github.com/SocialiteProviders/Bitbucket/releases)
- [ ] Release Provider [Box](https://github.com/SocialiteProviders/Box/releases)
- [x] Release Provider [Buffer](https://github.com/SocialiteProviders/Buffer/releases)
- [ ] Release Provider [CampaignMonitor](https://github.com/SocialiteProviders/CampaignMonitor/releases)
- [ ] Release Provider [Cheddar](https://github.com/SocialiteProviders/Cheddar/releases)
- [ ] Release Provider [ClaveUnica](https://github.com/SocialiteProviders/ClaveUnica/releases)
- [ ] Release Provider [Coinbase](https://github.com/SocialiteProviders/Coinbase/releases)
- [ ] Release Provider [ConstantContact](https://github.com/SocialiteProviders/ConstantContact/releases)
- [ ] Release Provider [Coursera](https://github.com/SocialiteProviders/Coursera/releases)
- [ ] Release Provider [Dailymotion](https://github.com/SocialiteProviders/Dailymotion/releases)
- [ ] Release Provider [Dataporten](https://github.com/SocialiteProviders/Dataporten/releases)
- [ ] Release Provider [Deezer](https://github.com/SocialiteProviders/Deezer/releases)
- [ ] Release Provider [DigitalOcean](https://github.com/SocialiteProviders/DigitalOcean/releases)
- [ ] Release Provider [Discogs](https://github.com/SocialiteProviders/Discogs/releases)
- [ ] Release Provider [Discord](https://github.com/SocialiteProviders/Discord/releases)
- [ ] Release Provider [Disqus](https://github.com/SocialiteProviders/Disqus/releases)
- [ ] Release Provider [Douban](https://github.com/SocialiteProviders/Douban/releases)
- [ ] Release Provider [Dribbble](https://github.com/SocialiteProviders/Dribbble/releases)
- [ ] Release Provider [Dropbox](https://github.com/SocialiteProviders/Dropbox/releases)
- [ ] Release Provider [Envato](https://github.com/SocialiteProviders/Envato/releases)
- [ ] Release Provider [Etsy](https://github.com/SocialiteProviders/Etsy/releases)
- [ ] Release Provider [Eventbrite](https://github.com/SocialiteProviders/Eventbrite/releases)
- [ ] Release Provider [EyeEm](https://github.com/SocialiteProviders/EyeEm/releases)
- [ ] Release Provider [Facebook](https://github.com/SocialiteProviders/Facebook/releases)
- [ ] Release Provider [Faceit](https://github.com/SocialiteProviders/Faceit/releases)
- [ ] Release Provider [Fitbit](https://github.com/SocialiteProviders/Fitbit/releases)
- [ ] Release Provider [Flattr](https://github.com/SocialiteProviders/Flattr/releases)
- [ ] Release Provider [Flexkids](https://github.com/SocialiteProviders/Flexkids/releases)
- [ ] Release Provider [Flickr](https://github.com/SocialiteProviders/Flickr/releases)
- [ ] Release Provider [Foursquare](https://github.com/SocialiteProviders/Foursquare/releases)
- [ ] Release Provider [FranceConnect](https://github.com/SocialiteProviders/FranceConnect/releases)
- [ ] Release Provider [GarminConnect](https://github.com/SocialiteProviders/GarminConnect/releases)
- [ ] Release Provider [GettyImages](https://github.com/SocialiteProviders/GettyImages/releases)
- [ ] Release Provider [GitHub](https://github.com/SocialiteProviders/GitHub/releases)
- [x] Release Provider [GitLab](https://github.com/SocialiteProviders/GitLab/releases)
- [ ] Release Provider [Gitea](https://github.com/SocialiteProviders/Gitea/releases)
- [ ] Release Provider [Gitee](https://github.com/SocialiteProviders/Gitee/releases)
- [ ] Release Provider [Goodreads](https://github.com/SocialiteProviders/Goodreads/releases)
- [ ] Release Provider [Google](https://github.com/SocialiteProviders/Google/releases)
- [ ] Release Provider [Google-Plus](https://github.com/SocialiteProviders/Google-Plus/releases)
- [ ] Release Provider [HabrCareer](https://github.com/SocialiteProviders/HabrCareer/releases)
- [ ] Release Provider [Harvest](https://github.com/SocialiteProviders/Harvest/releases)
- [ ] Release Provider [HeadHunter](https://github.com/SocialiteProviders/HeadHunter/releases)
- [ ] Release Provider [Heroku](https://github.com/SocialiteProviders/Heroku/releases)
- [ ] Release Provider [HubSpot](https://github.com/SocialiteProviders/HubSpot/releases)
- [ ] Release Provider [Human-API](https://github.com/SocialiteProviders/Human-API/releases)
- [ ] Release Provider [IFSP](https://github.com/SocialiteProviders/IFSP/releases)
- [ ] Release Provider [Imgur](https://github.com/SocialiteProviders/Imgur/releases)
- [ ] Release Provider [Instagram](https://github.com/SocialiteProviders/Instagram/releases)
- [ ] Release Provider [InstagramBasic](https://github.com/SocialiteProviders/InstagramBasic/releases)
- [ ] Release Provider [Intercom](https://github.com/SocialiteProviders/Intercom/releases)
- [ ] Release Provider [Jira](https://github.com/SocialiteProviders/Jira/releases)
- [ ] Release Provider [Kakao](https://github.com/SocialiteProviders/Kakao/releases)
- [ ] Release Provider [Keycloak](https://github.com/SocialiteProviders/Keycloak/releases)
- [ ] Release Provider [Laravel-Example](https://github.com/SocialiteProviders/Laravel-Example/releases)
- [ ] Release Provider [Laravel-Passport](https://github.com/SocialiteProviders/Laravel-Passport/releases)
- [x] Release Provider [Line](https://github.com/SocialiteProviders/Line/releases)
- [ ] Release Provider [LinkedIn](https://github.com/SocialiteProviders/LinkedIn/releases)
- [ ] Release Provider [Lumen-Example](https://github.com/SocialiteProviders/Lumen-Example/releases)
- [ ] Release Provider [MailChimp](https://github.com/SocialiteProviders/MailChimp/releases)
- [ ] Release Provider [Mailru](https://github.com/SocialiteProviders/Mailru/releases)
- [ ] Release Provider [MakerLog](https://github.com/SocialiteProviders/MakerLog/releases)
- [ ] Release Provider [Mattermost](https://github.com/SocialiteProviders/Mattermost/releases)
- [ ] Release Provider [Mediacube](https://github.com/SocialiteProviders/Mediacube/releases)
- [ ] Release Provider [Medium](https://github.com/SocialiteProviders/Medium/releases)
- [ ] Release Provider [Meetup](https://github.com/SocialiteProviders/Meetup/releases)
- [ ] Release Provider [Microsoft](https://github.com/SocialiteProviders/Microsoft/releases)
- [ ] Release Provider [Microsoft-Azure](https://github.com/SocialiteProviders/Microsoft-Azure/releases)
- [ ] Release Provider [Microsoft-Graph](https://github.com/SocialiteProviders/Microsoft-Graph/releases)
- [ ] Release Provider [Microsoft-Live](https://github.com/SocialiteProviders/Microsoft-Live/releases)
- [ ] Release Provider [Microsoft-TeamService](https://github.com/SocialiteProviders/Microsoft-TeamService/releases)
- [ ] Release Provider [Mixcloud](https://github.com/SocialiteProviders/Mixcloud/releases)
- [ ] Release Provider [Mollie](https://github.com/SocialiteProviders/Mollie/releases)
- [ ] Release Provider [Moves](https://github.com/SocialiteProviders/Moves/releases)
- [ ] Release Provider [Naver](https://github.com/SocialiteProviders/Naver/releases)
- [ ] Release Provider [Netlify](https://github.com/SocialiteProviders/Netlify/releases)
- [ ] Release Provider [Nocks](https://github.com/SocialiteProviders/Nocks/releases)
- [ ] Release Provider [OAuthgen](https://github.com/SocialiteProviders/OAuthgen/releases)
- [ ] Release Provider [OSChina](https://github.com/SocialiteProviders/OSChina/releases)
- [ ] Release Provider [Odnoklassniki](https://github.com/SocialiteProviders/Odnoklassniki/releases)
- [ ] Release Provider [Okta](https://github.com/SocialiteProviders/Okta/releases)
- [ ] Release Provider [Orcid](https://github.com/SocialiteProviders/Orcid/releases)
- [ ] Release Provider [Ovh](https://github.com/SocialiteProviders/Ovh/releases)
- [ ] Release Provider [Patreon](https://github.com/SocialiteProviders/Patreon/releases)
- [ ] Release Provider [PayPal](https://github.com/SocialiteProviders/PayPal/releases)
- [ ] Release Provider [PayPal-Sandbox](https://github.com/SocialiteProviders/PayPal-Sandbox/releases)
- [ ] Release Provider [Paymill](https://github.com/SocialiteProviders/Paymill/releases)
- [ ] Release Provider [PeeringDB](https://github.com/SocialiteProviders/PeeringDB/releases)
- [ ] Release Provider [Pinterest](https://github.com/SocialiteProviders/Pinterest/releases)
- [ ] Release Provider [Pipedrive](https://github.com/SocialiteProviders/Pipedrive/releases)
- [ ] Release Provider [Pixnet](https://github.com/SocialiteProviders/Pixnet/releases)
- [ ] Release Provider [Podio](https://github.com/SocialiteProviders/Podio/releases)
- [ ] Release Provider [Procore](https://github.com/SocialiteProviders/Procore/releases)
- [ ] Release Provider [ProductHunt](https://github.com/SocialiteProviders/ProductHunt/releases)
- [ ] Release Provider [ProjectV](https://github.com/SocialiteProviders/ProjectV/releases)
- [ ] Release Provider [Pushbullet](https://github.com/SocialiteProviders/Pushbullet/releases)
- [ ] Release Provider [QQ](https://github.com/SocialiteProviders/QQ/releases)
- [ ] Release Provider [QuickBooks](https://github.com/SocialiteProviders/QuickBooks/releases)
- [ ] Release Provider [Readability](https://github.com/SocialiteProviders/Readability/releases)
- [ ] Release Provider [Redbooth](https://github.com/SocialiteProviders/Redbooth/releases)
- [ ] Release Provider [Reddit](https://github.com/SocialiteProviders/Reddit/releases)
- [ ] Release Provider [Rekono](https://github.com/SocialiteProviders/Rekono/releases)
- [ ] Release Provider [RunKeeper](https://github.com/SocialiteProviders/RunKeeper/releases)
- [ ] Release Provider [SURFconext](https://github.com/SocialiteProviders/SURFconext/releases)
- [ ] Release Provider [Sage](https://github.com/SocialiteProviders/Sage/releases)
- [ ] Release Provider [SalesForce](https://github.com/SocialiteProviders/SalesForce/releases)
- [ ] Release Provider [SciStarter](https://github.com/SocialiteProviders/SciStarter/releases)
- [ ] Release Provider [SharePoint](https://github.com/SocialiteProviders/SharePoint/releases)
- [ ] Release Provider [Shopify](https://github.com/SocialiteProviders/Shopify/releases)
- [ ] Release Provider [Slack](https://github.com/SocialiteProviders/Slack/releases)
- [ ] Release Provider [Smashcast](https://github.com/SocialiteProviders/Smashcast/releases)
- [ ] Release Provider [Snapchat](https://github.com/SocialiteProviders/Snapchat/releases)
- [ ] Release Provider [SoundCloud](https://github.com/SocialiteProviders/SoundCloud/releases)
- [ ] Release Provider [Spotify](https://github.com/SocialiteProviders/Spotify/releases)
- [ ] Release Provider [StackExchange](https://github.com/SocialiteProviders/StackExchange/releases)
- [ ] Release Provider [Steam](https://github.com/SocialiteProviders/Steam/releases)
- [ ] Release Provider [Steem](https://github.com/SocialiteProviders/Steem/releases)
- [ ] Release Provider [StockTwits](https://github.com/SocialiteProviders/StockTwits/releases)
- [ ] Release Provider [Strava](https://github.com/SocialiteProviders/Strava/releases)
- [ ] Release Provider [StreamElements](https://github.com/SocialiteProviders/StreamElements/releases)
- [ ] Release Provider [Streamlabs](https://github.com/SocialiteProviders/Streamlabs/releases)
- [ ] Release Provider [Stripe](https://github.com/SocialiteProviders/Stripe/releases)
- [ ] Release Provider [TVShowTime](https://github.com/SocialiteProviders/TVShowTime/releases)
- [ ] Release Provider [Teamleader](https://github.com/SocialiteProviders/Teamleader/releases)
- [ ] Release Provider [Teamweek](https://github.com/SocialiteProviders/Teamweek/releases)
- [ ] Release Provider [Telegram](https://github.com/SocialiteProviders/Telegram/releases)
- [ ] Release Provider [Todoist](https://github.com/SocialiteProviders/Todoist/releases)
- [ ] Release Provider [Trakt](https://github.com/SocialiteProviders/Trakt/releases)
- [ ] Release Provider [Trello](https://github.com/SocialiteProviders/Trello/releases)
- [ ] Release Provider [Tumblr](https://github.com/SocialiteProviders/Tumblr/releases)
- [ ] Release Provider [Twitch](https://github.com/SocialiteProviders/Twitch/releases)
- [ ] Release Provider [Twitter](https://github.com/SocialiteProviders/Twitter/releases)
- [ ] Release Provider [UCL](https://github.com/SocialiteProviders/UCL/releases)
- [ ] Release Provider [UFS](https://github.com/SocialiteProviders/UFS/releases)
- [ ] Release Provider [Uber](https://github.com/SocialiteProviders/Uber/releases)
- [ ] Release Provider [Ufutx](https://github.com/SocialiteProviders/Ufutx/releases)
- [ ] Release Provider [Unsplash](https://github.com/SocialiteProviders/Unsplash/releases)
- [ ] Release Provider [Untappd](https://github.com/SocialiteProviders/Untappd/releases)
- [ ] Release Provider [VKontakte](https://github.com/SocialiteProviders/VKontakte/releases)
- [ ] Release Provider [Venmo](https://github.com/SocialiteProviders/Venmo/releases)
- [ ] Release Provider [Vercel](https://github.com/SocialiteProviders/Vercel/releases)
- [ ] Release Provider [VersionOne](https://github.com/SocialiteProviders/VersionOne/releases)
- [ ] Release Provider [Vimeo](https://github.com/SocialiteProviders/Vimeo/releases)
- [ ] Release Provider [WeChatServiceAccount](https://github.com/SocialiteProviders/WeChatServiceAccount/releases)
- [ ] Release Provider [WeChatWeb](https://github.com/SocialiteProviders/WeChatWeb/releases)
- [ ] Release Provider [Weibo](https://github.com/SocialiteProviders/Weibo/releases)
- [ ] Release Provider [Weixin](https://github.com/SocialiteProviders/Weixin/releases)
- [ ] Release Provider [Weixin-Web](https://github.com/SocialiteProviders/Weixin-Web/releases)
- [ ] Release Provider [Whmcs](https://github.com/SocialiteProviders/Whmcs/releases)
- [ ] Release Provider [Withings](https://github.com/SocialiteProviders/Withings/releases)
- [ ] Release Provider [WordPress](https://github.com/SocialiteProviders/WordPress/releases)
- [ ] Release Provider [Xero](https://github.com/SocialiteProviders/Xero/releases)
- [ ] Release Provider [Xing](https://github.com/SocialiteProviders/Xing/releases)
- [ ] Release Provider [Yahoo](https://github.com/SocialiteProviders/Yahoo/releases)
- [ ] Release Provider [Yammer](https://github.com/SocialiteProviders/Yammer/releases)
- [ ] Release Provider [Yandex](https://github.com/SocialiteProviders/Yandex/releases)
- [ ] Release Provider [Yiban](https://github.com/SocialiteProviders/Yiban/releases)
- [ ] Release Provider [YouTube](https://github.com/SocialiteProviders/YouTube/releases)
- [ ] Release Provider [Zalo](https://github.com/SocialiteProviders/Zalo/releases)
- [ ] Release Provider [Zeit](https://github.com/SocialiteProviders/Zeit/releases)
- [ ] Release Provider [Zendesk](https://github.com/SocialiteProviders/Zendesk/releases)
- [ ] Release Provider [Zoho](https://github.com/SocialiteProviders/Zoho/releases)
- [ ] Release Provider [deviantART](https://github.com/SocialiteProviders/deviantART/releases)
- [ ] Release Provider [xREL](https://github.com/SocialiteProviders/xREL/releases)

**Comment by atymic** [comment]
@lucasmichot is there any other changes we need to do before this apart from #484 
Would be good to get them all lumped into a single 4.0.0 release

**Comment by lucasmichot** [comment]
The major remaining problem is that many providers only support Guzzle 6, and not 7.
They would typically miss this check:

`$postKey = (version_compare(ClientInterface::VERSION, '6') === 1) ? 'form_params' : 'body';`

This needs to be fixed before the `4.0.0` release

**Comment by atymic** [comment]
Ahh, good catch. We should definitely get that fixed as well.
I was thinking about adding more types through the providers & the manager as well.

**Comment by lucasmichot** [comment]
> I was thinking about adding more types through the providers & the manager as well.

Do you mean types, like method and argument typing? If so, I am absolutely 👍

**Comment by atymic** [comment]
Done via script :)
