### ISSUE TITLE
Opskins failed to install package

### ISSUE THREAD

**Issue by gmatkowski** [SocialiteProviders/Providers#483]
# Issue / Motivation:
Cannot install Opskins provider

## Expected behavior:
Install Opskins provider through composer

## Actual behavior:
Error:
[InvalidArgumentException]                                                                                                                                                                                                    
  Could not find a matching version of package socialiteproviders/opskins. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

## Steps to reproduce the behavior:
composer require socialiteproviders/opskins

## Proposed solution:
Fix this issue :-)

**Comment by atymic** [comment]
Is this still an issue?

**Comment by atymic** [comment]
Opskins no longer exists it seems.
