### ISSUE TITLE
Audit and deprecate broken/dead providers

### ISSUE THREAD

**Issue by atymic** [SocialiteProviders/Providers#488]
Archive & deprecate dead providers.

Pending actions

Abandon on packagist:

- [x] https://packagist.org/packages/socialiteproviders/everyplay
- [x] https://packagist.org/packages/socialiteproviders/mixer
- [x] https://packagist.org/packages/socialiteproviders/gamewisp
- [x] https://packagist.org/packages/socialiteproviders/dailymile
- [x] https://packagist.org/packages/socialiteproviders/rdio
- [x] https://packagist.org/packages/socialiteproviders/jawbone
- [x] https://packagist.org/packages/socialiteproviders/hitbox

**Comment by lucasmichot** [comment]
Also abandon https://packagist.org/packages/socialiteproviders/rdio

**Comment by atymic** [comment]
Hey @m1guelpf 

Could you mark the above packages as abandoned on packagist please?
I don't have the perms to do so.

**Comment by m1guelpf** [comment]
@atymic Done!

**Comment by atymic** [comment]
Thanks a ton @m1guelpf :)

**Comment by atymic** [comment]
Also this provider if you have chance @m1guelpf 
https://packagist.org/packages/socialiteproviders/moikrug
