### ISSUE TITLE
[discussion] Extend documentation

### ISSUE THREAD

**Issue by saundefined** [SocialiteProviders/Providers#506]
Maybe add to the documentation information about where and how to register an OAuth application for authorization and a link to the documentation (if exists)?

**Comment by atymic** [comment]
Feel free to PR this to the new docs (in each provider's src folder)

**Comment by saundefined** [comment]
@atymic, the docgen.php will not overwrite these changes?
Or is it just for the initial doc gen?

**Comment by atymic** [comment]
It's just for the first generation, it doesn't overwrite once they exist :)
