### ISSUE TITLE
LinkedIn Provider

### ISSUE THREAD

**Issue by wislem** [SocialiteProviders/Providers#51]
Hello everyone!

I have been struggling to retrieve some more fields from the r_basicprofile scope (summary, specialties, positions).

In this provider, there is no configuration for the fields to request and changing them in the code made no difference.
https://github.com/SocialiteProviders/Providers/blob/master/src/LinkedIn/Provider.php line 96
```
        $response = $this->getHttpClient()->get(
            'https://api.linkedin.com/v1/people/~:(id,first-name,last-name,formatted-name,summary,specialties,email-address,headline,location,industry,positions,public-profile-url,picture-url,picture-urls::(original)', [
            'headers' => [
                'Accept-Language' => 'en-US',
                'x-li-format' => 'json',
                'Authorization' => 'Bearer '.$token,
            ],
        ]);
```

To get those fields, I had to mess with Socialite's official LinkedIn Provider
https://github.com/laravel/socialite/blob/3.0/src/Two/LinkedInProvider.php line 28
```
    protected $fields = [
        'id', 'first-name', 'last-name', 'formatted-name', 'summary', 'specialties',
        'email-address', 'headline', 'location', 'industry', 'positions',
        'public-profile-url', 'picture-url', 'picture-urls::(original)',
    ];
```

Is there any way to configure the fields to be requested?

Thank you in advance!

**Comment by faustbrian** [comment]
Socialite is supposed to only provide the basic details and login in the user. If you need to perform more actions use the token you receive from the response and perform another request to retrieve additional informations.
