### ISSUE TITLE
Undefined index: email with mailru provider

### ISSUE THREAD

**Issue by matro-skin** [SocialiteProviders/Providers#515]
Callback route return `Undefined index: email` error:
https://flareapp.io/share/W7z0vVmw#F49

Laravel version 7.23.0
PHP version 7.3.17

**Comment by atymic** [comment]
Hey @matro-skin 

Can you post the response/structure of the returned data? I can't find the docs and can't read russian.

**Comment by matro-skin** [comment]
Looks like it's resolved with last update up to v4.0

**Comment by atymic** [comment]
No worries :)
