### ISSUE TITLE
Steam Provider has errors due to miss match config variables

### ISSUE THREAD

**Issue by dreamgeekcoder** [SocialiteProviders/Providers#527]
The steam provider doesn't work correctly and has multiple errors. I eventually fixed them, but I don't exactly know how to do a fix request because there are a few including the documentation needs updating... and i'm new.. BUT anyway.. 

The main issues are.. 

1) Steam only uses SECRET CLIENT .. there is no client ID. (https://steamcommunity.com/dev/apikey)
2) The code is currently looking for api_key on lines 114, 119 and 309 of /socialiteproviders/steam/provider.php and it doesn't exist in config as a variable

So to fix... 

1) Documentation needs to be update to show this addition to services.php on installation (https://github.com/SocialiteProviders/Steam and https://socialiteproviders.com/Steam/)

'steam' => [
        'client_id' => null,
        'client_secret' => env('STEAM_CLIENT_SECRET'),
        'redirect' => env('STEAM_REDIRECT_URI'),
    ],

Not this as it currently shows;

'steam' => [    
  'client_id' => env('STEAM_CLIENT_ID'),  
  'client_secret' => env('STEAM_CLIENT_SECRET'),  
  'redirect' => env('STEAM_REDIRECT_URI') 
],

2) All mentions to api_key.php (lines 114, 119 and 309 of /socialiteproviders/steam/provider.php) need to be changed to 'client_secret'.

and ENV need to be shown as this 

// https://steamcommunity.com/dev/apikey
STEAM_CLIENT_SECRET=YOURKEY
STEAM_REDIRECT_URI=https://www. YOURURL.com

Then everything will work as expected.

Like i said i'm new and not exactly sure how to submit the fix for this... Or maybe there is a different one.. 

I've had this open for several hours while I did troubleshooting and finally fixed it myself.. so figured I would share and hopefully save that from someone else.

**Comment by dreamgeekcoder** [comment]
I think i figure out how to do the pull request... :) First time

**Comment by atymic** [comment]
We moved the docs over and some of the edited bits were lost. Thanks, for the PR. I think if you configured the `api_key` it should work. I think just changing the docs makes sense here, sorry about the time spent debugging!
