### ISSUE TITLE
Return scopes for google provider

### ISSUE THREAD

**Issue by ggolda** [SocialiteProviders/Providers#533]
Google OAuth api returns a string that contains a list of scopes that user gave access to. Is there a way to add them to google socialite provider?

https://socialiteproviders.com/Google-Plus/

**Comment by atymic** [comment]
Sure, feel free to PR :)

**Comment by robiiinos** [comment]
Hello, can you provide us the docs where you think they return the list of scopes?

Currently, Google is returning https://developers.google.com/identity/protocols/oauth2/openid-connect#an-id-tokens-payload and I do not see any list of scopes.
