### ISSUE TITLE
apple redirect uri is sending back a http post request?!!

### ISSUE THREAD

**Issue by Xoshbin** [SocialiteProviders/Providers#537]
Hi, I just started using this package + the apple provider, to implement sign in with apple button on my website, but I'm receiving a 419 error when apple is redirecting back to my website, because apple redirect uri is a http POST request as [described here](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple#3331292:~:text=and%20sends%20an%20HTTP%20POST%20request,to%20the%20URL%20provided%20in%20redirectURI.). and as we all know Laravel is not accepting http Post requests without CSRF token. so is there any solution please? or I'm doing something wrong?

**Comment by atymic** [comment]
See https://laravel.com/docs/7.x/csrf#csrf-excluding-uris\

Should also add to the docs 👍 
Feel free to PR

**Comment by vonec** [comment]
Apples implementation is a little different from the rest of the social login providers, the socialite provider documentation was changed recently as part of normalizing all socialite providers. we need to rework on Socialite Apple documentation.

**Comment by rushairer** [comment]
If skip CSRF and post callback, Auth:user() is null.
So, when I have had an account, and logined, connect apple, will not create a connected_accounts record.
