### ISSUE TITLE
How to logout in Youtube provider?

### ISSUE THREAD

**Issue by amcsi** [SocialiteProviders/Providers#543]
I'm stuck in a loop where I login with Google for Youtube, but with a Google account that doesn't have a Youtube channel.

Thus in the callback when I do `Socialite::driver('youtube')->user()`, because I get an ErrorException thrown for this line in the library code: `return json_decode($response->getBody()->getContents(), true)['items'][0];`.

I thought that what I could do was catch that exception, and in that case take the user back to the login page...

...**but** when the user would click on the login button again, they'd automatically get logged in by the same user that didn't work, rather than get a chance to log in as a different Google user.

So how am I supposed to make it so the user could choose a different user to log in as from Google?

**Comment by robiiinos** [comment]
Havent' tested it, but you can follow these guidelines from Google: https://developers.google.com/identity/protocols/oauth2/openid-connect#re-consent
And add an additional config to the provider like this:

```php
$additionalProviderConfig = ['prompt' => 'select_account'];
```

**Comment by atymic** [comment]
Thanks @robiiinos  👍
