### ISSUE TITLE
Question : is there interest in supporting CAS (Central Authentication Service) protocol & providers ?

### ISSUE THREAD

**Issue by abejenaru** [SocialiteProviders/Providers#544]
CAS is a different protocol than OAuth, so new adapters are needed.
Just an inquiry, thanks!

**Comment by atymic** [comment]
Could you link to the docs? We already have some non openid providers like steam and apple.

**Comment by abejenaru** [comment]
Hi, it's mainly used in education and enterprise environments, so I couldn't find public servers for testing, only mock-up server implementations.

Here is the protocol documentation: https://apereo.github.io/cas/6.2.x/protocol/CAS-Protocol.html
There is also an official PHP client: https://github.com/apereo/phpCAS
Some mock-up implementation (which I did not use): https://github.com/veo-labs/cas-server-mock or https://github.com/pfrenssen/cas_mock_server

Thanks!

**Comment by atymic** [comment]
Ahh. This repo is more focused on providing drivers for public services. 
Maybe not the best fit in that case?
