### ISSUE TITLE
[QUESTION] Using Socialite to auth against adAS (prise) service

### ISSUE THREAD

**Issue by pacoorozco** [SocialiteProviders/Providers#545]
Hi!
I know that this repo is focused in giving providers for public services, but my university's SSO is an [adAS service](http://www.adas-sso.com/en/) from Prise. They offer SSO using OAuth2, so I'd like to create a provider that allows me use this service to auth my Laravel app. 

I've created a provider for this adAS service, basically the one that the [generator](https://github.com/SocialiteProviders/Generators) did. If it's not published in this repo, **how can use it on my laravel app?**

Thanks in advance

**Comment by atymic** [comment]
Since you don't actually need to share it, you can just create the classes using the generator in your application. 
Then, follow the steps for any provider but instead reference your local socialite provider classes.
