### ISSUE TITLE
Untappd provider not working using the documentation step-by-step

### ISSUE THREAD

**Issue by kidh0** [SocialiteProviders/Providers#548]
Hello there.
I recently upgrade to laravel 8 and tried to get my application working with the untappd provider with no success.
My composer.json looks like the follow:
` "require": {
        "php": "^7.2.5",
        "doctrine/dbal": "^2.9",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/socialite": "^5.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "laravelcollective/html": "^6",
        "socialiteproviders/untappd": "^1.0"
    },`

For some unknown reason the file `vendor/socialiteproviders/untappd/Provider.php` is not update with the current master version and it is breaking the application. I had to manually upgrade the file to use the new `Arr::get` method instead of `array_get`. 

Is there any workaround?

**Comment by atymic** [comment]
I have just tagged a new version, could you give that a go?
https://github.com/SocialiteProviders/Untappd/releases/tag/v3.0.0

**Comment by kidh0** [comment]
Fixing the version to `^3.0` worked like charm. But I think that if you just do a `composer require socialiteproviders/untappd` it will install the `1.0.0`. I done it like 15 minutes ago :/

**Comment by atymic** [comment]
It should pick up the v3.0.0 for new installs (unless there's other issue forcing v1)
