### ISSUE TITLE
Call to undefined method SocialiteProviders\Spotify\Provider::getAccessTokenResponse()

### ISSUE THREAD

**Issue by marco-peters** [SocialiteProviders/Providers#55]
I'm getting the following error on the callback of the Spotify provider:

`Call to undefined method SocialiteProviders\Spotify\Provider::getAccessTokenResponse()`

I'm on Laravel 5.4, might that be an issue? However, I'm using Laravel Socialite 3.0.0, which should be compatible.

**Comment by sigfriedseldeslachts** [comment]
I've got the same issue on the YouTube one.

**Comment by faustbrian** [comment]
https://github.com/laravel/socialite/blob/3.0/src/Two/AbstractProvider.php#L252-L268
