### ISSUE TITLE
A bug fix is needed for Telegram provider

### ISSUE THREAD

**Issue by Altair4713** [SocialiteProviders/Providers#555]
The Telegram provider has a bug that prevents users who do not have a last name from logging in. If it is not there, then the script crashes with an error. I forked the repository for myself, but I would like the bug to be fixed in the official version. Is it possible?

Here's the fix https://github.com/Altair4713/Telegram/commit/8755269312d91534de6058323d6fdebf0faf97f8#diff-3c2c7bc87589e022ac1cdaf01268b250cd8456756927542cb2c58c67e67cf33f

**Comment by atymic** [comment]
Yep, just PR it against the correct file in this repo:

https://github.com/SocialiteProviders/Providers/blob/master/src/Telegram/Provider.php

```
$name = trim(sprinf('%s %s', $user['first_name'] ?? '', $user['last_name']))

return (new User())->setRaw($user)->map([
            'id'        => $user['id'],
            'nickname'  => $user['username'],
            'name'      => !empty($name) ? $name : null,
            'avatar'    => $user['photo_url'],
        ]);
```
