### ISSUE TITLE
Website is hacked / SSL invalid

### ISSUE THREAD

**Issue by dillingham** [SocialiteProviders/Providers#559]

**Comment by atymic** [comment]
Seems fine to me?

![image](https://user-images.githubusercontent.com/50683531/96388119-83725c80-11f2-11eb-8cbc-b8044b143121.png)

**Comment by dillingham** [comment]
@atymic i got an ssl chrome error and my isp said it detected it was insecure but after I proceeded and checked the cert seems fine 🤷‍♂️ so I closed this
