### ISSUE TITLE
Google Provider - 401 Invalid Client / Unauthorized

### ISSUE THREAD

**Issue by makesolutions-fl** [SocialiteProviders/Providers#564]
Hello there, 

when i try to authenticate via the google provider everything works fine until the callback. 
I dumped the response and I get the following error: 

`Client error: `POST https://oauth2.googleapis.com/token` resulted in a `401 Unauthorized` response: { "error": "invalid_client", "error_description": "Unauthorized" }`

I've tried almost everything, created a new project, fill everything out, added google+ and gmail as API library...

I also used the Laravel Socialite standard google provider for a test, same error, other token url. 
The CLIENT_ID and CLIENT_PASSWORD is 100% correct. No whitespaces or anything else...

Do you have a hint for me? 

Thanks in advance, 
sincerely, 
MN

**Comment by atymic** [comment]
Did you request the offline access scope?

**Comment by SaburovBabur** [comment]
Make sure to have Google+ API  **enabled** Please use Google Developers Console to activate the API for your project. There might be some issues on activating as it says error is on your client_id. It is either not activated or given with " ". So .env make it without any " ". 
Or check the google project name and product name the **Must be same**. If you find something difficult i will advice to create a new Web-Oauth client, cause it is not the issue of this package.

**Comment by Andrew-Pynch** [comment]
> Make sure to have Google+ API **enabled** Please use Google Developers Console to activate the API for your project. There might be some issues on activating as it says error is on your client_id. It is either not activated or given with " ". So .env make it without any " ". Or check the google project name and product name the **Must be same**. If you find something difficult i will advice to create a new Web-Oauth client, cause it is not the issue of this package.

Dude this fixed my issue thank you so much!
