### ISSUE TITLE
Version issues with new 4.0.0

### ISSUE THREAD

**Issue by LorenzoSapora** [SocialiteProviders/Providers#575]
Thanks for all your work here, truly the unsung hero of the Laravel ecosystem.

Some packages already had a v4, and even v5's. The twitch package for example. Now composer is getting confused between `v4.0.0` and `4.0.0`. And what happens when we get to 5.0, 5.1, and 5.2 in the future?

For future issue-splunkers, you can avoid the composer issues by either using `"*"` or `"dev-master"`, as your version. This isn't optimal, but will just use the most recent instead of a version number

**Comment by atymic** [comment]
Oops, there was a check in the script that should have caught that so sorry.
I'll release a version now.

https://github.com/SocialiteProviders/Providers/blob/master/tools/release-major-version.php#L33-L35

**Comment by atymic** [comment]
I've tagged 5.3.0 and removed the bugged version. Sorry, not sure what went wrong there!

**Comment by LorenzoSapora** [comment]
Not a problem :) thanks for the fix
