### ISSUE TITLE
Packagist vkontakte problem

### ISSUE THREAD

**Issue by NikolayGrishchenko** [SocialiteProviders/Providers#577]
Нужно обновить зависимости в composer.json в packagist
https://github.com/SocialiteProviders/VKontakte/blob/master/composer.json - "socialiteproviders/manager": "~4.0"
https://packagist.org/packages/socialiteproviders/vkontakte#v4.1.0 - socialiteproviders/manager: ~2.0 || ~3.0

**Comment by atymic** [comment]
Fixed :)
https://packagist.org/packages/socialiteproviders/vkontakte#4.2.0
