### ISSUE TITLE
Can this be upgraded to work with Guzzle v7?

### ISSUE THREAD

**Issue by pdolinaj** [SocialiteProviders/Providers#578]
I am using latest version of Laravel 8 with Guzzle v7 but this package supports only Guzzle v6. Is there a plan to have this upgraded to Guzzle v7 in near future? Thank you.

**Comment by atymic** [comment]
Which Provider are you having issues with. Can you post the output of composer/errors?

**Comment by pdolinaj** [comment]
FITBIT is still using Guzzle V7.

composer.json
`"require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/passport": "^10.0",
        "laravel/socialite": "^5.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "sentry/sentry-laravel": "^2.1",
        "socialiteproviders/fitbit": "^4.0",
        "socialiteproviders/garmin-connect": "^4.0",
        "socialiteproviders/strava": "^4.0"
    },`

Socialite FITBIT error from callback method: `$user = Socialite::driver('fitbit')->user();`

`
Error Undefined class constant 'VERSION''
SocialiteProviders\Fitbit\Provider::getAccessTokenResponse
vendor/socialiteproviders/fitbit/Provider.php:47
`

`public function getAccessTokenResponse($code)
    {
        $postKey = (version_compare(ClientInterface::VERSION, '6') === 1) ? 'form_params' : 'body';
...
    }`

The **ClientInterface::VERSION** has been removed as per : https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

`Constant GuzzleHttp\ClientInterface::VERSION is removed. Added GuzzleHttp\ClientInterface::MAJOR_VERSION instead.`

**Comment by atymic** [comment]
Thanks, will tag a new release shortly.
