### ISSUE TITLE
can not install:  Could not find a matching version of package socialiteproviders/thirtysevensignals.

### ISSUE THREAD

**Issue by nekromoff** [SocialiteProviders/Providers#580]
composer require socialiteproviders/thirtysevensignals
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2

In InitCommand.php line 727:
                                                                                                                                                 
  Could not find a matching version of package socialiteproviders/thirtysevensignals. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by nekromoff** [comment]
so apparently it is now "/37signals" contrary to what docs say

**Comment by atymic** [comment]
Could you please link the docs where it's incorrect or send an update PR please?

**Comment by nekromoff** [comment]
https://github.com/SocialiteProviders/Providers/tree/master/src/ThirtySevenSignals

**Comment by atymic** [comment]
Closed in https://github.com/SocialiteProviders/Providers/commit/d5fc3762131a12dd14fc1df684904d5db046e7b7

Thanks!
