### ISSUE TITLE
Minecraft OAuth

### ISSUE THREAD

**Issue by FoksVHox** [SocialiteProviders/Providers#585]
Hi!

I would love to see support for Minecraft Authentication for this. 

Usecase: 
To manage players through a custom shop system
To link an MC account with another OAuth service like Steam

**Comment by atymic** [comment]
Feel free to make a PR :)

**Comment by FoksVHox** [comment]
> Feel free to make a PR :)

I would gladly do, but I have next to nothing experience with creating packages

**Comment by atymic** [comment]
Take a look at the guide here
https://socialiteproviders.com/contribute/ 

Feel free to PR wherever you get to and I'll help out :)

**Comment by Katzen48** [comment]
I created a provider for this.
Pull request just needs to be accepted.
