### ISSUE TITLE
Upgrade Apple Provider dependency for full PHP 8 support

### ISSUE THREAD

**Issue by nea** [SocialiteProviders/Providers#587]
Ahoi

I just upgraded everything to fool around with PHP 8 and I jumped into a dependency clash to fully be able to upgrade.

The Apple Provider requires `lcobucci/jwt` in version ^3.3, but PHP 8 support was only added to ^4.0 (https://github.com/lcobucci/jwt/releases/tag/4.0.0). 

Would you be able to apply that dependency allowance/requirement, too?

Thanks a lot in advance

**Comment by atymic** [comment]
Feel free to PR :)

**Comment by Iamscaredofcode** [comment]
what's missing here? there seem to be so many posts on this and I have lost the overview what needs to be done to make this work
