### ISSUE TITLE
Php8 dependency on version 4.0 was not updated properly in packagist

### ISSUE THREAD

**Issue by kkame** [SocialiteProviders/Providers#588]
The source was modified normally, but the dependencies managed by packagist were not properly modified.

In packagist, version 4.0 has the following dependencies:

requires
php: ^7.2

Also, the convention of version tagging is different from before.

v3.x.x -> 4.0.0

**Comment by atymic** [comment]
What provider is this for?

**Comment by kkame** [comment]
<img width="488" alt="Screen Shot 2020-11-30 at 3 09 35 PM" src="https://user-images.githubusercontent.com/4939813/100574765-10462500-331e-11eb-93c1-988b203047f1.png">

We checked based on slack, and it was confirmed that other providers are the same.

**Comment by atymic** [comment]
Tagged as 4.1
https://github.com/SocialiteProviders/Slack/tree/4.1.0
