### ISSUE TITLE
Please tag a new release for the Microsoft-Azure provider

### ISSUE THREAD

**Issue by litan1106** [SocialiteProviders/Providers#591]
https://github.com/SocialiteProviders/Microsoft-Azure/commit/7808764f777a01df88be9ca6b14d683e50aaf88a

**Comment by atymic** [comment]
Coming shortly 👍 
Takes a while to release 100 or so packages 📦

**Comment by DarrenChowles** [comment]
Sorry for hijacking this @atymic, but is there a reason the Azure provider shows as deprecated on https://socialiteproviders.com/Microsoft-Azure/? I might need to use it soon. The website says it's deprecated but it seems to be in active development here?

**Comment by atymic** [comment]
My understanding is that you should use the microsoft graph provider, as they are exactly the same. If this is wrong, let me know and I'll fix it.

**Comment by DarrenChowles** [comment]
> My understanding is that you should use the microsoft graph provider, as they are exactly the same. If this is wrong, let me know and I'll fix it.

Ah, I see the Microsoft provider is the way to go, thank you!

**Comment by johnwc** [comment]
@atymic The MS Azure provider needs to be revived, as Microsoft accounts are not the same as Microsoft Azure accounts. If you use the Azure AD oAuth, you will notice there is a tenant section of the authorization url. The Microsoft oAuth is for logging in with "Microsoft" accounts.

**Comment by atymic** [comment]
I will untag it as deprecated, thanks 👍
