### ISSUE TITLE
Twitter OAuth now throwing error

### ISSUE THREAD

**Issue by Murked** [SocialiteProviders/Providers#607]
Hello, not sure what happened because this was working fine last week, but i now get this error when i hit the login endpoint:

https://flareapp.io/share/LPlA9yB7#F53

I guess this was caused by an update on my end when i reinstalled my local environment & got a newer PHP version? I have tried to update the twitter package for 8.0 support, but its just throwing me this error each time: https://gyazo.com/1cd32513d47f6407a65b789fba15edd0

EDIT: I have ran `composer update` & have installed the recent updates, but still getting the same problem.

Sorry if it sounds stupid, but I've never encountered a lock like this & im not 100% sure how to solve it, any help would be appreciated. Thanks!

**Comment by TomWhitson** [comment]
Same here, changing line 105 of vendor\socialiteproviders\twitter\Server.php to,

public function getAuthorizationUrl($temporaryIdentifier, array $options = [])

fixes the issue (until the package is updated)

**Comment by atymic** [comment]
It was actually fixed, but forgot to tag a release. Give it a try now.

**Comment by atymic** [comment]
Closing this, feel free to ping if you have any issues.
