### ISSUE TITLE
Call to undefined method SocialiteProviders\Telegram\Provider::getScript()

### ISSUE THREAD

**Issue by robertnicjoo** [SocialiteProviders/Providers#611]
When I add

```php
{!! Socialite::driver('telegram')->getScript() !!}
```
Based on [documentation](https://socialiteproviders.com/Telegram/#configuration), I get this error:

```
Call to undefined method SocialiteProviders\Telegram\Provider::getScript()
```

But If I use

```php
{!! Socialite::with('telegram')->redirect() !!}
```
It will show login button, however it will not follow callback route.

**Any suggestions?**

**Comment by atymic** [comment]
Looks like correct method is:
https://github.com/SocialiteProviders/Providers/blob/master/src/Telegram/Provider.php#L51

`getButton`

Could you try?

**Comment by ZBrettonYe** [comment]
Base on my research, this package is maintain by Max13. here is his code about telegram socialite.
https://github.com/Max13/TelegramSocialite

In this version, it does include all the code, the document mentioned.
