### ISSUE TITLE
OpenID Connect Possible with Socialite Providers?

### ISSUE THREAD

**Issue by orware** [SocialiteProviders/Providers#619]
Good afternoon,

I spent a bit of time this weekend trying my hand at creating my own Socialite Provider to try and integrate with the SSO software we utilize at a number of community colleges here in California (the software is from a company from the East coast however and is named PortalGuard).

PortalGuard supports multiple SSO protocols: CAS, SAML 2.0, and also OpenID Connect.

As I have been trying to wrap my head around what to utilize for my projects moving forward, I started reading up on Socialite and thought it might be worth a try experimenting with creating my own provider for PortalGuard (since after reviewing the other providers it seemed like everything in place with PortalGuard's OpenID Connect support should allow me to get things working...especially since a few months ago I was able to get the open source Kanboard project authenticating with its OAuth2 Provider and PortalGuard).

The main error I've been receiving has been the following one on my end:
```
Client error: `POST https://idp.example.com/oauth/v2/token` resulted in a `400 Bad Request` response: Bad Request
```

If I try with the stateless option instead it resulted in a different error, but the stateful approach seemed to be the better overall option.

I wasn't able to get it up and running though and wasn't sure exactly where the problem was.

As far as OpenID Connect goes, there's an older Laravel piece that seems like it might use Socialite a bit (last update is from 2017 however and the repo is archived currently):
https://github.com/furdarius/oidconnect-laravel

There's a different OpenID type client here that's had more recent updates (but doesn't seem to target OpenID Connect specifically):
https://github.com/univicosa/laravel-openid-client

There's a general PHP OpenID Connect Library available here that's also had recent updates (I experimented with this one a little bit, but it wasn't an option I wasn't able to get quickly up and running either):
https://github.com/jumbojett/OpenID-Connect-PHP

At the moment, for SSO the protocol I've had the most success with has been CAS (via https://github.com/subfission/cas) but an option utilizing Socialite underneath the hood seemed like it might be a little more future proof / integrated into the normal Laravel capabilities, but that's a completely different protocol so wouldn't be something I could use with Socialite.

Any thoughts on whether an Identity Provider (PortalGuard in this case) that supports OpenID Connect can be used with Socialite correctly if a Provider is created for it? (At the moment I'm under the assumption that there's something wrong with the Provider class I put together, but since debugging details were slim it was difficult to say for sure).

Any thoughts on being able to troubleshoot the new Provider more effectively? (I do have a bit of insight into the requests in the PortalGuard logs on that end and share the following additional info).

Following the Socialite instructions, I added the following two routes on my end:

```
Route::get('/auth/redirect', function () {
    //return Socialite::driver('portalguard')->stateless()->redirect();
    return Socialite::driver('portalguard')->redirect();
});

Route::get('/auth/callback', function () {
    $user = Socialite::driver('portalguard')->stateless()->user();
    //$user = Socialite::driver('portalguard')->user();
    // $user->token
});
```

Primarily, I've been attempting to access the `/auth/callback` endpoint which I'm assuming should trigger a login flow on its own, but I never get to the PortalGuard login page. However, it does mark down some items in its log, including the following line:

```
2021-Jan-18 18:40:55.861919 [0x00001960] (i) IdPAgentOAuthToken::handleRequest(): Request _1234567891234567891234567891234 was missing code parameter
```

And I was looking at the Socialite code to try and understand where that `code` parameter comes from and it seems to come from the `redirect()` action, but I'm not sure why it's not being triggered automatically behind the scenes (or however it is supposed to work).

If I attempt to access the `/auth/redirect` endpoint directly first, it does correctly redirect me over to the PortalGuard Login page, and then I'm able to login, but then it seems to get stuck in a redirect loop alternating between these two requests primarily:

```
/oauth/v2/authz?client_id=987654321987654321987654&redirect_uri=http%3A%2F%2Fsocialite.test%2Fauth%2Fredirect&scope=openid+email&response_type=code&response_mode=form_post
http://socialite.test/auth/redirect?code=RANDOMLY-GENERATED-CODE
```

Thank you for any tips/insight you might be able to share!

**Comment by 27pchrisl** [comment]
@orware I recently submitted https://github.com/SocialiteProviders/Providers/pull/612 for SAML 2.0 support, maybe this would help with the PortalGuard integration?

**Comment by orware** [comment]
@27pchrisl thanks for sharing that PR link, that definitely seems like another good option I could potentially utilize with PortalGuard :-).

Since it's still being processed as a PR, what would be the best way to attempt to bring in that Provider easily at the moment via composer? I'd be happy to give it a try just to see if I can get something working using it.

Overall, something that's still a bit confusing at the moment is how much additional work is still needed when using Socialite for adding the data coming in from SSO into the Laravel User's table (the older Laracasts video on the topic covers some of that...but at the same time I'm not sure if the newer versions of Socialite take care of that automatically...basically what I'm aiming for is a long-term method of being able to use one of our available SSO options that PortalGuard is providing, but also have it nicely integrated into the normal Laravel functionality, and part of that puzzle would include having the custom attributes we'd like to send back into Laravel to be brought in and saved automatically in the Users table).

One other note I noticed in your PR that you mentioned was the need for making your site publicly accessible it seems for completing the SAML tests...this is something I've been wondering about if it's a true requirement or not (e.g. it doesn't seem to be for my CAS authentication tests, since I have my site running only locally from home, but I have the URL I'm using allowed through the connection setup within PortalGuard...I think I've been able to do the same with SAML as well in the past for a different project, but it's been a while so I don't remember at the moment...same goes for OpenID Connect, but that was also a few months back already now too so the details are fuzzy regarding whether or not I had that working fine via my local server during development). Also, I tend to not be fully sure of how to fill in the certificate information (in the case of SAML, our Metadata does include the X509 section in it, which I believe would be the same as our Public Certificate...would that be the value I plug in for the SAML configuration?).

**Comment by 27pchrisl** [comment]
To try it locally:

- Clone https://github.com/flat3/Providers/tree/saml2
- Modify the composer.json of your app to add this key at the top level
```
"repositories": [
        {
            "type": "path",
            "url": "../Providers/src/Saml2" // Or wherever the path to this is
        }
    ]
```
- Add `"socialiteproviders/saml2": "*"` to the require block
- Do `composer install`

Socialite doesn't help you with creating the user locally in your database or pushing the id of the user into the session (as far as I know), you still have to do those bits as part of the callback route by transferring the relevant data from the Socialite User object into your user object.

You're right that like CAS there's no need for the SAML IDP and SP to communicate directly. However making the site publically accessible is the easiest way to test that the metadata is fetchable from the SP and parsable by the IDP. If PortalGuard can provide you metadata as an XML file, you can pass that XML directly into the config (https://github.com/flat3/Providers/blob/saml2/src/Saml2/README.md#using-an-identity-provider-metadata-xml-file)

**Comment by orware** [comment]
@27pchrisl Thanks for the extra details Chris! That'll be helpful for me to try giving it a shot here on my end :-).

That's a bummer that the actual adding of the user locally into the database / session stuff isn't really being handled by Socialite though, since on the surface that seemed like it might be the case, maybe because I was looking at Passport initially? (I think that's one of my criticisms for Laravel, since on the one hand it seems to have a lot of batteries included, but on the same note, there can be quite a bit that may need to be implemented on one's own, and as a relative newcomer to building stuff with the framework, it's been hard wrapping my head around the pieces I'll need to come up with on my own, which adds its own set of challenges/delays, versus what will be done automatically...or at least be somewhat guided/simple ;-)).

**Comment by atymic** [comment]
@27pchrisl since the saml2 provider was accepted, is this issue able to be closed?
https://github.com/SocialiteProviders/Providers/pull/612

**Comment by 27pchrisl** [comment]
@atymic It answers the question about PortalGuard, so I think yes?

**Comment by orware** [comment]
Thanks for the updates on this one! If SAML2 is now possible via (https://github.com/SocialiteProviders/Saml2) then I should be able to give that one a fresh try now and see if I can get SAML2 working that way moving forward and then integrate into a future project :-). 

I've still been using the (https://github.com/subfission/cas) package in recent months as an SSO option for myself that was workable as a starting point but this SAML2 option may end up being better moving forward.

**Comment by orware** [comment]
In a quick read through of the https://github.com/SocialiteProviders/Saml2 README just now, probably the only extra suggestion might be to have an example of the CSRF middleware exclusion mentioned that's being needed to support the HTTP POST option rather than the HTTP Redirect option that's the default (at the moment I'm not sure if PortalGuard supports HTTP Redirect or not...but I do know most of the integrations I've made have used the POST option...I'll have to try and give both a try though and see what works and what doesn't...I'll add an issue over in that repo though if I encounter any specific issues related to that provider once I've had an opportunity to run through some tests with it and PortalGuard).

**Comment by atymic** [comment]
Feel free to PR to update the dcos @orware  :)
