### ISSUE TITLE
Mastodon Support

### ISSUE THREAD

**Issue by crscheid** [SocialiteProviders/Providers#62]
It would be nice to have a Mastodon Socialite provider that also allows the ability to pass in which instance you are attempted to authenticate to, since the instances are distributed.

**Comment by faustbrian** [comment]
Send a PR.

**Comment by ahangarha** [comment]
I don't see Mastodon in the list of providers in [documentation](https://socialiteproviders.com/). Couldn't find the mentioned PR as well.
