### ISSUE TITLE
No refreshToken from Microsoft-Graph Provider

### ISSUE THREAD

**Issue by lordisp** [SocialiteProviders/Providers#624]
May there be an option to retrieve an `refreshToken` somehow? I would Use the Azure Provider but I need to use Azure Resource Manager provider APIs use the request URI `https://management.azure.com`

**Comment by atymic** [comment]
You should be able to get the refresh token directly from the user object, even if it isn't a default key. 

Are you requesting the `offline_access` scope?

**Comment by lordisp** [comment]
I missed the `offline_access` bit. No I'm receiving the refresh token. cheers!
