### ISSUE TITLE
Keycloak socialite returns missing parameter: code on callback

### ISSUE THREAD

**Issue by Jonskadev** [SocialiteProviders/Providers#625]
Greetings, I have been trying to use keycloak login on laravel-lumen service, but It only returns this:

![imagen](https://user-images.githubusercontent.com/9122377/106676885-7fe2c580-6596-11eb-9639-c9a2e266cb0b.png)

I have verified with another keycloak service and it works so it may be a keycloak version problem?

I have keycloak 12.0.2, other thing that it can be is a problem of client configuration but still I can't manage to use the browser login provided by keycloak, only thing that works is the token validation using the userFromToken method.

My login controller looks like this:
![imagen](https://user-images.githubusercontent.com/9122377/106677182-131bfb00-6597-11eb-80d0-8b234e956e3d.png)
Since I'm using lumen, I'm trying to use the browser login for testing purposes.

**Comment by atymic** [comment]
Looks like invalid scope error?
![image](https://user-images.githubusercontent.com/50683531/106693486-b407c600-662a-11eb-8e48-122cae7b571d.png)

From your code sample you are using the default scopes, which is nothing

**Comment by Jonskadev** [comment]
My bad, it works now adding the openid scope, for some reason on older versions of keycloak, it doesn't ask for this scope.

![imagen](https://user-images.githubusercontent.com/9122377/112586850-4a5e9980-8ddb-11eb-8a1f-a0af356eaa02.png)

**Comment by atymic** [comment]
Could you make a PR to the docs to update it please?
