### ISSUE TITLE
Error about SocialiteProviders\Twitter when run composer install

### ISSUE THREAD

**Issue by khacnha** [SocialiteProviders/Providers#627]
We used:
"laravel/socialite": "^5.1",
"socialiteproviders/twitter": "^3.0"
When run `composer install` with other package, it show error relate Twitter:
![image](https://user-images.githubusercontent.com/20592123/107009036-139ad880-67c7-11eb-8602-169c3ff7221a.png)

Any update?

**Comment by atymic** [comment]
Use the latest version
https://github.com/SocialiteProviders/Twitter/releases
