### ISSUE TITLE
[Apple] Don't JSON-decode user from request if it's already an array

### ISSUE THREAD

**Issue by thtg88** [SocialiteProviders/Providers#643]
I'm currently using the Apple provider for social login from a mobile app, which communicates with a Laravel API at the back-end. The app authenticates with Apple first, and I verify with Apple (with Socialite) that the app is sending valid IDs and name, before persisting the state in a DB.

I'm facing an issue whereas at https://github.com/SocialiteProviders/Providers/blob/master/src/Apple/Provider.php#L205 the `user` is already a JSON-decoded associative array, which makes Socialite crash at that line with an error `Array to string conversion`

I was wondering if you'd be open for a PR that checks that the `user` coming through is an array before casting, happy to open it if you guys think it can help.

Apologies if this is not the right place to open, I'm not very good at OAuth in general 😓

**Comment by atymic** [comment]
No worries, open a PR :)

Thanks!

**Comment by thtg88** [comment]
Thank you, I've opened a PR at #644, let me know if there's anything I can do for it :)
