### ISSUE TITLE
Facebook: Cannot call API for app {AppID} on behalf of user {UserID}

### ISSUE THREAD

**Issue by AshPowell** [SocialiteProviders/Providers#659]
Hi, 

I wonder if anyone could help debug what's the cause of this issue - it's happening a lot, but I cannot reproduce it.

The error is:
```
Client error: `POST https://graph.facebook.com/v3.3/oauth/access_token` resulted in a `400 Bad Request` response:
{"error":{"message":"Cannot call API for app {AppID} on behalf of user {UserID}","type":"OAuthException" (truncated...)
```

No matter what I try I cannot reproduce it, does anyone have an idea of what could cause it?

Thanks in advance

**Comment by atymic** [comment]
Did you try this?
https://stackoverflow.com/questions/56791689/unexpected-cannot-call-api-on-behalf-of-this-user-after-upgrading-to-graph-api

**Comment by atymic** [comment]
Closing as i don't think this is socialite related. Feel free to ping if it is.
