### ISSUE TITLE
Creating Custom Provider issues

### ISSUE THREAD

**Issue by Grasume** [SocialiteProviders/Providers#666]
Currently I keep getting The following error Messages.  Linking to my GitHub (https://github.com/Grasume/eveonline-socialite-provider) I tossed my code at but will put relevant parts here. 
![image](https://user-images.githubusercontent.com/16157418/114338433-ada93500-9b18-11eb-8d0e-4522b4e6742f.png)

App\Providers\EventServiceProvider.php
`  SocialiteProviders\Manager\SocialiteWasCalled::class => [
            'SocialiteProviders\Eveonline\EveonlineExtendSocialite@handle'
        ],`
App\Http\Controllers\DevLoginController.php
`class DevLoginController extends Controller
{
  public function redirectToProvider()
  {
      return Socialite::driver('eveonline')->redirect();
  }

  public function index(){
    return config('services.eveonline.org_number');
  }
}`
Config\app.php
`         'providers' => [
        SocialiteProviders\Manager\ServiceProvider::class,
        Laravel\Socialite\SocialiteServiceProvider::class,
        SocialiteProviders\Generators\GeneratorsServiceProvider::class,`
]
Code created by running php artisan make:socialite Eveonline --spec=oauth2 --author=YourName --email=your@name.com
SocialiteProviders\src\Eveonline\EveonlineExtendSocialite.php
`class EveonlineExtendSocialite
{
    /**
     * Register the provider.
     *
     * @param  \SocialiteProviders\Manager\SocialiteWasCalled $socialiteWasCalled
     */
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        $socialiteWasCalled->extendSocialite('eveonline', Provider::class);
    }
}`

**Comment by atymic** [comment]
I checked the repo, are you sure your provider is getting autoloaded? check by using `class_exists` function in your controller.

**Comment by Grasume** [comment]
I have ran the class_exists keeps telling me false and tried a couple things but cant seem to get the provider loaded

**Comment by Grasume** [comment]
Closing as solved the issue
