### ISSUE TITLE
Documentation issue for the SalesForce driver

### ISSUE THREAD

**Issue by nwoodhouse** [SocialiteProviders/Providers#670]
The documentation found here: https://socialiteproviders.com/SalesForce/#installation-basic-usage appears to have a small typo. It directs that the name of the driver configured in services.php should be:

'SalesForce'

However - this appears to result in a driver not supported error. Instead, the name of the driver ought to be:

'salesforce'

Should be a simple fix to update.

**Comment by atymic** [comment]
Feel free to PR :)

**Comment by nwoodhouse** [comment]
> Feel free to PR :)

Happy to - but I can't find the documentation repo any place :-/

**Comment by atymic** [comment]
> > Feel free to PR :)
> 
> Happy to - but I can't find the documentation repo any place :-/

It's in this repo :)
https://github.com/SocialiteProviders/Providers/blob/master/src/SalesForce/README.md

**Comment by nwoodhouse** [comment]
Done :-). My first pull request for an open source project - wahoo :-)

**Comment by atymic** [comment]
Closed in #671
