### ISSUE TITLE
Stripe - Undefined array key "email" when email is not returned in /v1/account call

### ISSUE THREAD

**Issue by franjohn21** [SocialiteProviders/Providers#681]
I'm using the Stripe provider and at least in local development in test mode I am able to see Stripe does not always return an email for the user. 

This is consistent with Stripe's documentation that the `email` field can be `null` for the `Account` object ([code](https://github.com/stripe/stripe-php/blob/master/lib/Account.php#L27)).

Because we hardcode `user["email"]` - the socialite provider throws an error in this case `Undefined array key "email"`. 

I can open up a pull request to fix this as it should be easy to make this optional. Just to confirm though - is this library production ready? I would figure something like this would have been seen already.

**Comment by atymic** [comment]
Tagged in https://github.com/SocialiteProviders/Stripe/releases/tag/4.1.1
