### ISSUE TITLE
How to logout ?

### ISSUE THREAD

**Issue by realtebo** [SocialiteProviders/Providers#683]
There is no doc about how to LOGOUT from a social provider.

**Comment by atymic** [comment]
Just use the normal laravel methods. They can sign in via the social provider again if needbe

**Comment by realtebo** [comment]
It is not enough. I destroy laravel section but at next social login the social user is still logged in remotely so user cannot change account.

Please don't close

Scarica Outlook per Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by atymic** [comment]
Which driver are you using? When you click do the socialite redirect, they will not be logged in. The provider should let you chose a specific account again (ie google)

**Comment by realtebo** [comment]
I am using Microsoft Azure Open  ID Connect.

I resolved redirecting user to official MS logout link, so user can really change account when they need.

**Comment by atymic** [comment]
Oh ok. I guess that's specific to the microsoft driver. Feel free to PR that to the microsoft docs:
https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft/README.md
