### ISSUE TITLE
Saml2 Provider - custom SP entity id

### ISSUE THREAD

**Issue by peppeocchi** [SocialiteProviders/Providers#705]
Hi, I was wondering if there is any way to manually set the SP entity id. By looking at the code [here](https://github.com/SocialiteProviders/Saml2/blob/master/Provider.php#L221) it uses `URL::to('auth/saml2')` as entity id.
It would be great if that could be customised.

I'm now integrating with a IDP and the developer I'm talking to sent me this message
>  I’ve seen issues with apps that use the same entity ID for all implementations, and that causes issues when dealing with multiple environments and the ability to support multiple IDPs.

Did I miss any configuration or function to set a custom SP entity id?

Thanks

**Comment by atymic** [comment]
Feel free to PR :D

**Comment by 27pchrisl** [comment]
This makes sense according to the spec. The implementation as it is sort of assumes each instance of your app (eg each customer) is on their own subdomain, causing different entity ids for different customers. If you don’t partition your app in the url like this you definitely need to be able to generate entity ids like (eg) http://app.com/auth/saml2/<customer id> so you know which customer to route an incoming assertion to.

**Comment by atymic** [comment]
Close in #707
