### ISSUE TITLE
Withings Provider need update to oAuth2

### ISSUE THREAD

**Issue by CecileV** [SocialiteProviders/Providers#715]
Hi,
The documentation say Withings API use oAuth2 : https://developer.withings.com/developer-guide/data-api/authentication

In the FAQ, it's write : 
https://developer.withings.com/developer-guide/faq/faq
![image](https://user-images.githubusercontent.com/10630411/128022605-a97b8aad-2762-4eaf-8489-d8e221aa51e2.png)

**Comment by atymic** [comment]
Feel free to PR

**Comment by atymic** [comment]
@CecileV want to PR?
