### ISSUE TITLE
MS Azure: compatibility with v2.0 Api endpoints

### ISSUE THREAD

**Issue by alessandrofuda** [SocialiteProviders/Providers#724]
Hi guys, 
for my needs I upgraded the provider to work with v2.0 of the API. Can I do a pull request?

The new endpoints version switched, for example, 
from:
`https://login.microsoftonline.com/common/oauth2/authorize` format
to:
`https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize` format

and it runs through some deprecated functionalities.
(`https://graph.windows.net` is deprecated too, the new is: `https://graph.microsoft.com`)

This leads to some changes to provider class.

I fixed it. Can I do a pull request?

**Comment by atymic** [comment]
Please PR :)

**Comment by alessandrofuda** [comment]
done
