### ISSUE TITLE
MS Azure Active Directory

### ISSUE THREAD

**Issue by alessandrofuda** [SocialiteProviders/Providers#725]
Hi, inside microsoft-azure package I have to override/extend the URLs inside `SocialiteProviders\Azure\Provider` class.
It contains v1 of API endpoints and I have to change it from v1 to v2 (and some other changes).

How can I override it without change package's source file? Thanks a lot.

I tried registering a new serviceprovider in my app and binding the new class, but it doesn't works..

**Comment by atymic** [comment]
Feel free to PR the fixes required.
