### ISSUE TITLE
Request Azure Active Directory user groups

### ISSUE THREAD

**Issue by jstam89** [SocialiteProviders/Providers#731]
Hi there,

I'm currently using Laravel Socialite for authentication and my goal is to aquire all the groups a user is in.
I've added a scope `GroupMember.Read.All` but the response doesn't seen to have the user groups in it. Anyone any idea how to get the user groups from a user in Azure Active Directory using Socialite with Microsoft Azure provider?

**Comment by atymic** [comment]
This provider will only give you the access token, I'd imagine you'd then need to query the graph api to get the groups?
https://docs.microsoft.com/en-us/graph/api/group-getmembergroups?view=graph-rest-1.0&tabs=http

**Comment by jstam89** [comment]
> This provider will only give you the access token, I'd imagine you'd then need to query the graph api to get the groups?
> https://docs.microsoft.com/en-us/graph/api/group-getmembergroups?view=graph-rest-1.0&tabs=http

Thnx for your reply, I solved my problem by swapping to graph during the process.

**Comment by atymic** [comment]
No worries, closing!
