### ISSUE TITLE
multiple Microsoft Azure AD connections

### ISSUE THREAD

**Issue by fruitl00p** [SocialiteProviders/Providers#732]
When implementing multiple MS Azure AD connections in a single app the `with` parameter doenst eems to work when instantiating a socialite provider (i.e. multiple directories all hosted on azure)

Also I seem to be missing the tentant config option to allow for branding of the login screen... ? is there any way to allow configuring the tenant aside from the 'common' it is now?

**Comment by atymic** [comment]
Feel free to PR to allow changing that :)

**Comment by fruitl00p** [comment]
@atymic it might be just a documentation issue: Using the withConfig() method and injecting the right Config instance this already is possible:
```php
function getConfig(): Config
  {
    return new Config(
      env('AD_CLIENT_ID', 'some-client-id'),
      env('AD_CLIENT_SECRET'),
      url(env('AD_REDIRECT_PATH', '/azuread/callback')),
      ['tenant' => env('AD_TENTANT_ID', 'common')]
    );
  }

Socialite::driver('azure')
      ->setConfig(getConfig())
      ->redirect();
```
and ofcourse:
```php
 $socialUser = Socialite::driver('azure')
        ->setConfig(getConfig())
        ->user();
```

in the same way, just passing the tenant in the extra config params actually works ;)

**Comment by atymic** [comment]
Could you PR a change to the docs? Thanks!

**Comment by atymic** [comment]
Will await your PR
