### ISSUE TITLE
Getting additional information (Microsoft provider)

### ISSUE THREAD

**Issue by blorange2** [SocialiteProviders/Providers#745]
I am using the Microsoft provider on Laravel 6 (back then it was called `graph`) to login users and get users information.

I get a whole bunch of fields based on the fields listed within this provider: https://github.com/SocialiteProviders/Providers/blob/master/src/Microsoft/Provider.php

What do I do if I want extra fields, such as department?

I currently get all fields listed in the above link.

```
protected const DEFAULT_FIELDS = ['id', 'displayName', 'businessPhones', 'givenName', 'jobTitle', 'mail', 'mobilePhone', 'officeLocation', 'preferredLanguage', 'surname', 'userPrincipalName'];
```

Could I copy this provider and then extend it so that I could override the protected constant?

I have also updated from using `graph` to `microsoft`

**Comment by atymic** [comment]
You can either update your provider, or backport the changes to a copy in your older version?
