### ISSUE TITLE
How can we use the refresh token?

### ISSUE THREAD

**Issue by ERROPiX** [SocialiteProviders/Providers#75]
Hi,

I have learned how to get a token after the login via OAuth 2 providers (like Envato), but the token expires after 1 hour. 

Any way how to handle this case?

Thanks

**Comment by faustbrian** [comment]
https://stackoverflow.com/questions/33988064/how-can-i-manage-oauth-refresh-tokens-with-laravel
https://laravel.io/forum/08-26-2016-handling-oauth-token-refresh-with-socialite
