### ISSUE TITLE
Provider Requests [See Description]

### ISSUE THREAD

**Issue by atymic** [SocialiteProviders/Providers#751]
This issue will collect all provider requests to keep things clean. Please comment your request, and once PR'd it will be removed :)

- [ ] Idporten (suggested @PragnaBrahmbhatt)
- [ ] Epic Games (suggested @belzaaron) 
https://dev.epicgames.com/docs/services/en-US/Interfaces/Auth/EASAuthentication/index.html
- [ ] Metamask (suggested @bigint) - metamask.io
- [ ] DeSo/BitClout (suggested @marlon-montgomery) - https://docs.deso.org/devs/identity-api

**Comment by atymic** [comment]
Added

> DeSo/BitClout (suggested @marlon-montgomery) - [docs.deso.org/devs/identity-api](https://docs.deso.org/devs/identity-api)

**Comment by littleblue50** [comment]
printful - https://developers.printful.com/docs

**Comment by Dectom** [comment]
Would be good to add Authentik (https://goauthentik.io/) (https://goauthentik.io/docs/providers/oauth2)

**Comment by ARCHES-Academy** [comment]
Could we get [Clever SSO](https://dev.clever.com/docs/identity-api) added as a provider? They provide SSO for various apps for the education sector.

**Comment by binaryfire** [comment]
I see a generic SAML provider was recently added. It would be great to get a generic OIDC provider.

**Comment by atymic** [comment]
> I see a generic SAML provider was recently added. It would be great to get a generic OIDC provider too.

Feel free to PR :)

**Comment by NikolaiL** [comment]
> DeSo/BitClout (suggested @marlon-montgomery) - https://docs.deso.org/devs/identity-api

updated link to the docs: https://docs.deso.org/deso-identity/identity

**Comment by remipelhate** [comment]
Hi there! My team and I have been working closely with [itsme](https://www.itsme-id.com/en-BE) for the past few months, a digital identity provider primarily used in Belgium and the Netherlands. For one of the projects, we developed a Socialite provider to use different itsme identification services. We'd like to add it to Socialite providers, however, I have a few questions:
- Our implementation comes with an extensive test suite (including a few E2E tests) to cover all the intricacies of the integration. However, according to the [docs](https://socialiteproviders.com/contribute/#tests), tests are only foreseen in the Manager package. Is there any way we can handle this within the providers repository? Or are we better off creating a package under our own vendor name and depend on it within this repository?
- Most of the providers seem to be following the major version of the Manager. Can I assume this a requirement? So our initial release for `itsme` would be `4.0.0`?

Thanks for your feedback!

**Comment by markusKautz** [comment]
I would love to see SeadyHQ [ https://steadyhq.com/de/ ]( https://steadyhq.com/de/ ) 
They are a german Crowdfunding Platform like Patreon 
[https://developers.steadyhq.com](https://developers.steadyhq.com)

**Comment by sympact06** [comment]
I would love to see Roblox oauth

**Comment by renatofrota** [comment]
I can't see [Amazon](https://github.com/SocialiteProviders/Amazon) listed on https://socialiteproviders.com - is it supported?

**Comment by rjoo** [comment]
Would it be possible to add support for PingFederate's SSO? https://docs.pingidentity.com/r/en-us/pingfederate-112/pf_authoriz_endpoint

**Comment by Nu11ified** [comment]
Add support for LogTo https://logto.io/en thanks

**Comment by pixeline** [comment]
A Bluesky provider would be awesome!

**Comment by JustinRijsdijk** [comment]
CFX.re / FiveM: https://github.com/TheIndra55/discourse-user-api-keys

I'll provide a PR.

**Comment by pixeline** [comment]
> Hi there! My team and I have been working closely with [itsme](https://www.itsme-id.com/en-BE) for the past few months, a digital identity provider primarily used in Belgium and the Netherlands. For one of the projects, we developed a Socialite provider to use different itsme identification services. We'd like to add it to Socialite providers, however, I have a few questions:

Wow @remipelhate  an Itsme integration would be a killer! For people outside Belgium: itsme is the go-to authentifcation system that most Belgian federal / regional institutions (but also private sectors such as banks, etc) use to allow citizen to easily connect to their account. 
Looking forward to check it out!

**Comment by Geovanek** [comment]
https://www.polar.com/br/developers
