### ISSUE TITLE
Keycloak Provider: Doc does not match current release version

### ISSUE THREAD

**Issue by marconett** [SocialiteProviders/Providers#773]
The current version of the Keycloak provider on Packagist is `5.0.0` (https://packagist.org/packages/socialiteproviders/keycloak#5.0.0).

But the docs (https://socialiteproviders.com/Keycloak/#installation-basic-usage), which seem to be pulled directly from the master of the repo, reference a provider function (`getLogoutUrl `) that does not exist in version `5.0.0`. It only exists in master (https://github.com/SocialiteProviders/Keycloak/tree/master).

Either the doc needs to point to the correct git tag, or a new package version should be released.

**Comment by atymic** [comment]
Looks like 5.1 was tagged which fixed this :)
