### ISSUE TITLE
Target class [SocialiteProviders\QQ\QQExtendSocialite] does not exist.

### ISSUE THREAD

**Issue by cmxpanda** [SocialiteProviders/Providers#775]
![image](https://user-images.githubusercontent.com/21009035/144859949-e81407cc-0f49-4ae0-aab5-389dc0f325fc.png)
Laravel 8

**Comment by thinkverse** [comment]
The class should be `SocialiteProviders\QQ\QqExtendSocialite`, notice the second lowercase `q` in the [QqExtendSocialite](https://github.com/SocialiteProviders/QQ/blob/00bf77170e73be69eb6fe661def3aa1ae5b7035d/QqExtendSocialite.php#L7) class. The README is currently wrong.
