### ISSUE TITLE
Apple: 400 Bad Request - invalid_client

### ISSUE THREAD

**Issue by dimitribocquet** [SocialiteProviders/Providers#780]
I'm trying to enable Apple Sign In with my API.

I've followed instructions from the Installation page: https://socialiteproviders.com/Apple/#installation-basic-usage.
I also used this article to generate a new Client Secret automatically: https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#generate-the-client-secret

When I go to my https://api.example.com/auth/apple/login, I have to sign in with my Apple account, etc.
But when I am redirected to https://api.example.com/auth/apple/callback, I have this error:

I am using it in Stateless, since I have no session.

```
Client error: `POST https://appleid.apple.com/auth/token` resulted in a `400 Bad Request` response: {"error":"invalid_client"}
```

LoginController:
```php
class AppleLoginController extends Controller
{
    public function __invoke(Request $request)
    {
        return Socialite::driver('apple')
            ->stateless()
            ->redirect();
    }
}
```

CallbackController:
```php
class AppleCallbackController extends Controller
{
    public function __invoke(AppleToken $appleToken)
    {
        config()->set('services.apple.client_secret', $appleToken->generate());

        $socialUser = Socialite::driver('apple')
            ->stateless()
            ->user();

        dd($socialUser);
    }
}
```

The client secret is successfully generated, but I always have `400 Bad Request - invalid_client` error when I want to get the user details.
I also tried to manually generate the client secret and added it in my `.env`, but it does not work either.

What did I miss?

Thank you for your help!

**Comment by dimitribocquet** [comment]
I forgot to put my Key ID. Now it's working!

**Comment by PirunSeng** [comment]
Excuse me @dimitribocquet , could you share your environment please? I can't get the issue of "Driver apple not supported" fixed.
Here are my environments:
```
"require": {
        "php": "^7.4",
        "laravel/framework": "^8.0",
        "laravel/socialite": "^5.2",
        "socialiteproviders/apple": "^5.0"
    },
```
Thanks in advanced for your support :)
