### ISSUE TITLE
Deprecation of Azure AD Graph

### ISSUE THREAD

**Issue by JaZo** [SocialiteProviders/Providers#787]
Microsoft has [deprecated](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview) Azure AD Graph and will close the service on June 30, 2022. Maybe it's good to also deprecate the [microsoft-azure](https://socialiteproviders.com/Microsoft-Azure/) provider? Or am I mixing things up? Please tell me if I do 😄.

**Comment by ashjmcfox** [comment]
I believe this provider has been updated to use the Microsoft Graph API which is not deprecated. Therefore no action required.

See https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences

Source code is referencing `https://graph.microsoft.com`, not `https://graph.windows.net` in `Provider.php`

https://github.com/SocialiteProviders/Microsoft-Azure/blob/481b8cbbf61ae5401d3cfc63d1ab3aa71842e1cf/Provider.php#L21

**Comment by JaZo** [comment]
Ahhh, good to know @ashjmcfox, didn't notice that! Do you also know the difference between [microsoft-azure](https://socialiteproviders.com/Microsoft-Azure/) and [microsoft](https://socialiteproviders.com/Microsoft/)?

**Comment by ashjmcfox** [comment]
I think [microsoft](https://socialiteproviders.com/Microsoft/) supports authenticating users with their Microsoft account, which can be created at https://signup.live.com/.

Whereas [microsoft-azure](https://socialiteproviders.com/Microsoft-Azure/) allows users to authenticate with their work credentials, if their employer is provisioning accounts using Microsoft Active Directory. The account email would be using a company domain; @company-name.com etc.

**Comment by JaZo** [comment]
That makes sense, thanks!
