### ISSUE TITLE
Saml2 Provider - disable cache or customise cache key

### ISSUE THREAD

**Issue by peppeocchi** [SocialiteProviders/Providers#810]
Hi

I just stumbled on an issue with the Saml2 Provider, specifically around cache. I don't see an option to disable it or at least to customise the cache key.
I have a SAAS product where each tenant can "install" a Saml2 authentication, which means each tenant will have its own configuration/metadata. So the metadata can't be cached as it is without customising the cache key, otherwise all tenants will get the same metadata, which is the problem.
I could "disable" it by setting a ttl to 0, or clearing it out programmatically before every attempt, but it's a workaround rather than a solution.

It would be great to have a "cache: true/false" configuration where cache can be enabled or disabled, or better to have a method to customise the cache key so each tenant gets its own version.

As a side note, I don't understand why there is a need to store on a separate cache entry the ttl, can't it just be set as expiration of the metadata cache entry, instead of caching it ["forever"](https://github.com/SocialiteProviders/Saml2/blob/master/Provider.php#L184)?

**Comment by 27pchrisl** [comment]
There's currently a bunch of changes being made to the provider in https://github.com/SocialiteProviders/Providers/pull/781/files, probably this is another good one to make.
