### ISSUE TITLE
Firebase\JWT\BeforeValidException: Cannot handle token prior to ..

### ISSUE THREAD

**Issue by lsmith77** [SocialiteProviders/Providers#811]
I just used `socialiteproviders/azureadb2c` and I received

```
Error on validationg id_token. Firebase\JWT\BeforeValidException: Cannot handle token prior to 2022-03-03T11:02:13+0000 in /app/vendor/firebase/php-jwt/src/JWT.php:142
```

I suspect I might have to adjust the `leeway` setting:
https://github.com/googleapis/google-api-php-client/issues/1630

Since JWT is used in several providers I wonder if there should be a global setting for this?

**Comment by atymic** [comment]
Fixed in new version

**Comment by lsmith77** [comment]
can you elaborate how the issue was fixed specifically?
in the recent commits I found https://github.com/SocialiteProviders/Providers/pull/854 but looking at the change log for v6 I don’t see how this “fixes” the problem I faced.
