### ISSUE TITLE
EveOnlineProvider for `"firebase/php-jwt": "^5.2"` broken

### ISSUE THREAD

**Issue by herpaderpaldent** [SocialiteProviders/Providers#813]
The latest commit to the EveOnline Provider breaks existing installations using `"firebase/php-jwt": "^5.2"`

In order to use `JWT::decode()` with firebase/php-jwt v5.2 one needs to set the used algorithm as it was done prior to:
https://github.com/SocialiteProviders/Providers/commit/6faaad86d37bce45b7856f714a29b692f8497df4#diff-ee2dbdcc9514c641873a948c269b54572040cd0b8d80dac3de71f7381ab9cf08L86 
```php
 $decodedArray = (array) JWT::decode($jwt, JWK::parseKeySet($responseJwksInfo), ['RS256']);
 ``` 
Else this error is being thrown:
https://github.com/firebase/php-jwt/blob/v5.5.1/src/JWT.php#L121
```php
if (empty($algorithm)) {
            // Use deprecated "allowed_algs" to determine if the algorithm is supported.
            // This opens up the possibility of an attack in some implementations.
            // @see https://github.com/firebase/php-jwt/issues/351
            if (!\in_array($header->alg, $allowed_algs)) {
                throw new UnexpectedValueException('Algorithm not allowed');
            }
        }
```

However the firebase/php-jwt v6.0 does not have the third argument anymore https://github.com/firebase/php-jwt/blob/v6.0.0/src/JWT.php#L85

I suggest reverting: https://github.com/SocialiteProviders/Providers/commit/9e494cbfb615866bd6aac4e469fdc007158417f8

**Comment by atymic** [comment]
@herpaderpaldent 

Can you please PR your suggested fix. Can we just re-drop 5.x support, and anyone using jwt 6.x will be able to use the new version?

**Comment by herpaderpaldent** [comment]
Hey @atymic 

i have used your branch to create the PR and add additional instructions on how to delete the current *4.1.0* tag from github and packagist. Revoming this tag is vital.

https://github.com/SocialiteProviders/Providers/pull/815

**Comment by Grasume** [comment]
@atymic Yeah can you push off the #815 branch

**Comment by herpaderpaldent** [comment]
Has been resolved.
