### ISSUE TITLE
Repo Subtree Split is broken

### ISSUE THREAD

**Issue by atymic** [SocialiteProviders/Providers#820]
We're ending up with only a single commit in each repo, previously this had the proper history. Investigate.

**Comment by atymic** [comment]
@lucasmichot not sure if this was a side effect of upgrading some of our actions workflows at some point. Previously the subtree split has all the commit history for that folder, now it seems we only get the single latest commit, even if it's for a different provider. Any ideas?

**Comment by lucasmichot** [comment]
Thanks for opening the ticket @atymic, I have investigated and could see any similar issue during the upgrade for v2 to v3.
I have nevertheless created a PR worth testing: #838
