### ISSUE TITLE
OpenID Connect implementation

### ISSUE THREAD

**Issue by fabricecw** [SocialiteProviders/Providers#823]
There are multiple issues about the implementation of OpenID Connect. In #751 it seems OpenID is not yet on the roadmap. What do you think about a generic OpenID Connect provider? If you think it makes sense, we will take care of it and PR this provider.

**Comment by Braunson** [comment]
Following up on this!

**Comment by fabricecw** [comment]
I'm still confused why no one seems to be interested in an OpenID Connect implementation. OIDC became a popular standard when it comes to SSO authentication. At least for enterprises.

Maybe I am missing something.
