### ISSUE TITLE
getAvatar broken for Microsoft provider

### ISSUE THREAD

**Issue by has-n** [SocialiteProviders/Providers#824]
```Client error: `GET https://graph.microsoft.com/v1.0/me/photo/$value` resulted in a `404 Not Found` response: {"error":{"code":"UnknownError","message":"{\r\n \"errorCode\": \"ErrorProfileNotFound\",\r\n \"message\": \"Exception (truncated...)```

404 is returned if the user has not assigned a profile picture. The endpoint can be tested before returning null.

**Comment by atymic** [comment]
Feel free to make a PR wrapping it in a try/catch :)
