### ISSUE TITLE
37signals (Basecamp) Socialite provider not showing up on website

### ISSUE THREAD

**Issue by rvanbaalen** [SocialiteProviders/Providers#850]
There is a socialite provider for Basecamp (37signals): 

https://github.com/SocialiteProviders/37Signals

But it's not showing up on the socialite website https://www.socialiteproviders.com

The link to the website from the repo even returns a 404:

https://socialiteproviders.com/37Signals/

Would be nice to get this fixed. If I knew how I would have provided a PR.

**Comment by atymic** [comment]
PR it here :)
https://github.com/SocialiteProviders/website/blob/master/providers.js

**Comment by rvanbaalen** [comment]
@atymic Just did that :-)

On another note; 37Signals has completely rebranded to Basecamp. 

Previously, 37Signals was the mother company of all their products. Today, it's all called Basecamp.
Since it would be a massive breaking change to rename 37signals to Basecamp in the Socialite provider repo, I would suggest creating a new repo for Basecamp.

If I knew how to contribute, I'll be more than happy to make a clone of the 37signals provider and rename it all to Basecamp.
