### ISSUE TITLE
Keycloak Logout Failed on latest Keycloak Version (18.0)

### ISSUE THREAD

**Issue by azophy** [SocialiteProviders/Providers#859]
I just tried to use [SocialiteProviders/Keycloak](https://socialiteproviders.com/Keycloak/) package and all features (redirect, callback, getUser) seemed working fine except the logout functions. this is the screenshot of keycloak error page I encountered:

![image](https://user-images.githubusercontent.com/2698551/171649922-983e27ed-1b53-4263-87dc-8c0e8721e1c8.png)

I suspect this package suffers from the same problem described in https://github.com/mariovalney/laravel-keycloak-web-guard/issues/71

## further reference
- https://www.keycloak.org/docs/latest/upgrading/index.html#openid-connect-logout

**Comment by atymic** [comment]
https://github.com/SocialiteProviders/Keycloak/releases/tag/5.2.0
