### ISSUE TITLE
Laravel 5.4 - Socialite Providers multiple configurations with Twitter

### ISSUE THREAD

**Issue by pirmax** [SocialiteProviders/Providers#86]
I have two services to connect with Socialite Provider:

    use Laravel\Socialite\Facades\Socialite;
    use \SocialiteProviders\Manager\Config;

    public function connect_1() {
    	$config1 = new Config(
    	    env('TWITTER_CONSUMER_KEY_1'),
    	    env('TWITTER_CONSUMER_SECRET_1'),
    	    env('TWITTER_REDIRECT_URI_1'),
    	    [
    	        //
    	    ]
    	);
    
    	return Socialite::with('twitter')->setConfig($config1)->redirect();
    }
    
    public function connect_2() {
    	$config2 = new Config(
    	    env('TWITTER_CONSUMER_KEY_2'),
    	    env('TWITTER_CONSUMER_SECRET_2'),
    	    env('TWITTER_REDIRECT_URI_2'),
    	    [
    	        //
    	    ]
    	);
    
    	return Socialite::with('twitter')->setConfig($config2)->redirect();
    }

But, I have this error when I try this code:

> Configuration for TWITTER_KEY is missing. There is no services entry
> for twitter

**Comment by faustbrian** [comment]
Did you place the ENV Variables from the documentation into your .env place together with your custom ones? They are required for the provider to boot and can stay empty.

```php
TWITTER_KEY=
TWITTER_SECRET=
TWITTER_REDIRECT_URI=

TWITTER_CONSUMER_KEY_1=yourkeyfortheservice
TWITTER_CONSUMER_SECRET_1=yoursecretfortheservice
TWITTER_REDIRECT_URI_1=https://example.com/login

TWITTER_CONSUMER_KEY_2=yourkeyfortheservice
TWITTER_CONSUMER_SECRET_2=yoursecretfortheservice
TWITTER_REDIRECT_URI_2=https://example.com/login
```

**Comment by pirmax** [comment]
I can't stay empty.

I must add chars and I have the same error.

**Comment by faustbrian** [comment]
Before posting my previous reply I quickly tested it on my local machine and it works just fine. The `Twitter1` or `Twitter2` credentials will be used instead of the `Twitter` ones.
