### ISSUE TITLE
Socialite Apple code is null

### ISSUE THREAD

**Issue by KentKongH** [SocialiteProviders/Providers#866]
Somehow when I try to sign in with apple id it always return invalid_request when the callback hits https://appleid.apple.com/auth/token 
after some checking I notice the $code is null.

**Comment by atymic** [comment]
cc @rcerljenko @pyrou @damonto
I don't use this provider, is one of you able to help? Thanks !

**Comment by damonto** [comment]
Can you provide more details? For example code snippets.

**Comment by KentKongH** [comment]
Sure, after i have clicked on the continue button
![image](https://user-images.githubusercontent.com/25153275/180348988-f030725b-ef46-4fd9-aefe-5d2b6777f532.png)

I get an error response invalid_request from the https://appleid.apple.com/auth/token and I am sure I have the correct include the correct client_id and secret in my env
![image](https://user-images.githubusercontent.com/25153275/180349054-24b5684e-3c6f-4e98-83c7-4447a81ebcdc.png)

And I realized in the Provider.php the function getAccessTokenResponse it has the $code in it but when I tried to dd it all it return null.
![image](https://user-images.githubusercontent.com/25153275/180348903-778571a3-2744-453f-92e7-a0cbd3060481.png)

I also tried dd in $_POST["code"] since response_mode is a form_post method and to my surprise it returned the code in it.

**Comment by damonto** [comment]
I don't have an API Key/Secret to test Apple Sign-in right now.

Can you try dd $this->request->all(), request()-all(), $_POST in the Provider.php the function getAccessTokenResponse  to see the difference?

**Comment by KentKongH** [comment]
Here's the result

dd $this->request->all() 
![image](https://user-images.githubusercontent.com/25153275/180362182-946988e6-9719-4ade-b386-d258f74e703d.png)

dd request()->all()
![image](https://user-images.githubusercontent.com/25153275/180362397-c2e03c98-4786-49a6-9e59-a9b77931d38b.png)

dd $_POST
![image](https://user-images.githubusercontent.com/25153275/180362772-62322d7c-5d3f-41cd-8fcf-72f93a116ecd.png)

Only $_POST return the code

**Comment by damonto** [comment]
Which version of Laravel are you using? Did you reset or recreate the Illuminate\Http\Request in your code?

**Comment by KentKongH** [comment]
> Which version of Laravel are you using? Did you reset or recreate the Illuminate\Http\Request in your code?

I am using Laravel Lumen 8.3.4 and nope i didn't reset or recreate the Illuminate\Http\Request in my code

**Comment by damonto** [comment]
I don't know what happened to your application, but I think you can use the following code to solve it temporarily

```php
public function handleCallback(Request $request) 
{
    if (! $request->has('code')) {
        $request->merge(['code' => $_POST['code']]);
    }

    $user = Socialite::driver('apple')->user();

    dd($user);
}
```
