### ISSUE TITLE
Stripe Provider sending the wrong ID

### ISSUE THREAD

**Issue by danrovito** [SocialiteProviders/Providers#87]
When using the stripe provider the docs call to add this to my ENV

```
STRIPE_KEY=yourkeyfortheservice
STRIPE_SECRET=yoursecretfortheservice
STRIPE_REDIRECT_URI=https://example.com/login  
```

The actual URL of the stripe oauth calls for the `client_id` and not the stripe key, which is whats being put into the URL.  The `client_id` is created when you create an app in Stripe connect.  That ID is what needs to be sent in the `client_id` parameter.

`https://connect.stripe.com/oauth/authorize?client_id=pk_test_XXXXXXXXXX&redirect_uri`

**Comment by faustbrian** [comment]
STRIPE_KEY=client_id https://github.com/SocialiteProviders/Manager/blob/master/src/Config.php#L20-L22

If something is not working properly you are always free to send a PR to fix it.

**Comment by faustbrian** [comment]
No feedback received, re-open it the issue still persists.
