### ISSUE TITLE
[SAML2] Best way to support multiple IdP's

### ISSUE THREAD

**Issue by jakeland** [SocialiteProviders/Providers#889]
Hi all, 

I'm trying to get multiple IdP's working with the SAML2 Provider. 
I would like to allow specific users to store the metadata and other relevant info for each IdP in my Database, and then use those to alter the metadata and routes dynamically. 

I wanted to get the metadata to return with a different sp_acs before I tried anything really intense. 
However, it looks like I am misunderstanding something. 

The acs is removed when I attempt to do this. 

Is there currently any way to support multiple IdP's that would work better than this?  

My initial attempt is the following: 

Services Config: 

    'saml2' => [
        'sp_acs' => env('SP_ACS'),
        'entity_id' => env('SAML_ENTITY_ID'),
        'metadata'=> env('IDP_METADATA') ? file_get_contents(env('IDP_METADATA')) : '', //  if statements used so that i  can get around missing files on localhost
        'sp_certificate' => env('SP_SAML_CERT') ? file_get_contents( env('SP_SAML_CERT')) : '' ,
        'sp_private_key' => env('SP_PRIVATE_KEY') ? file_get_contents(env('SP_PRIVATE_KEY')) : '', 
      ],`
Route file:
```
Route::get('/auth/saml2/{idpName}/metadata', function ($idpName) {
    // get the idp metadata
    log_info('test', $idpName);
    $config = Config::get('services.saml2'); 
    $config['sp_acs'] = "/auth/".$idpName."/jumpcloud-callback-test-url"; // test, minimum viable change. 

    $config = new \SocialiteProviders\Manager\Config("secret", "secret", "secret", $config);
    
    return Socialite::driver('saml2')->setConfig($config)->getServiceProviderMetadata();

});
```

Expected Result: 
```
<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://station.local/auth/saml2" ID="_1b04b07ae8fc4aa73038eeb7b1e2ea76e34c237eb5"><SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol" WantAssertionsSigned="true"><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat><AssertionConsumerService index="0" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://station.local/auth/test/jumpcloud-callback-test-url"/></SPSSODescriptor></EntityDescriptor>
```

Actual Result: 
```
<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://station.local/auth/saml2" ID="_eeb413a5db6840e79870b5650b98a2eb3cf0b279a9"><SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol" WantAssertionsSigned="true"><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat></SPSSODescriptor></EntityDescriptor>

```

**Comment by 27pchrisl** [comment]
Hi @jakeland, sure no problem. Ultimately I think your use case (multi-tenant, multi-idp) is more complex than this simple Socialite driver is intended to handle. It's trying to provide a real simple interface for a single-idp use case.

I'd recommend implementing litesaml/lightsaml directly, maybe lifting the code out of the socialite driver into your code as a starting point?

**Comment by jakeland** [comment]
thanks @27pchrisl  👍 

Was pretty sure that was the case, but needed to double check
