### ISSUE TITLE
Patreon Provider return bad request when using v2 API

### ISSUE THREAD

**Issue by WillyReyno** [SocialiteProviders/Providers#890]
Hello, 

I'm using the Patreon Provider with v1 API keys and everything works fine. However, when I try with v2 API keys I get the following error : 

 ```
 Client error: `POST https://api.patreon.com/oauth2/token` resulted in a `400 Bad Request` response: {"error": "invalid_request", "error_description": "Missing code parameter."}
``` 

I don't see any documentation regarding v2 API on the provider, so I'm wondering if it's even supported?

**Comment by atymic** [comment]
Is it possible that they use different endpoints? Can you link their docs.

**Comment by WillyReyno** [comment]
Here it is https://docs.patreon.com/#apiv2-oauth

**Comment by WillyReyno** [comment]
@amr-coding I continue using the v1 API for the mean time

**Comment by atymic** [comment]
Feel free to PR an update to the provider.
