### ISSUE TITLE
Flickr Issue

### ISSUE THREAD

**Issue by ebisbe** [SocialiteProviders/Providers#9]
Hello,

I'm not sure that I have to post the issue here but the flickr socialite provider keeps asking to grant permissions each time I call to login. I've manage to save the responded user and save it to the session. Is that the way flickr works?

**Comment by faustbrian** [comment]
Don't have a Flickr account so can't test it.

**Comment by ebisbe** [comment]
Ok, thanks. I'll try to find it in the Flickr documentation.

**Comment by faustbrian** [comment]
If it isn't Flickr in this case let me know.
