### ISSUE TITLE
Received HTTP status code [401] with message "This feature is temporarily unavailable" when getting token credentials.

### ISSUE THREAD

**Issue by nicoalvarez-cd** [SocialiteProviders/Providers#90]
![image](https://user-images.githubusercontent.com/12100047/28366440-17d5790e-6c63-11e7-9832-772e59e0e031.png)

anyone knows which can be the issue?
it's with twitter provider.. and find this working for almost all the users.. but fail in 10/15 of almost 250 users... 

using Laravel 5.4 and "socialiteproviders/twitter": "^3.0"

**Comment by faustbrian** [comment]
If you google the error message you will find different results, some state it is an issue on Twitters side and just starts working again randomly.

**Comment by faustbrian** [comment]
No feedback received, re-open it the issue still persists.
