### ISSUE TITLE
Etsy sunsetting v2 for v3 OAuth2

### ISSUE THREAD

**Issue by cdburgess** [SocialiteProviders/Providers#909]
Are there any plans to upgrade the Etsy OpenApi to v3 since v2 is being sunsetted in Q4 2022?  I am happy to figure this out but I would rather not duplicate any work that may be coming.

**Comment by atymic** [comment]
As far as I know, no. Feel free to PR.

**Comment by cdburgess** [comment]
Pull request created. Please let me know if you have any questions. This has been tested on my local environment with my Etsy credentials and is working as expected.
