### ISSUE TITLE
Laravel 5.2 - Socialite Providers Twitter give me bad authentication data

### ISSUE THREAD

**Issue by pirmax** [SocialiteProviders/Providers#91]
I use **Laravel 5.4** with **Socialite Providers** ([http://socialiteproviders.github.io/providers/twitter/][1])

I want build an application with two Twitter services with no the same credentials.

I use this in **services.php**:

    'twitter' => [
        'client_id' => env('TWITTER_KEY'),
        'client_secret' => env('TWITTER_SECRET'),
        'redirect' => env('TWITTER_REDIRECT_URI'),
    ],

I have this to my controller:

    $config = new SocialiteProvidersConfig(
        env('TWITTER_CONSUMER_KEY_2'),
        env('TWITTER_CONSUMER_SECRET_2'),
        env('TWITTER_REDIRECT_URI_2')
    );
    
    return Socialite::with('twitter')->setConfig($config)->redirect();

I have my credentials to **.env**:

    TWITTER_KEY=
    TWITTER_SECRET=
    TWITTER_REDIRECT_URI=
    
    TWITTER_CONSUMER_KEY_2=xxx
    TWITTER_CONSUMER_SECRET_2=xxx
    TWITTER_REDIRECT_URI_2=http://localhost/twitter/login/callback
    
    TWITTER_CONSUMER_KEY_3=xxx
    TWITTER_CONSUMER_SECRET_3=xxx
    TWITTER_REDIRECT_URI_3=http://localhost/twitter/login/callback

But, I have this error when I try to connect my Twitter account:

> Received HTTP status code [400] with message
> "{"errors":[{"code":215,"message":"Bad Authentication data."}]}" when
> getting temporary credentials.

I have the impression that the configuration is not taken into account.

[![enter image description here][2]][2]

  [1]: http://socialiteproviders.github.io/providers/twitter/
  [2]: https://i.stack.imgur.com/TFtoC.png

**Comment by faustbrian** [comment]
Try this commit https://github.com/SocialiteProviders/Manager/commit/4cc05ae61f5ca4fbc6dd08b304f915fb35c1199c

**Comment by faustbrian** [comment]
If the issue still continues to exist just re-open.
