### ISSUE TITLE
Getting null back for user when using LaravelPassport

### ISSUE THREAD

**Issue by shahnewazshahidi** [SocialiteProviders/Providers#922]
Hello, 

Not sure if I'm messing up some setup, but I did install fresh copies on two laptops and got the same result on both.  Using Laravel Passport and the related socialite plugin, I'm getting null for all the user fields.

`SocialiteProviders\Manager\OAuth2\User {#323 ▼ // routes/web.php:13`
`+id: null`
`+nickname: null`
`+name: null`
`+email: null`
`+avatar: null`
`+user: []`
`+token: "Z...MGVlNDE ▶"`
`+refreshToken: "def502...bee8 ▶"`
`+expiresIn: 31536000`
`+approvedScopes: null`
`+accessTokenResponseBody: array:4 [▶]`
`}`

using:
`Socialite::driver('laravelpassport')->userFromToken($token);`
Also returns nulls.

Any troubleshooting hints would be greatly appreciated.  As well as if I can provide any additional info.  

Thank you

**Comment by atymic** [comment]
I'd put a `dd()` in the `getUserByToken` function of the provider to see exactly what's returned. Guessing there's a mismatch in fields or scopes here.

**Comment by shahnewazshahidi** [comment]
Thank you. Assuming userFromToken function:

`Route::get('/auth/callback', function () {`
    `    $user_token = Socialite::driver('laravelpassport')->user()->token;`
    `    dd( Socialite::driver('laravelpassport')->userFromToken($user_token));`
`});`

Outputs:

`SocialiteProviders\Manager\OAuth2\User {#321 ▼ // routes/web.php:16`
`  +id: null`
`  +nickname: null`
`  +name: null`
`  +email: null`
`  +avatar: null`
`  +user: []`
`  +token: "eyJ0..TBmNzNhMWMyMzk0Y2ExMzAwZTI2NGI2ZWE ▶"`
`  +refreshToken: null`
`  +expiresIn: null`
`  +approvedScopes: null`
`  +accessTokenResponseBody: null`
`}`

Is there something I should be checking in the Passport side?

Attaching a screenshot of 
`    dd(Socialite::driver('laravelpassport'));`

![Screenshot 2022-10-04 at 11-15-33 Screenshot](https://user-images.githubusercontent.com/50636175/193858603-d1488cc5-ab92-4732-a01a-48a6ffb03eca.png)

Thank you

**Comment by shahnewazshahidi** [comment]
Must update middleware in /routes/api in passport server. Change from sanctum to api

From:
`Route::middleware('auth:sanctum')->get('/user', function (Request $request) {`
`     return $request->user();`
` });`

To:
`Route::middleware('auth:api')->get('/user', function (Request $request) {`
`    return $request->user();`
`});`
