### ISSUE TITLE
Add a Steein provider

### ISSUE THREAD

**Issue by jenniferhub** [SocialiteProviders/Providers#93]
https://github.com/SteeinRu/oauth2-steein - This package includes many, additional components

**Comment by faustbrian** [comment]
Feel free to send a PR for a Provider. You can either use https://github.com/SocialiteProviders/Generators or take a look at other Providers to see how they are structured.

**Comment by faustbrian** [comment]
Still no PR, if you still want to add the provider feel free to send one. Closing for now.
