### ISSUE TITLE
Shopify provider issue

### ISSUE THREAD

**Issue by mcirami** [SocialiteProviders/Providers#937]
When using Socialite::driver('shopify')->redirect() it's not redirecting correctly to Shopify for the user to login. Looks like it's missing the first part of the url that actually goes to Shopify. Browser just says 'This site can't be reached.' This is what I get in the browser address bar:

https://admin/oauth/authorize?client_id=<my_client_id>&redirect_uri=https%3A%2F%2Feca4-174-86-205-0.ngrok.io%2Fapi%2Fauth%2Fcallback&scope=&response_type=code&state=LZkYo4vSGwYarMq6e0WrOSosH5tMkRdOB17Tq64x

I am also using this for the Mailchimp provider and everything is working correctly for that, so I know I have everything set up correctly in the EventServiceProvider and Services files.

**Comment by atymic** [comment]
You can either pass the subdomain in the shop query param, or set it via the subdomain config
https://github.com/SocialiteProviders/Providers/blob/master/src/Shopify/Provider.php#L84

**Comment by mcirami** [comment]
is that the only parameter that can be added? Shopify also needs to add a 'scope' parameter in the url.  I tried adding that to the $additionalProviderConfig array but it doesn't add it to the url.
