### ISSUE TITLE
Is SocialiteProviders/Xing broken?

### ISSUE THREAD

**Issue by tobiasdalhof** [SocialiteProviders/Providers#94]
Hello, 

can anyone confirm that SocialiteProviders/Xing is working?

Looks like XING disabled their API for new users. I am only able to create a "Login with XING Plugin" which provides me a consumer key & signature salt

**Comment by faustbrian** [comment]
Check http://socialiteproviders.github.io/providers/xing/ to learn how to use the consumer key and secret XING provides you.

**Comment by tobiasdalhof** [comment]
I'm getting follow exception:

```
(1/1) CredentialsException Received HTTP status code [401] with message "{"message":"Invalid OAuth signature","error_name":"INVALID_OAUTH_SIGNATURE"}" when getting temporary credentials.
```

My .env file looks like this
```
XING_KEY=consumerkeyhere
XING_SECRET=signaturesalthere
XING_REDIRECT_URI=http://laravel.dev/login/xing/callback
```

The "Signature salt" provided by XING equals the XING_SECRET config, right?!

Routes
```php
Route::get('login/xing', 'Auth\LoginController@redirectToXING')->name('login.xing');
Route::get('login/xing/callback', 'Auth\LoginController@handleXINGCallback')->name('login.xing.callback');
```

LoginController
```php
    /**
     * Redirect the user to the XING authentication page.
     *
     * @return mixed
     */
    public function redirectToXING()
    {
        return Socialite::with('xing')->redirect();
    }

    /**
     * Obtain the user information from XING.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function handleXINGCallback()
    {
        try {
            $XINGUser = Socialite::driver('xing')->user()->user;

            dd($XINGUser);

            return redirect()->intended(route('frontend.home'));
        }
        catch (Exception $e) {
            return redirect()->route('user.login');
        }
    }
```

No idea whats wrong here :cry:

**Comment by faustbrian** [comment]
I don't remember what XING called their things as they always want to be special and never name the things what they actually are but I found an test application on my local machine that is working just fine, so if you have the right credentials everything should be working fine if you have the right permissions set up.

**Comment by tobiasdalhof** [comment]
Looks like the they closed their API for new users. I contacted XING for further information.

Thanks for your effort

**Comment by faustbrian** [comment]
I will try to contact someone who works at XING and let you know if I get more information.

**Comment by faustbrian** [comment]
From what my friend that works at XING could tell me there are currently security issues with the API and some business clients experience major issues trying to implement OAuth, they are currently working on a new API that should be ready till end of the year.

**Comment by tobiasdalhof** [comment]
Interesting... Thank you! Looks like I have to stick with LinkedIn OAuth for now. 🤔

**Comment by OzanKurt** [comment]
@tobiasdalhof Any updates about the topic?

**Comment by tobiasdalhof** [comment]
@OzanKurt Nope, sorry! You could try to contact the Xing team for more info
