### ISSUE TITLE
FACEIT provider asks for undefined Guzzle constant

### ISSUE THREAD

**Issue by PatryQHyper** [SocialiteProviders/Providers#947]
Line 44 in file: faceit\Provider.php asks for ClientInterface::VERSION, which in Guzzle 7 is undefined.
`$postKey = (version_compare(ClientInterface::VERSION, '6') === 1) ? 'form_params' : 'body';`

ClientInterace has MAJOR_VERSION constant instead.

Installed guzzle version: 7.5.0

**Comment by atymic** [comment]
Feel free to PR and just drop the support for guzzle 6

**Comment by PatryQHyper** [comment]
The main problem is that this repo and Faceit repo on default branches don't have $postKey anymore. I think you should just release a new version from master branch

**Comment by atymic** [comment]
Tagged a new version
https://github.com/SocialiteProviders/Faceit/releases/tag/4.2.0

Thanks!
