### ISSUE TITLE
Slack oauth url redirecting to a url that is not for the app.

### ISSUE THREAD

**Issue by JSponaugle** [SocialiteProviders/Providers#95]
**Expected Behavior:**
Click Login/Signup
Redirect you url https://(slackteam).slack.com/oauth/<data>
Click 'Continue'
At Dashboard.

**Current Behavior:**
Click Login/Signup
Redirect you url https://(slackteam4).slack.com/oauth/<data>
ERROR: OAuth Error: invalid_team_for_non_distributed_app

**How to Reproduce:**
1. Login to slackteam1 https://(slackteam).slack.com/
2. Login to slackteam4 https://(slackteam4).slack.com/
3. Go to your Login page on laravel. Click slack Login

I assume need a way to direct people to the correct slackteam oauth url. Might need another configuration.

**Comment by faustbrian** [comment]
Are you sure you are setting the correct redirect url? Looks very strongly like an issue with your configuration which results in handling the wrong team.

**Comment by faustbrian** [comment]
No feedback received, re-open it the issue still persists.

**Comment by appcarevenkataramana** [comment]
The same issue found, how to solve this issue....?
