### ISSUE TITLE
SAML2 Driver does not honor stateless

### ISSUE THREAD

**Issue by robertdeboer** [SocialiteProviders/Providers#955]
## What
The SAML2 provider does not honor the stateless configuration when used with the redirect call. This causes the SAML callback to fail as it does not exit the state check due to this and then fails as the SAML response may not contain state. It throws an `InvalidState` exception.

## When
Whenever you attempt to set the redirect as stateless

## Where
If you use the stateless configuration when producing the redirect:
```php
return Socialite::driver('saml2')->stateless()->redirect();
```
The processing of the user data on the callback route will fail here `vendor/socialiteproviders/saml2/Provider.php`, line 444 due to this function at line 491:
```php
    protected function hasInvalidState(): bool
    {
        if ($this->isStateless()) {
            return false;
        }

        $state = $this->request->session()->pull('state');

        return !(strlen($state) > 0 && $this->messageContext->getMessage()->getRelayState() === $state);
    }
```

However it pulls the stateless configuration, it is not seeing it as described in the Socialite Providers documentation [here](https://socialiteproviders.com/usage/#_5-usage)

## How
I am not sure. I have not dug deeper to find out how exactly the stateless "state" is set and propagated.

**Comment by atymic** [comment]
cc @27pchrisl

**Comment by 27pchrisl** [comment]
Hi @robertdeboer, from a SAML perspective are you trying to use the stateless feature to support unsolicited (ie IDP-initiated) logins? I don't think the code would support that, it would have to be modified to do so.

The `isStateless` check is just mirroring what all the other OAuth providers do but it doesn't have any functionality for that in the Saml2 provider.

**Comment by robertdeboer** [comment]
@27pchrisl 
I am trying to stop the following behaviour. When sending a standard redirect for login on the IDP and it sends the customer back, it is generating an InvalidStateException. So in order to avoid this and because the SSO is technically stateless, I used the `->stateless` method on the redirect as described in the generic provider documentation.

However, even when I used this, the check on the return from the service provider is still checking the state of the request even though the `->stateless` method is being used and so the state check "should" not check

**Comment by 27pchrisl** [comment]
Hi @robertdeboer, I tested this using:

```php
Route::post('/auth/callback', function () {
    $user = Socialite::driver('saml2')->stateless()->user();
    dd($user);
});
```
as the receiver, and `https://samltest.id/start-sp-test/` to start a stateless login, and it did work correctly (skipped the state check). Is there any more information about your configuration you can provide?

**Comment by robertdeboer** [comment]
@27pchrisl,

I will try that and let you know. According to the docs [here](https://socialiteproviders.com/usage/#stateless) the stateless method is shown to be use on the redirect and not the callback. I will try the callback and see if that works.
