### ISSUE TITLE
[Microsoft Azure] pass refresh_token as a grant_type

### ISSUE THREAD

**Issue by guillaumeboussion** [SocialiteProviders/Providers#966]
It looks like there's no way with the current implementation to get a new `access_token` by using the provided `refresh_token` (when having the `offline_access`). Would you be open to a PR for this enhancement ?

**Comment by atymic** [comment]
Feel free to PR!

**Comment by atymic** [comment]
cc @guillaumeboussion

**Comment by atymic** [comment]
Feel free to PR if you get around to it.

**Comment by Tamas-hi** [comment]
I was looking for the same thing, and believed this is not implemented. But you can call refreshToken() on the azureProvider and you will get back what you need:

$azureProvider = Socialite::driver('azure');
$refreshTokenResponse = $azureProvider->refreshToken($azureToken->refresh_token); // contains new accessToken, new accessTokenExpires and new refreshToken
