### ISSUE TITLE
Azure provider not returning `id_token` in newer versions

### ISSUE THREAD

**Issue by etfz** [SocialiteProviders/Providers#973]
Hi,

I previously installed the microsoft-azure provider version 3.1 (old PHP/Laravel version) and successfully received an object containing `id_token`, `refresh_token` and more. When using a newer Laravel version, it instead installed version 5.1 of the provider, and I no longer receive those fields. I'm not too experienced with this stuff, so is this intended? Am I not meant to receive an `id_token`?

**Comment by atymic** [comment]
Can you post redacted output?
