### ISSUE TITLE
Providers not being published to packagist?

### ISSUE THREAD

**Issue by saade** [SocialiteProviders/Providers#985]
Hello, yesterday i've contributed with GovBR provider, it got merged and added to the website.

I've noticed that `socialiteproviders/govbr` and others are not published in packagist, see other examples.

`socialiteproviders/usos` #972 
`socialiteproviders/onelogin` #949 
`socialiteproviders/webflow` #942
...

did i miss something?

**Comment by atymic** [comment]
Looks like the publish script token expired. Shall publish them now, new ones should be published again.

**Comment by saade** [comment]
Sweet! Thanks!
