### ISSUE TITLE
StreamElements got new syntax

### ISSUE THREAD

**Issue by bilbodog** [SocialiteProviders/Providers#997]
Hi there,
I think there might be an issue with the StreamElements provider in Socialite. Right now, when it generates the link, it makes the scope with the old syntax:

**Old syntax (with comma)**
scope:scope,scope:scope,scope:scope

**New syntax (with space)**
scope:scope scope:scope scope:scope

Here are the same examples where the link has been generated:
**Old syntax (%2C)**
`https://streamelements.com/oauth2/authorize?client_id=<ClientID>&redirect_uri=<URL>&response_type=code&scope=tips%3Aread%2Ctips%3Awrite%2Cloyalty%3Aread%2Cloyalty%3Awrite&state=<string>`

**New syntax (%20)**
`https://streamelements.com/oauth2/authorize?client_id=<ClientID>&redirect_uri=<URL>&response_type=code&scope=tips%3Aread%20tips%3Awrite%20loyalty%3Aread%20loyalty%3Awrite&state=<string>`

I would be very happy, if this got fixed! 😃

**Comment by atymic** [comment]
Do you have a link to the docs?

**Comment by bilbodog** [comment]
> Do you have a link to the docs?

https://dev.streamelements.com/docs/api-docs/cd02cda5171ea-o-auth2

**Comment by bilbodog** [comment]
I was in contact with the StreamElements community, where I was tipped of by another user, shown in the picture. But at the moment the scope wasn't an issue. The issue at that moment was that StreamElements forgot to activate my account.

But after that was figured out, then the scope became an issue.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/16679010/227134469-b9745682-738d-4a36-b776-cdb97187f882.png">
